### ISSUE TITLE
Device error state

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#10]
Is there a register to surface an error state in device?

**Comment by pelikhan** [comment]
does jacdac still broadcast while in panic mode?

**Comment by pelikhan** [comment]
I understand we want to avoid a broken device polluting the bus with error messages.

**Comment by jamesadevine** [comment]
Yeah, I think you'd just continue sending advertisement reports with some error flag set. A JD debugger/brain could then interrogate a device for its error state when connected

**Comment by tballmsft** [comment]
- bit in the advertisement packet for failure
- register in the control service tells you the reason for a failure

**Comment by pelikhan** [comment]
Base register in the service definition

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac/pull/91
