### ISSUE TITLE
support for role bound, unbound evens

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#1003]
![image](https://user-images.githubusercontent.com/4175913/167263175-c04d14b6-c06d-4c81-aa90-39b7bcf0c7e2.png)

**Comment by mmoskal** [comment]
Already supported see https://github.com/microsoft/jacscript/blob/main/README.md#roles

**Comment by pelikhan** [comment]
Missing support for compiling isConnected()

![image](https://user-images.githubusercontent.com/4175913/167272564-626179cb-67f1-4158-962f-0c7d1d4881b6.png)
