### ISSUE TITLE
"Add Blocks" button present though all services loaded

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1009]
1. load [pelikhan/pxt-kitronik-air-quality/jacdac](https://makecode.microbit.org/beta#pub:github:pelikhan/pxt-kitronik-air-quality/jacdac) into MakeCode
2. create a program as shown below
3. press the "add simulator" button
4. see that "Add Blocks" button appears
5. click on it to see it wants to add extension that is already loaded

![image](https://user-images.githubusercontent.com/10767146/167486253-b48efda1-1bac-4537-ab0a-bd0c7269f9c5.png)

**Comment by pelikhan** [comment]
which version of the makecode editor is this in? make sure to use beta.

**Comment by tballmsft** [comment]
ah, yes, much better in beta
