### ISSUE TITLE
losing up event with button

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1014]
1. using our JD button
2. put this code on micro:bit: https://makecode.microbit.org/_FPKUVRCjCPyJ
3. push button quickly
4. see that we lose up event (heart sometimes stays)

**Comment by pelikhan** [comment]
- [ ] test with RP2040 banding dual G0 button. Eventually the RP2040 can't handle a hf2 message. We get a timeout and don't really handle it well.
![image](https://user-images.githubusercontent.com/4175913/168384932-8c4f23e4-fd4b-4d0d-8ac5-e3c94c83a271.png)

**Comment by pelikhan** [comment]
we need a test brain that does not use the makecode stack to be able to isolate issues faster.

**Comment by tballmsft** [comment]
But I agree it will be useful to have a C-only brain to help isolate things (using the VM to do testing?)

**Comment by pelikhan** [comment]
Are you testing this from makecode or the dashboard?
Are we loosing the event on the hardware or on the simulator?

**Comment by pelikhan** [comment]
I think it's a race between "showicon" which uses the animation system of CODAL and "clearScreen" which just wipes out the screen buffer. To stabilize this demo, either add led.stopAnimations() in up and use showIcon with an empty icon.

As a sanity check add ``music.playTone(400, 50)`` in up to ear the up event and not rely on the screen.
