### ISSUE TITLE
QR codes on modules are not correctly linked

### ISSUE THREAD

**Issue by alyssacaples** [microsoft/jacdac#1015]
**Describe the bug**
When scanning a few of the modules, the QR code will bring you to a 404-error message instead of the module's information. I noticed this issue when using the following modules:

- JM-3-Sliders
- JM-Rotary
- JM-Hall
- JM-Base
- JM-Buzzer
- JM-RGB-8

**To Reproduce**
1. Scan the code on the back.
2. Click on the link.
3. See error

**Expected behavior**
It should show the module's information. 

**Screenshots**
![image-20220513-203446-acbb6b0d](https://user-images.githubusercontent.com/60932038/168386838-12017dc7-f71d-4660-abdb-5725bcbbabff.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 15.4.1
 - Safari

**Comment by pelikhan** [comment]
The full list at https://microsoft.github.io/jacdac-docs/tools/qr-silk/

**Comment by pelikhan** [comment]
fix https://github.com/microsoft/jacdac-docs/commit/5afa98c02bad9d90ec0d4f68ae450c34d9a345fe

**Comment by pelikhan** [comment]
fixed.
