### ISSUE TITLE
LED Simulation module cannot turn off LEDS once started

### ISSUE THREAD

**Issue by alyssacaples** [microsoft/jacdac#1016]
**Describe the bug**
When simulating the JM RGB-8 83 v4.0 in MakeCode, once you click an LED to turn it on, you are unable to click it again to turn off. In general, you would want to be able turn on/off different LEDs.  

**To Reproduce**
1. Go to MakeCode
2. Simulate a JM RGB-8 by clicking the 'start simulator' button
3. Click on the LEDS in the model to start and stop the LED simulation

**Expected behavior**
You should be able to turn off the LEDs. 

**Screenshots**
![image](https://user-images.githubusercontent.com/60932038/168390701-bb091fdb-8a34-4082-a936-51105824ab11.png)

**Comment by pelikhan** [comment]
Fixed. One should not interact with leds from makecode... only through code!
