### ISSUE TITLE
able to connect to jacdac and makecode at the same time

### ISSUE THREAD

**Issue by alyssacaples** [microsoft/jacdac#1019]
**Describe the bug**
I was able to connect to microbit to makecode and jacdac at the same time, with both sites recognizing and displaying the digital simulation when I pressed physical buttons. This seems like an issue with possibly having multiple controllers for one device. 

I had been switching between jacdac and makecode all day to understand the software better.

**Comment by pelikhan** [comment]
This one is very tricky. I've made jacdac-docs less aggressive about connecting to the device so that it's not constantly locking it.
