### ISSUE TITLE
floating parameters in makecode

### ISSUE THREAD

**Issue by alyssacaples** [microsoft/jacdac#1020]
**Describe the bug**
I duplicated a block and after moving the block around, my arguments started "floating" around the UI. See picture for reference. 

Possibly due to having many blocks running. 

**To Reproduce**
1. Duplicate a block
2. Click on it to move around.
3. Determine if parameters remain in correct position.

**Expected behavior**
When you move a block, the arguments are supposed to stay in line. 

**Screenshots**
![image](https://user-images.githubusercontent.com/60932038/168395319-a3e6a247-c71d-4de3-ab9a-00d6f2b7c883.png)

**Comment by pelikhan** [comment]
Looks like a makecode/blockly bug, unlike we fix this.
