### ISSUE TITLE
Disconnecting over and over again

### ISSUE THREAD

**Issue by alyssacaples** [microsoft/jacdac#1028]
**Describe the bug**
Device (ESP32/brain) continually disconnects and reconnects over and over again. This makes it impossible to connect to the Azure IoT hub. I noticed this issue occurs with the temperature/humidity sensor and the motion sensor. 

**To Reproduce**
1. Go Jacdac device dashboard. 
2. Connect device. 
3. You can choose to open console & open serial connection or not, but overall, you will be able to see device connecting and reconnecting over and over again. 

**Expected behavior**
Although the device normally disconnects and reconnects from time to time, this is excessive and prevents connection to the Azure IoT Hub. The device essentially crashes after it successfully connects to wifi and then tries to make a stable connection with the Azure IoT hub. 

**Additional context**
![jacdac_connection_bug](https://user-images.githubusercontent.com/60932038/170095437-302ffd07-3ac7-43d4-94be-48806a9b5952.gif)

**Comment by pelikhan** [comment]
can you export the console output and attach it as well? also click on "save trace" and attach it

**Comment by alyssacaples** [comment]
the two files as requested
[trace.jd (1).txt](https
[jacdac-console.txt](https://github.com/microsoft/jacdac/files/8765955/jacdac-console.txt)
://github.com/microsoft/jacdac/files/8765944/trace.jd.1.txt)

**Comment by alyssacaples** [comment]
Solved: The issue was the device was not connected to the internet. 

![image](https://user-images.githubusercontent.com/60932038/170130696-1396dc21-c716-4f06-88bc-67ddbe474844.png)

If you see these lines in the console, or something similar, it means the device cannot connect to the internet, which then causes it to reboot.
