### ISSUE TITLE
updating docs

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1029]
A variety of updates need to be done:

- [x] /overview/kit/oob/ is out-of-date, needs to be refreshed with microbit-machine and moved somewhere else (it is for micro:bit V2, should do something reasonable for commonly available modules). 
- [x] /overview/kit/ should be removed, as well as /overview/kit/unbox.
- [x] review /clients/makecode/user-guide/ - revisit dongle mode - are we cutting down the scenario
- [x] review /clients/makecode/extensions/
- [x] review /clients/makecode/projects/
- [x] review /clients/makecode/code/
- [x] review /clients/makecode/servers/
- [x] get rid of /overview/ and move content elsewhere (confusing!)
- [x] review /ddk
- [x] update FAQs
- [x] update blog

**Comment by pelikhan** [comment]
We should probably rename OOB to something else and move somewhere else

**Comment by tballmsft** [comment]
yes, that is in process...
