### ISSUE TITLE
Wifi Config Bug

### ISSUE THREAD

**Issue by alyssacaples** [microsoft/jacdac#1030]
**Describe the bug**
If you attempt to configure the device's wifi settings, regardless if it is already connected to wifi or not, it will display a screen stating "Something went wrong. Please reload the page." 

**To Reproduce**
1. Go to Jacdac device dashboard
2. Connect a device
3. Press the gear button next to the wifi settings

**Expected behavior**
It should let you view available networks and then select and enter the password of desired network. Instead, it crashes. 

**Additional context**
![jacdac_wifi_config_bug](https://user-images.githubusercontent.com/60932038/170133063-203260d7-ecbe-4310-a0b3-19845f16ebfe.gif)

**Comment by pelikhan** [comment]
Please try again, it should be fixed. (and close if fixed).
