### ISSUE TITLE
jacdac branding is not consistent

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1032]
this page  https://microsoft.github.io/jacdac-docs/overview/ looks like this:
![image](https://user-images.githubusercontent.com/12393831/170291903-8f4fa7cc-cc73-4031-b15f-707c9e656ca8.png)
but it should look like this:
![image](https://user-images.githubusercontent.com/12393831/170291987-c557b9af-7db3-4983-b7e8-510e7d5ce428.png)
here is the SVG to use:
![Jacdac Logo](https://user-images.githubusercontent.com/12393831/170292037-012c588d-cbd2-4589-87c8-b77bb8cf99eb.svg)

these other pages also have a bad font:
https://microsoft.github.io/jacdac-docs/clients/
https://microsoft.github.io/jacdac-docs/tools/
https://microsoft.github.io/jacdac-docs/overview/connectorcable/

the correct font is 'Sen (Regular)'

**Comment by pelikhan** [comment]
Removed icon so that it does not look like a logo. We need to do a review of the other font before using it.
