### ISSUE TITLE
Bootloader Mode Additional Information Needed

### ISSUE THREAD

**Issue by alyssacaples** [microsoft/jacdac#1033]
**Is your feature request related to a problem? Please describe.**
When devices go into bootloader mode, it would be helpful if the information button told you how to resolve the problem. Without it, it is not intuitive to resolve by resetting the device inside the update firmware tab. 

**Describe the solution you'd like**
It would let you reset the device then and there, or it would tell you the steps on how to resolve the issue. 

**Additional context**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/60932038/170312967-2fa2cfc1-bf66-4ef1-9271-771db5af999d.png)

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/jacdac-docs/commit/5fb11947f438acf5633d2e217ea5489cf24e0e73
