### ISSUE TITLE
device registration page

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1034]
Regarding this page https://microsoft.github.io/jacdac-docs/tools/device-registration/ 
1. Kitronik appears twice in the list of mfrs:
![image](https://user-images.githubusercontent.com/12393831/170348528-354dad49-c1d1-4db6-a0e6-4ca33ff588eb.png)

2. Not sure why we are asking about the Jacdac connector (what does the answer affect later down the road?). But in any case, the options: 
![image](https://user-images.githubusercontent.com/12393831/170347163-1fa970d7-a776-424e-9425-149d4b5469aa.png)

are not consistent with our definitions on https://microsoft.github.io/jacdac-docs/ddk/design/ :
![image](https://user-images.githubusercontent.com/12393831/170347337-cc41c741-b9ef-4d10-bc1f-55dd321f83ce.png)

if we want mfrs to call out high current power providers separately from low current power providers we should have:
No PCB edge connector
PCB edge connector, independently powered - no power transfer either way
PCB edge connector, pure consumer - power always taken from Jacdac bus
PCB edge connector, pure provider onto Jacdac bus, low current
PCB edge connector, pure provider onto Jacdac bus, high current
PCB edge connector, dynamically powered, low current provision
PCB edge connector, dynamically powered, high current provision

**Comment by sehodges** [comment]
Also, it's not clear to me what power category passive hubs fall into? I guess they might be the last one because power can flow in any direction?!

**Comment by sehodges** [comment]
can this:
![image](https://user-images.githubusercontent.com/12393831/170359403-b240b955-bd2e-4754-a72b-4138852a164e.png)

say "Firmware binary repo" and can this:
![image](https://user-images.githubusercontent.com/12393831/170359487-9c72a046-eb51-41c0-803f-0fc140ab902b.png)

say "Firmware source repo" ?

**Comment by sehodges** [comment]
and I guess this:
![image](https://user-images.githubusercontent.com/12393831/170364641-6ab44ace-177a-471f-a72a-5be0a746bddc.png)

should say "Hardware design repo"

**Comment by pelikhan** [comment]
> Also, it's not clear to me what power category passive hubs fall into? I guess they might be the last one because power can flow in any direction?!
 Let's add a category for them

**Comment by pelikhan** [comment]
I think all the issues are fixed here.
