### ISSUE TITLE
makecode client leaks event handler

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#1046]
The clients use CODAL event system, `control.onEvent(....)`, to dispatch handlers. However, there is no reliable way to unregister those handlers.

**Comment by tballmsft** [comment]
OK, can we replace the use of CODAL event system with something else? I thought that Jacdac provided its own pub/sub system.

**Comment by pelikhan** [comment]
we want the same semantics as other makecode events at the user/block level


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
