### ISSUE TITLE
better tag line for Jacdac?

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1047]
Current:

* Jacdac: Plug-and-play for microcontrollers

New ideas:

* Jacdac: Device creation for everyone
* Jacdac: Working with hardware has never been this easy...
* Jacdac: Sensors have never been this easy...
* Jacdac: Creating devices is easy
* Jacdac: Electronics has never been this easy
* Jacdac: Creating devices has never been this easy
* Jacdac: Building devices has never been this easy
* Jacdac: Building and programming devices has never been this easy
* Jacdac: Plug-and-play device creation 
* Jacdac: plug-and-play physical computing
* Jacdac: plug-and-play for creating with microcontrollers
* Jacdac: plug-and-play hardware creation

**Comment by pelikhan** [comment]
Done.
