### ISSUE TITLE
videos of various demos

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1059]
video (-> animated gif) of hand plugging/unplugging cable/connector

**Comment by pelikhan** [comment]
for where?

**Comment by tballmsft** [comment]
good question - the videos on the start page are nice. i see you've replaced the videos on the makecode client page.

what about the blog?

**Comment by pelikhan** [comment]
Can you reuse some of them?
________________________________

**Comment by tballmsft** [comment]
yeah, I'll rewrite to incorporate them
