### ISSUE TITLE
mark services stable

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1071]
https://microsoft.github.io/jacdac-docs/tools/service-status/

the following services should be marked stable:
- [ ] https://microsoft.github.io/jacdac-docs/services/led/
- [ ] https://microsoft.github.io/jacdac-docs/services/lightlevel/
- [ ] https://microsoft.github.io/jacdac-docs/services/lightlevel/
- [ ] https://microsoft.github.io/jacdac-docs/services/potentiometer/
- [ ] https://microsoft.github.io/jacdac-docs/services/rotaryencoder/
- [ ] https://microsoft.github.io/jacdac-docs/services/temperature/

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac/commit/c2ba3f6f02423f1c55cb5898ab3c496e5d24c7f2
