### ISSUE TITLE
related Jacdac devices

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1078]
We need a way to link (two ways) Jacdac devices that may not be part of the same kit. For example:
- /devices/microbit-educational-foundation/microbitv2/

Should reference all Jacdaptors for the micro:bit V2, including:

- /devices/kittenbot/jacdaptorformicrobitv2v10/

So that
- when we visit micro:bit V2, see all the Jacdaptors for V2 as "related devices"
- when we visit a Jacdapdtor for micro:bit V2, we see micro:bit as "releated devices"

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac-docs/commit/1161eacfdc8a3d59b30a31df64fc17e30d9ee8f7
