### ISSUE TITLE
embedding Jacscript in markdown

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1087]
Can we have the ability to give sample Jacscript programs in markdown (and have them load in separate page?)

**Comment by tballmsft** [comment]
We should also have projects for JacScript available everywhere:

![image](https://user-images.githubusercontent.com/10767146/172696617-f6f1589a-0c7d-41a9-afef-a08ae8b689cc.png)

**Comment by pelikhan** [comment]
We don't have a décompiler and the block editor is not ready for prime time.
