### ISSUE TITLE
requires micro:bit V2 (not included)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1088]
Three things related to messaging

1. 
```
Extra micro:bit V2 needed.
```
Should really be
```
Requires micro:bit V2 (not included)
```

2. The above message should be on Kit A with Jacdaptor, as well as Jacdaptor by itself.

3. What sort of (needs XYZ) message should be on Kit A (with no Jacdaptor)?

**Comment by pelikhan** [comment]
Fixed 1,2

**Comment by tballmsft** [comment]
For 3, what about something like

* This kit only contains Jacdac modules. To create a complete Jacdac system, you will need to purchase a Jacdac brain, and possibly a Jacdaptor.

We need to have a notion of what a "complete system" is made of:
- Jacdac brain
- Jacdac module 
- Jacdaptor

Of course, we have software-only, where you only need a Jacdac brain.

Thoughts?

**Comment by tballmsft** [comment]
Simplify for now: Kit A with Jacdaptor (focused first on micro:bit).
