### ISSUE TITLE
micro:bit V2.0 jukebox connection problem

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1097]
Repro:

1. load latest microbit-jukebox onto micro:bit (in my case, a v2.0)
2. connect via USB to dashboard
3. see micro:bit connect
4. a few seconds later, get this message
```
device "BBC micro:bit CMSIS-DAP" (A transfer error has occurred.)
```

This is repeatable. Can't make progress past this.

**Comment by tballmsft** [comment]
Update: I tried with a v2.2 micro:bit. It's fine.

**Comment by pelikhan** [comment]
Is this a jukebox issue or a general jacdac issue?

**Comment by tballmsft** [comment]
USB. It seems like it is something to do with my work computer. Let me take the v2.0 home and see if the problem persists there.

**Comment by tballmsft** [comment]
V2.2 works fine for me, so no longer blocked.
