### ISSUE TITLE
firmware update always unsuccessful

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1098]
Trying to update LED ring and never makes it more than halfway before disconnecting. Same with button module. 

![image](https://user-images.githubusercontent.com/10767146/172950217-d286b387-ad60-4a3e-99da-eecea5209ac2.png)

**Comment by pelikhan** [comment]
It is actually updated but the logic to check the version seems wrong 
![image](https://user-images.githubusercontent.com/4175913/172952984-951f80e6-a395-4471-9086-1841ad0b10e3.png)
