### ISSUE TITLE
need a video for following scenario (coding with MakeCode)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1099]
Peli, can you make a single video for the following scenario from the blog:

* MakeCode editor, showing creation of a simple program that sets all the LEDs blue when a button down event is received, and turns the LEDs off when a button up event is received.  
* Inset shows the above code deployed to a micro:bit V2. 
* Note that the program continues to function when the keycap button is replaced by a rotary button, as both modules support the button service. 

Other things that could be shown
- program running in MakeCode against simulators, then against physical devices

**Comment by pelikhan** [comment]
Added as 
```
<Video
    label="Programming a button in MakeCode"
    src="blog-makecode-happy-button"
/>
```
