### ISSUE TITLE
getting started with no hardware

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1105]
https://github.com/microsoft/jacdac-docs/blob/main/src/pages/start.mdx says that you don't need any special hardware to get started in the second sentence.

then it goes on to say "Visit the Jacdac [device dashboard](https://github.com/microsoft/jacdac-docs/blob/main/dashboard) and connect your device which allows you to visualize the device twins for each connected modules."

so which is it?!

**Comment by tballmsft** [comment]
yeah, that's the problem with multiple editors and POVs.

we need to have a link to the section on how to work with no hardware.

**Comment by tballmsft** [comment]
Updated: https://microsoft.github.io/jacdac-docs/start/
