### ISSUE TITLE
makecode page button video not working

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1106]
I moved the micro:bit live video to the end of the page https://microsoft.github.io/jacdac-docs/clients/makecode/

The video player does not appear when you press the button:

![image](https://user-images.githubusercontent.com/10767146/173207661-f8b1da7a-fe17-466a-91a9-18d8433cc377.png)

**Comment by pelikhan** [comment]
We can completely remove it.

**Comment by tballmsft** [comment]
will do
