### ISSUE TITLE
update connector design document

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#1117]
The connector PDF https://github.com/microsoft/jacdac-ddk/blob/main/connector/JACDAC_PCB_Edge_Connector_Drawing_JD-PEC-02_rev_05.pdf is still marked as preleminary.

**Comment by tballmsft** [comment]
https://github.com/microsoft/jacdac-ddk/tree/main/connector

**Comment by tballmsft** [comment]
Need new links, @sehodges

**Comment by pelikhan** [comment]
http://aka.ms/jacdac-edge-connector

**Comment by pelikhan** [comment]
http://aka.ms/jacdac-ec30

**Comment by pelikhan** [comment]
I've done a pass at updating some links. most likely some missed

**Comment by tballmsft** [comment]
thanks, @pelikhan. I will double check.
