### ISSUE TITLE
refactor of docs around accessories/interop with existing platforms

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1120]
ATM our accessories docs are overly focussed on micro:bit. It's fine to only have details for micro:bit, but we should structure the docs so it's clear that there will be others too. 

Can we do something like change 'MICRO:BIT ACCESSORIES' below into 'MICRO:BIT INTEROP' and underneath it put 'Raspberry Pi Interop'? I already created a raspberry-pi.mdx file for this.

Thanks!

**Comment by pelikhan** [comment]
I'm not sure what you are referring to. Can you please add more details?

**Comment by sehodges** [comment]
sorry, meant to paste a pic:
![image](https://user-images.githubusercontent.com/12393831/173864157-d69f15b9-0bab-409c-9917-07047da80281.png)

**Comment by tballmsft** [comment]
My understanding is that you want a generic section "Interop" under the DDK and put the brain-specific files there.

**Comment by tballmsft** [comment]
I can work on that.

**Comment by sehodges** [comment]
OK, I changed it myself. Need to wait and see if it worked...
