### ISSUE TITLE
prevent users selecting zero Jacdac edge connectors on the left in the board outline generator

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1123]
please can we prevent users selecting zero Jacdac edge connectors on the left in the board outline generator, e.g. on [this page](https://microsoft.github.io/jacdac-docs/ddk/design/ec30/):

![image](https://user-images.githubusercontent.com/12393831/173909311-54007f9c-7b84-46b2-84a2-227f86753236.png)

**Comment by pelikhan** [comment]
Fixed.
