### ISSUE TITLE
rename box.svg to device.svg

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1124]
when you download a module outline the filename defaults to box,svg, but it's not a box. please can we call it device.svg or device-outline.svg? (BTW don't call it module.svg because it applies to devices other than modules like brains and jacdaptors). 

Also, why display this filename in the UI? can we remove it from the UI?

![image](https://user-images.githubusercontent.com/12393831/173918151-184f5088-19df-4ea0-b8d6-753e3d9f3116.png)

**Comment by pelikhan** [comment]
file name removed
