### ISSUE TITLE
make image the right scale

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1125]
I added an image on [this page ](https://microsoft.github.io/jacdac-docs/ddk/microbit/) but it's very large. Please can you make it a more appropriate size? When you've done it I'll try to remember to look and see how you did it.

Thanks!

![image](https://user-images.githubusercontent.com/12393831/173930163-a7bd6063-8c98-49df-b7e0-d3aa7582e5ca.png)

**Comment by pelikhan** [comment]
we don't have the source of this page. for other diagrams, we actually moved to using draw.io ( vscode extension is at https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio ).

See this image: https://github.com/microsoft/jacdac-docs/blob/main/static/images/jdbus.drawio.svg

**Comment by sehodges** [comment]
I don't have time to get up to speed with draw.io so unless there is a ppt->draw.io converter I'll stick with the image.

**Comment by pelikhan** [comment]
Where is the source of this image in case it needs to be updated?
