### ISSUE TITLE
update references to hardware designs in device specs

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#1128]
Once we have stabilized the location of the modules (current and deprecated), update url references in device specs.

For example, this commit move folders (https://github.com/microsoft/jacdac-ddk/commit/28dab8280b8d34ca7ff5f98e2e31bffe4d7abc61) and broke links in https://github.com/microsoft/jacdac/blob/main/devices/microsoft-research/jmmicrobitshieldlp29v05.json

**Comment by tballmsft** [comment]
any old prototype will now be in

https://github.com/microsoft/jacdac-ddk/tree/main/electronics/deprecated_form_factor

The URL could be updated by simply inserting "deprecated_form_factor", but I wonder if we want to do that?

The other option is to eliminate the hardware design reference from the json for deprecated form factor (make it harder to find).

@sehodges ?
