### ISSUE TITLE
"pure/idempotent" commands

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#113]
I am proposing to annotate commands with a "pure" attribute, which means that the command can be called without changing the internal state of the device.

This is usefull, for example, to automatically display the result of "list required roles" in the role manager, without running the risk of launching a rocket.

**Comment by mmoskal** [comment]
`list required roles` should logically be a read-only register, but the response may be too long, so it's a command opening a pipe. Maybe we should have syntax for pipe-registers?

**Comment by pelikhan** [comment]
Yes pipe register sound good.

note: MakeCode piped time out silently and returns partial data. Needs fixing

**Comment by mmoskal** [comment]
Never did this.
