### ISSUE TITLE
open source hardware certification

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#1136]
It seems that we qualify, should we certify our reference designs through https://application.oshwa.org/apply ?

**Comment by sehodges** [comment]
not sure. would we have to check with CELA to get permission? presumably we wouldn't then put the OSHWA mark on our PCBs - so the benefit is just that we can tell people we're OSHWA compliant. but I think most people will understand it's open source from the licences we have on our repo. OTOH if it's a lightweight process there is probably no harm.
