### ISSUE TITLE
searching for 'qr' doesn't find the QR code generator page

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1137]
![image](https://user-images.githubusercontent.com/12393831/174410060-1bc373e4-7884-4f71-b031-c0e5c5ddb58c.png)
 
can we fix this?

**Comment by pelikhan** [comment]
fixed by https://github.com/microsoft/jacdac-docs/commit/bf41de086cf0f44ec8140bf7348442d38359bc3a

Typescript pages were not indexed.
