### ISSUE TITLE
update photos for MSR Modules

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1139]
I took new photos of the EC30 MSR modules that I have. I think I followed the guidelines. I put them [here](https://microsofteur.sharepoint.com/teams/MSRPhysicalComputing-AzureIoTandJD/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fteams%2FMSRPhysicalComputing%2DAzureIoTandJD%2FShared%20Documents%2FJACDAC%20%28internal%29%2Fboards%20%26%20modules%2FMSR%20module%20photos&FolderCTID=0x012000EAD8900091FCF6468801C34AC589FB90.) If you like them please update them in the device catalog.

**Comment by pelikhan** [comment]
You can find the current pictures in https://github.com/microsoft/jacdac/tree/main/devices/microsoft-research and override them. Then the build will optimize them automatically and they will trickle up to the web site once we upgrade the submodule references.

Make sure your picture are 4:3 form factor
