### ISSUE TITLE
auto-import of info for device registration may not be correct

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1142]
I have a module that I may not have flashed with exactly the right information - I made a few minor changes to one of michal's firmware setups. But when I auto-import into the device registration page I get:
![image](https://user-images.githubusercontent.com/12393831/174684676-ba30ae2e-ba2c-4d99-8414-891b0e6de992.png)
and I'm pretty sure that's a bit funky?

**Comment by sehodges** [comment]
also tried this with the padauk-powered MSR 'tact' button module I made / put online as a reference design - which michal did the firmware for. the auto-import of information seemed worse in that it was all blank apart from the product id and the services:

![image](https://user-images.githubusercontent.com/12393831/174687725-fe6f6164-d9d1-4b22-b9b8-192b7dd2df66.png)

**Comment by mmoskal** [comment]
the second one is expected - Padauk doesn't have the module name in the firmware

**Comment by pelikhan** [comment]
Should be smarter about design identifier there so much it can do.
