### ISSUE TITLE
add more info about creating a personal access token for the device registration pull request

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1143]
obviously I'm a newbie here, but when I followed the instructions for creating a personal access token on github to allow my device registration to complete, initially I missed a step. having created the token I needed to assign it to Microsoft. before I did this I got this error:

![image](https://user-images.githubusercontent.com/12393831/174685280-3dbe7156-0e27-42ad-bc49-dd577cf1a99b.png)

please can you add another phrase to the short instructions in the dialog that pops up saying that having created the token with 'repo' attribute it needs to be assigned? might help someone else who's similarly inexperienced...

**Comment by sehodges** [comment]
I think you have to use the 'configure SSO' dropdown in github and then select the org:

![image](https://user-images.githubusercontent.com/12393831/174686392-974775af-0d42-4cab-bfeb-9ae6b8a20b63.png)

**Comment by sehodges** [comment]
and do I need to keep a copy of the token? github told me I'd not get another chance to copy it, but I thought that it would be remembered in the jacdac website. 

I'm doing another device registration and it doesn't seem to remember -has asked for it again. so we might want to warn users they will have to enter it each time? or should they generate a new one each time (even though it lasts for 30 days)?

**Comment by pelikhan** [comment]
Yes we forget it. It much more safe that way. You can store your token in your password manager.

Added more information about the SSO org... which is mostly something that Microsoft employees will face.
