### ISSUE TITLE
auto-generated device catalog URL may be wrong in the device registration page?

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1144]
I got the following from the device registration page:

![image](https://user-images.githubusercontent.com/12393831/174685531-00b04747-3158-4e0f-8463-5ea7e95de135.png)

which looks wrong to me because I think it should have /devices/ in the URL? apologies if this is my mistake, can't actually check it against my device just yet - but it didn't seem consistent with other device URLs?

**Comment by pelikhan** [comment]
Good catch.
