### ISSUE TITLE
after device registration the page doesn't clear

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1147]
after I've gone thru device registration successfully (I think?), I see:

![image](https://user-images.githubusercontent.com/12393831/174686571-8968b5be-b7bd-4882-9503-6e664e4692c4.png)

but then in a few seconds that pop-up has gone and the page looks unchanged. I'm kinda left wondering if it really worked. in a way it's nice that the info isn't just removed from the page, but if it really worked I think we should indicate that to the user. maybe a dialog with two options: 'continue with a new registration' (that wipes everything) or 'revise data in order to re-register'?

**Comment by pelikhan** [comment]
Using an alert now that does not go away.
