### ISSUE TITLE
can't read accel values in tree

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#1159]
see attached picture
<img width="707" alt="Screen Shot 2022-06-21 at 11 20 05 AM" src="https://user-images.githubusercontent.com/10673976/174870885-c424d62d-516f-4132-a9b4-1249e264cd2b.png">

Maybe we can do 2 decimal points or longer text?

The same applies to gyro.

**Comment by mmoskal** [comment]
also maybe use "toFixed" and don't cut the zeros? now the values jump quite a bit...

**Comment by pelikhan** [comment]
It should cut it according to precision. I think I have that logic somewhere else

**Comment by mmoskal** [comment]
we don't distinguish between absolute and relative precision; I think it may be better to have a fixed precision per unit/service

**Comment by pelikhan** [comment]
Longer text...
