### ISSUE TITLE
Light -> programmable light 

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#116]
Proposed name change to be more descriptive

**Comment by pelikhan** [comment]
@mmoskal ok with "ProgrammableLED" ?

**Comment by pelikhan** [comment]
or something better, but less generic than "light"

**Comment by mmoskal** [comment]
maybe LED pixels or something? the key part is that they are individually controlled (like pixels in a screen)

@jamesadevine @tballmsft opinions?

**Comment by pelikhan** [comment]
Pixel light?

________________________________

**Comment by jamesadevine** [comment]
LEDPixel(s) seems good!
