### ISSUE TITLE
hardware overview does not match toc 

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#1161]
in ddk/design,

![image](https://user-images.githubusercontent.com/4175913/175093620-d4eade52-2e24-458a-b36d-41406c7a04c7.png)

**Comment by tballmsft** [comment]
the page does have other sections, in the same order as TOC. Everything in the TOC is referred to, just not in the overview.

**Comment by pelikhan** [comment]
It is a bit confusing because it starts with a incomplete bullet list

**Comment by tballmsft** [comment]
agreed. @sehodges ???

**Comment by sehodges** [comment]
sorry, what do you want me to change it to?

**Comment by tballmsft** [comment]
fixed: https://github.com/microsoft/jacdac-docs/commit/6f1c2c24032a75b18e2caebdf4927b2b04a6dd50
