### ISSUE TITLE
RP2040 USB prototype as "dongle"

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1162]
As previously discussed, this prototype functions as "jacdaptor", more than a programmable brain, so would be good to classify it. It should really show up in the list of Jacdaptors.

**Comment by pelikhan** [comment]
Add “adapter” as tag in device json
________________________________

**Comment by pelikhan** [comment]
Still we should avoid showing modules with the wrong form factor  (same for star fighter)

**Comment by tballmsft** [comment]
Brains and Jacdaptors are not modules, so I think we should show them. EC30 is not an absolute requirement. I think it's important to show breadth, and not be bound totally by EC30. Let's chat more on Friday.

**Comment by pelikhan** [comment]
It's tagged as brain currently so misleading

**Comment by tballmsft** [comment]
Yes, it is not a brain. I thought you were going tag it as "dongle" and we would include dongle as a type of "jacdaptor".

**Comment by tballmsft** [comment]
Discussed with Michal. See https://github.com/microsoft/jacdac/issues/1165

**Comment by pelikhan** [comment]
so you want a "dongle" tag?

**Comment by pelikhan** [comment]
unclear what's the decision here

**Comment by tballmsft** [comment]
add "adapter" tag

**Comment by pelikhan** [comment]
JacdapterImageList is not used anymore so it won't have much effect.
