### ISSUE TITLE
how to add a new service

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1167]
Need a page describing how to create new service <foo>

# Design service

0. make sure there's no existing service that meets your needs.
1. design/spec service. is this a top-level new service or a mixin service for an existing service?
2. create service specification (jacdac/services/<foo>.md)
    - tool for this

# Implement service 

1. start with a copy of existing service  
6. run tool to generate header file <foo>.h
7. create new file <foo>.c in microsoft/jacdac-c/services

**Comment by tballmsft** [comment]
@mmoskal - can you check the above steps?

**Comment by mmoskal** [comment]
Maybe split into creating a service and then adding impl?

**Comment by pelikhan** [comment]
We have a service editor that generates a PR, but I can see how this does not fit into the cycle of someone writing a new c server.

Might be confusing.

**Comment by tballmsft** [comment]
Please see https://microsoft.github.io/jacdac-docs/ddk/services/ and edit.

**Comment by tballmsft** [comment]
@mmoskal ?

**Comment by mmoskal** [comment]
Edited the text a little

added issue https://github.com/microsoft/jacdac/issues/1173
