### ISSUE TITLE
Fix on JSOM Node.js example

### ISSUE THREAD

**Issue by alankrantas** [microsoft/jacdac#1168]
[**Describe the bug**
The ```createNodeUSBOptions()``` in JSOM Node.js requires a WebUSB constructor from the package ```usb``` ,

https://microsoft.github.io/jacdac-docs/clients/javascript/jdom/

**Additional context**
My fix:

First the user has to install ```usb```

```
npm install --save usb
```

Then

```javascript
import { createUSBBus, createNodeUSBOptions, ... } from "jacdac-ts"
import { WebUSB } from "usb";  // fix

const options = createNodeUSBOptions(WebUSB);  // fix
const bus = createUSBBus(options);
```

**Comment by pelikhan** [comment]
Thanks! Fix applied!
