### ISSUE TITLE
Simulator not showing in chrome - seems to work in Edge Browser

### ISSUE THREAD

**Issue by dsssssssss9** [microsoft/jacdac#1170]
**Describe the bug**
When i create or load  a Makecode program including Jacdac extension the Simulator does not appear when Using Chrome Browser

**To Reproduce**
1. In Chrome Browser goto www,https://makecode.microbit.org/
2. Create new program + add jacdac extension
3.Simulator does not appear , just a blank screen areaa where it should be 
4. 
![Chrome Does not work](https://user-images.githubusercontent.com/30810847/175788569-de5809d9-3fe6-4481-bf40-73c9b060f548.png)

**Expected behavior**
![Edge Works](https://user-images.githubusercontent.com/30810847/175788576-d112a412-dc9c-4798-9763-18608a0d5f29.png)

**Desktop (please complete the following information):**
 - Windows 10 Home
 - Chrome
 - 103.0.5060

**Additional context**

**Comment by pelikhan** [comment]
What happens if you go to https://microsoft.GitHub.io/dashboard?

**Comment by pelikhan** [comment]
Could you also collect the Javascript console output of https://microsoft.github.io/jacdac-docs/tools/makecode-sim/?dbg=1 ?

**Comment by dsssssssss9** [comment]
> What happens if you go to https://microsoft.GitHub.io/jacdac-docs/dashboard?

If i go to the limkwithout Micro:Bit connected i get ....

![jacdac peli question 1a](https://user-images.githubusercontent.com/30810847/176022571-a96ce40a-87ad-44c6-acd0-743ba76a8a8d.png)


When I connect Micro:Bit i get,,,,,,,
![jacdac peli question 1b](https://user-images.githubusercontent.com/30810847/176022665-c61e37dd-61ed-444e-af39-f8b24e8d1ec3.png)

**Comment by dsssssssss9** [comment]
> Could you also collect the Javascript console output

![jacdac peli question 2](https://user-images.githubusercontent.com/30810847/176023137-ef5880bc-3d3a-4c80-ad95-f766bf1ca549.png)

**Comment by dsssssssss9** [comment]
Also on a second machine running same version of chrome as the 1st
When i try to connect a Micro:Bit i get the following error....

![Jacdac peli question extra info 1](https://user-images.githubusercontent.com/30810847/176023816-d5250e45-3c6b-467c-9d3c-16dc4741463f.png)

If i connecect the same Micro:Bit to the same cpmptuer under chropme in MakeCode i have no problems

On both computers i get no problems with other browsers ( Brave , Firefox etc etc ) so i am thinking this is a chrome problem?

 A frine of mine who has a old Chromebook has reported that both MakeCode & Jacdac  Dashboard work.

**Comment by pelikhan** [comment]
If you could click on the "console", there might be information there about what is failing.

**Comment by pelikhan** [comment]
It seems that the service worker gets corrupted somehow.

**Comment by dsssssssss9** [comment]
> It seems that the service worker gets corrupted somehow.

Is this something that can be fixed ?

Can I provide any further information to help with this ?

**Comment by pelikhan** [comment]
In developer tools, open Application and unregister the microsoft.github.io/jacdac-docs service worker
![image](https://user-images.githubusercontent.com/4175913/177007294-b196f8c0-fda0-4002-a6bf-ce718a562d59.png)

**Comment by dsssssssss9** [comment]
So sorry for the delay - real life got in the way!

May have found a sort of solution ....

Instead of using Chrome i have used Brave browser that seems to work well - the simulator appears in the MakeCode Editor & functions as expected

for the 2nd problem - connecting to Dashboard gives an error - this seems to be a browser  permissions problem - if i reset the Site permissions for the Dashboard web page in the browser  all seems to function  

Still no luck with Chrome or Edge browsers though!

**Comment by pelikhan** [comment]
Need to get to the bottom of this...

**Comment by tballmsft** [comment]
can't repro - clear cache as workaround
