### ISSUE TITLE
picture of micro:bit plugged into our jacdaptor

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1172]
- [  ] microbit + our jacdaptor
- [  ] large RPi + JacHat.

**Comment by pelikhan** [comment]
Waiting for new JacHAT for large pi picture and from KittenBot for updated picture.

**Comment by sehodges** [comment]
what exactly is the request on this one?

**Comment by pelikhan** [comment]
A picture of the micro:bit + jacdactor in the same style as other kittenbot picture. We can also just close this and ignore.
