### ISSUE TITLE
jacdac dashboard on pi doesn't handle the Pi and the STM on the HAT correctly

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1176]
my button works great in the R Pi dashboard, but I see two other devices which are a bit confusing. one is the Pi I guess, but no name or anything and a progress wheel that spins forever. the other is the STM on the HAT I think - so that's a bit like seeing the micro:bit on the PC dashboard - but it doesn't have a friendly appearance either and it says 'led' although there is no way to control the LED?

**Comment by pelikhan** [comment]
Please click on the "save trace" link at the bottom of the page and attach the trace.jd file. I don't know what you have connected.

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/211105814-2175236f-034c-491f-a2e7-aa5c12ff553a.png)

**Comment by tballmsft** [comment]
out of scope
