### ISSUE TITLE
the 'connect' process for R Pi is inconsistent with connecting to micro:bit or USB dongle on a PC

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1177]
![image](https://user-images.githubusercontent.com/12393831/176475016-9a004a32-f1c4-47ca-be6a-6f68f5b70664.png)
when I press 'connect' I see the optoins for (web) USB  and (web) serial, but I don't want either of these. in fact, if I'm running the right stuff in the background I don't need to manually connect at all. this inconsistent experience is going to confuse people. can we at least remove the 'connect' optoins when it's already connected? ideally 'SPI' is a third option in the 'connect' dialog.

**Comment by pelikhan** [comment]
the connect is useful in codespaces, but yes it's a bit confusing right now

**Comment by tballmsft** [comment]
out of scope
