### ISSUE TITLE
change colour of simulated 7-segment LEDs

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1179]
it's hard to see the simulated 7 seg displays, I suspect even harder for certain visual impairments:
![image](https://user-images.githubusercontent.com/12393831/176500644-8e1f3eed-71a9-4b72-bc15-3d649661e56b.png)
the above looks like 8EEE for example. 

I know that real displays are like this a bit too, but let's not replicate that (and make it worse). I'd suggest red for when they light up and dark grey for when they are off, with an even darker grey background. so when they are off one can just about make out the segments (dark grey against even darker grey) but when the light up they hopefully stand out. maybe the yellow we already use is even better than red?

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/183725079-8ac0a1f6-c452-4bca-8ccc-27373b0c1fc2.png)
