### ISSUE TITLE
dashboard can't show the LightSensor and MagnetSensor picture

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1195]
![image](https://user-images.githubusercontent.com/3880290/182330130-77f7a4d3-1aab-4bc0-873c-cee471aa846f.png)

**Comment by smfox10** [comment]
![image](https://user-images.githubusercontent.com/3880290/182342888-88bd81e0-0f9e-407f-8fad-a107ce9e6646.png)

the same as in Makecode

**Comment by pelikhan** [comment]
Indeed the product identifier from the specification (https://github.com/microsoft/jacdac/blob/main/devices/kittenbot/lightsensorv10.json#L11) don't seem to match the ones reported by the devices

**Comment by pelikhan** [comment]
fixed by https://github.com/microsoft/jacdac/commit/be2fe8ed869707fdc35c3b4d31dbbf5bd6d70938
