### ISSUE TITLE
dashboard RGBRing simulator direction

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1196]
![image](https://user-images.githubusercontent.com/3880290/182339542-dfecfd21-2603-49e9-9e5b-a9bdc8b3beb2.png)

According to Jacdac module standards, the physical object and emulator do not match

![jacdac-rgbLedRing-brd](https://user-images.githubusercontent.com/3880290/182339799-37c2dba2-3054-4f60-b6f8-87ca1f6ef997.svg)

**Comment by mmoskal** [comment]
looks like it's documented here https://microsoft.github.io/jacdac-docs/ddk/design/ec30/#component-numbering-and-orientation
