### ISSUE TITLE
is streaming should automatically stop if no one is listening

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#12]
It's easy to start streaming but stopping is much harder. When there are multiple listeners, a listener should not stop the streaming otherwise the other will loose data ... but ... that means never stopping the streaming once started. Or the listener might just go away without stopping streaming.

IMO, a device should stop streaming if it has not received a streaming command in x seconds.

**Comment by mmoskal** [comment]
@jamesadevine can your paduk do it? I guess reserve a byte for is_streaming, set it to 255 when set to true and then decrement until reaches zero?

**Comment by jamesadevine** [comment]
yup, it can do that!
