### ISSUE TITLE
SEO information is not accurate for Jacdac homepage

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#1211]
**Describe the bug**
In a bing search for Jacdac, the homepage has the title "Jacdac logo - GitHub Pages":

<img width="475" alt="image" src="https://user-images.githubusercontent.com/4742697/189086470-bcdf4127-8fee-4305-be89-d7870cfe34c9.png">

**To Reproduce**
Search bing for jacdac, e.g.:

https://www.bing.com/search?q=jacdac&qs=n&form=QBRE&msbsrank=1_9_File_2&sp=-1&pq=jacdac

**Expected behavior**
Title the page "Jacdac"

**Comment by pelikhan** [comment]
You're right, looks like all titles are gone.

**Comment by pelikhan** [comment]
I have a half fix for this, still figuring out the MDX thingy
