### ISSUE TITLE
It will be nice to have rotary event or variable shows the direction in which rotary encoder is rotated. 

### ISSUE THREAD

**Issue by siby-george** [microsoft/jacdac#1213]
when working with rotary encode there is need to know direct in which we are rotating the shaft.

It will be good to have a variable which shows the direction rather that have a state variable and compare the value to do that in make code.

Having this as part of the rotary encoder will simplify the sketch.

**Comment by pelikhan** [comment]
@siby-george is this for makecode?

**Comment by siby-george** [comment]
That is right for makecode.
