### ISSUE TITLE
update web UI for haptic module

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1220]
A PADAUK-based haptic module can only play up to five 'symbols'; if there are more then currently nothing happens. 

We could change the default pattern in the web UI to contain only 5? Or better yet we could Have a way to learn from the module how many it supports.

**Comment by pelikhan** [comment]
I've shortened the vibration pattern to '.-.' . @mmoskal what about adding a const optional register with the maximum size supported?

**Comment by pelikhan** [comment]
Added support for max vibrations register and support in UI
