### ISSUE TITLE
when registering a new device in the catalog, the import function doesn't seem to work right

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1232]
Starting from the [device registration page](https://microsoft.github.io/jacdac-docs/tools/device-registration/), I click on 'import'. But for the modules I tried (e.g. RP2040 brain 124 V1.3 running Jacscript firmware, and the triple sliders) the text that appears in the device name field seems to miss the first character and the text that goes into the company field is also filled in as the device name. 

Here are some screenshots:

![image](https://user-images.githubusercontent.com/12393831/210541013-243adecb-ebc7-4eb1-be33-8fc3aeb65939.png)

![image](https://user-images.githubusercontent.com/12393831/210541081-35bd6c69-4dca-41dc-a606-ac77451ec9df.png)

**Comment by pelikhan** [comment]
It is a best effort to parse the company name from the description. The user needs to patch.

**Comment by sehodges** [comment]
But there's just an off-by-one error? It's probably better to have no auto-suggest than something that's wrong every time?

**Comment by sehodges** [comment]
Sorry, to be clear: website suggests R2040 instead or RP2040 and M-slider-3 instead of JM-slider-3. The auto-suggest for the company name gets the device name correct, can we just use the code from there to replace what you currently have for the device name? 

If you want to delete the auto-suggest for the company name (since the current heuristic seems to fail and get the device name) that's fine with me.

**Comment by tballmsft** [comment]
Seems like a bug here.

**Comment by pelikhan** [comment]
heuristic removed
