### ISSUE TITLE
base and sensor classes show as experimental

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1243]
These two services show as experimental on the website:
![image](https://user-images.githubusercontent.com/12393831/213772058-16dd962b-1e4e-4bf0-b48d-c55651833953.png)

They don't seem to have a status tag, so I'm not sure where the 'experimental' tag comes from? Maybe it's triggered by the lack of a status tag.

The role manager also shows as experimental in the same way. Not sure if that's stable?

**Comment by pelikhan** [comment]
fixed.
