### ISSUE TITLE
makecode and jacdac not working together

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1244]
Repro
1. load jacdac extension
2. connect micro:bit and download empty program
3. See the following in log:

```
pxtapp.js:1 
        
 Failed to execute 'postMessage' on 'DOMWindow': 
The target origin provided ('https://microsoft.github.io') 
does not match the recipient window's origin 
('https://makecode.microbit.org').
```

**Comment by tballmsft** [comment]
After the above, then keep getting these messages:

```

Collect roles failed
eventsource.ts:199 
        
       JacdacError: no ACK for MS18/3[3]: 0x83 sz=12: 6abc472303208e92aa010000
    at Object.errCb (device.ts:1058:31)
    at resend (device.ts:1006:25)
```

**Comment by pelikhan** [comment]
Does this happen when you reload the simulator?

**Comment by tballmsft** [comment]
yes

**Comment by pelikhan** [comment]
Does Jacdac work when using https://microsoft.github.io/jacdac-docs/dashboard/ ?

**Comment by tballmsft** [comment]
Yes. This is the program: https://makecode.microbit.org/_axXJKYKMHF53

**Comment by tballmsft** [comment]
This program contains jacdac.start(), which fixes the problem.

**Comment by tballmsft** [comment]
We should probably add a block for starting Jacdac to help bootstrap things. The Jacdac blocks don't have any meaningful event for bootstrapping.

**Comment by tballmsft** [comment]
OK. will leave this issue open.
