### ISSUE TITLE
jacdac Servo in Makecode need two  channel

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1247]
hi guys,we are preparing BETT project.We made a carton robot that needs two servos to drive.

But we found there is no channel(S0,S1) can be choice in makecode.
![image](https://user-images.githubusercontent.com/3880290/217413839-02f9f2e6-6806-4bb7-a15e-e229251732b1.png)

**Comment by pelikhan** [comment]
Fixed, you'll find 4 servos and 4 buttons.

**Comment by smfox10** [comment]
Thx，it works~^^
