### ISSUE TITLE
jacdac Servo angle（90-180）can't work in Makecode 

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1250]
if I set angle 180°，servo actually reaches 90°
![image](https://user-images.githubusercontent.com/3880290/217780570-1b922127-7e5d-4a26-9f0e-47f27cf9bbea.png)

**Comment by pelikhan** [comment]
Could you share your program?

**Comment by smfox10** [comment]
https://makecode.microbit.org/_WpA0YkagvfXW

**Comment by smfox10** [comment]
Already solved.Thx peli.my firmware problem. Servo angle change to 0-180 in the firmware
