### ISSUE TITLE
jacdac Servo initial angle bug

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1253]
hey，guys，we are debugging the servo in makecode.
We found a bug.When I set the angle for servo1 and servo2(Serov1->60,Serovo->46),I downloaded the hex.
The Servo1 and Servo2 turns to 0 degrees（did not meet my expectations），when I press buttonA，it works
![image](https://user-images.githubusercontent.com/3880290/218365830-44c511f5-65f3-4ca2-86c8-379dc466dc35.png)

**Comment by pelikhan** [comment]
Could you share your program? Is the issue on hardware or in the simulator?

**Comment by smfox10** [comment]
https://makecode.microbit.org/_PExPhJDV8Me3

hardware issue .the simulator works fine

**Comment by pelikhan** [comment]
@mmoskal do you have this module?

**Comment by smfox10** [comment]
Thx peli，Already works fine
