### ISSUE TITLE
z-index on website broken on jacdac-docs

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#1254]
See eg device registration page:

<img width="529" alt="Screen Shot 2023-02-14 at 3 19 42 PM" src="https://user-images.githubusercontent.com/10673976/218885138-4b7781c5-45d5-4be6-8f33-e32faf172691.png">

Also observed when configuring WiFi.

**Comment by pelikhan** [comment]
fixed with https://github.com/microsoft/jacdac-docs/pull/255
