### ISSUE TITLE
HID Keyboard - space not working

### ISSUE THREAD

**Issue by minki710** [microsoft/jacdac#1258]
Cannot set the HID Keyboard to insert a space. when coded, nothing happens. 

<img width="621" alt="image" src="https://user-images.githubusercontent.com/41535026/222881449-e658eadf-f391-4db9-8b31-8a00f184c9f4.png">

**Comment by pelikhan** [comment]
Can you describe your hardware setup?

**Comment by minki710** [comment]
we are using the Jacdac HID Brain with the STM32F chip, and then a standard Jacdac button by Kittenbot. 

![Jacdac_HID_button](https://user-images.githubusercontent.com/41535026/223303470-9786b843-78fb-487b-b96d-8566c33447d6.jpg)
