### ISSUE TITLE
HID Keyboard - cannot hold control or shift key down

### ISSUE THREAD

**Issue by minki710** [microsoft/jacdac#1259]
I am trying to something like sticky keys, to be able to use a button to hold down shift, and then allow using the mouse to select multiple objects, such as cells in Excel or multiple images in Powerpoint. 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/41535026/222883588-5e6f0a45-f8ff-495f-9b80-660b3571e690.png">

**Comment by pelikhan** [comment]
Can you describe your hardware setup?

**Comment by pelikhan** [comment]
Try pxt-jacdac v1.8.41

**Comment by minki710** [comment]
it works!!! thank you!
