### ISSUE TITLE
Servo bug in dashboard

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1260]
https://microsoft.github.io/jacdac-docs/dashboard/

there is a bug in slider of servo 1 .servo 2 is ok
![servo1 bug](https://user-images.githubusercontent.com/3880290/223999001-27c8706a-1d6c-43f3-a96d-62d7d5011003.gif)

**Comment by pelikhan** [comment]
It looks like the first servo is bound to a role. Is there a makecode program that keeps the angle at 0?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: CCFIVE ***@***.***>
Sent: Thursday, March 9, 2023 2:37 AM
To: microsoft/jacdac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/jacdac] Servo bug in dashboard (Issue #1260)


https://microsoft.github.io/jacdac-docs/dashboard/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2Fjacdac-docs%2Fdashboard%2F&data=05%7C01%7Cjhalleux%40microsoft.com%7Cc71e1fc7384446f1b39108db208a58b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638139550783941809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D8KGI8KIF7zHM40fjfWJr%2FZod2P%2FE9%2FKIdipZM6oCZw%3D&reserved=0>

there is a bug in slider of servo 1 .servo 2 is ok
[servo1 bug]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3880290%2F223999001-27c8706a-1d6c-43f3-a96d-62d7d5011003.gif&data=05%7C01%7Cjhalleux%40microsoft.com%7Cc71e1fc7384446f1b39108db208a58b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638139550783941809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ANRgd0xEeV2AaxC8a4SMVZriQRJlEJ%2F8gtJJXu%2Bw0TY%3D&reserved=0>

**Comment by smfox10** [comment]
servo 1 works fine in makecode
![servo1 work fine](https://user-images.githubusercontent.com/3880290/224199330-30d0f99f-0193-48e2-b28c-a4f8afa433b0.gif)
