### ISSUE TITLE
Some suggestions on servo in dashboard

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1261]
1、I recommend that the slide does not fold, each time you need to open, very tedious
![image](https://user-images.githubusercontent.com/3880290/223999707-550bf3f2-3ed3-4a19-ab35-1eb7a970b426.png)

2、The angle rotation range is now -90-90. This is very different from what we are used to, whether it is Arduino or microbit, the servo angle is always 0-180

**Comment by pelikhan** [comment]
(1) fixeds
(2) the ui uses the min/max angles register, what do you have in your server?
![image](https://user-images.githubusercontent.com/4175913/224084764-f30d656c-0b71-4f31-b02b-5e3c4703d19e.png)

**Comment by smfox10** [comment]
Thx peil.I know why the servo does not work at 90-180 degrees.The actual operating range of my servo is -90-90 degrees.I will ask Riven to change the server

**Comment by smfox10** [comment]
![image](https://user-images.githubusercontent.com/3880290/224201802-8ad17cf4-6dee-41a0-9fac-2d9bb2ab7161.png)
