### ISSUE TITLE
makecode ‘ADD BLOCKS’ unavailable

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1285]
https://makecode.microbit.org/beta#editor

When I refreshed again, the button worked again

![image](https://github.com/microsoft/jacdac/assets/3880290/f5fe5d33-7483-4437-ad56-46447586011a)

[**https://makecode.microbit.org/S14794-75698-44410-98101**](https://makecode.microbit.org/S14794-75698-44410-98101)

**Comment by pelikhan** [comment]
what do you do to get into this mode?

**Comment by smfox10** [comment]
1、download a jacdac program, such as the use of ultrasonic module program
2、after unplugging the jacdac ultrasonic, and then insert other modules, such as temperature and humidity module

**Comment by pelikhan** [comment]
fixed in https://github.com/microsoft/jacdac-docs/commit/37c1727ffb1aa3bdf519542f9e516d9e1c9b26b8
