### ISSUE TITLE
jacdac-Temp&Hum reading values problem 

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1286]
There is a problem with the first download of the module reading values

Screen display 'undefined' (Same problem with reading both temperature and humidity)

https://makecode.microbit.org/S14794-75698-44410-98101

https://github.com/microsoft/jacdac/assets/3880290/0029e42f-a1e8-4c74-92fe-ed906e9b8391

**Comment by pelikhan** [comment]
Try again with 1.9.7

**Comment by smfox10** [comment]
Thanks, it works fine now!
