### ISSUE TITLE
jacdac-Temp&Hum problem blocks

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1287]
![image](https://github.com/microsoft/jacdac/assets/3880290/89d5bc99-a712-4b85-a29e-381ce15b89fb)

Problem blocks

https://makecode.microbit.org/S14794-75698-44410-98101

**Comment by pelikhan** [comment]
fixed
<img width="466" alt="image" src="https://github.com/microsoft/jacdac/assets/4175913/29f71b59-c361-49a3-890d-8b9d39d4fae7">
