### ISSUE TITLE
jacdac-HapticOutput add blocks bug

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1288]
When I plugged in the HapticOutput module and clicked on ADD BLOCKS, no Blocks appeared on the right side

https://makecode.microbit.org/_1FtRofCwt2FX
![image](https://github.com/microsoft/jacdac/assets/3880290/5f4dc1d9-406f-45be-af51-d828fe9d0602)

https://github.com/microsoft/jacdac/assets/3880290/40d8df15-5d86-4d45-b5f6-8bc4eccb4c53

**Comment by pelikhan** [comment]
fixed in 1.9.8. also added `vibratePattern`
