### ISSUE TITLE
jacdac-ledstrip number of pixels and brightness

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1290]
https://makecode.microbit.org/_2rtFM0YJ28Yw

first time to show number of pixels or brightness，it gets 'undefined' and 'NaN'

![image](https://github.com/microsoft/jacdac/assets/3880290/118ce0da-985a-4004-b355-908b951885b5)

**Comment by pelikhan** [comment]
fixed in 1.9.11
