### ISSUE TITLE
jacdac-power 

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1292]
1、It should contain power1 and power2
![image](https://github.com/microsoft/jacdac/assets/3880290/b73114d9-5530-4f47-ba7a-a9d27b9b6621)

2、I set power1 allowed to true，but It turns off？

3、set power1 allowed to false，no response（They all work fine in the dashboard）

https://makecode.microbit.org/_PaJAm0AfFhpd

![image](https://github.com/microsoft/jacdac/assets/3880290/7390a374-d213-44f1-8b6e-09dc24ae5148)

**Comment by pelikhan** [comment]
Do you really want kids to control the power service using blocks?

**Comment by smfox10** [comment]
'I think we should simply not have blocks for the power module.'  I agree with you.

**Comment by pelikhan** [comment]
removed.
