### ISSUE TITLE
JD Brain RP2040 HID in Makecode

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1314]
I would like to add one more programming block for sending words from the keyboard.This would make programming less difficult

![image](https://github.com/microsoft/jacdac/assets/3880290/1af214c5-d961-4f53-905b-17c09a9d8529)

![image](https://github.com/microsoft/jacdac/assets/3880290/d1fd78fa-4eb9-4e39-8e51-ede33a61f739)

**Comment by pelikhan** [comment]
Fixed in v1.9.13

**Comment by smfox10** [comment]
Need a little delay between letters?
I see the correct result in the left window.
![image](https://github.com/microsoft/jacdac/assets/3880290/d0b9a42d-0bd0-4b39-801d-7be2f43fa474)

But my keyboard only triggers K
![image](https://github.com/microsoft/jacdac/assets/3880290/71af5017-2c39-43f6-a436-0157f8e6f130)
