### ISSUE TITLE
JD Brain RP2040 HID Consecutive letters

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1315]
When my keyboard sends a message containing consecutive letters, such as 't', sometimes it only prints out a

https://makecode.microbit.org/_LxYYX3Y6uegH

![image](https://github.com/microsoft/jacdac/assets/3880290/31655da9-a381-4db5-a9a9-e5c3fcd9c8ea)

**Comment by pelikhan** [comment]
Fixed in v1.9.13

**Comment by smfox10** [comment]
√
