### ISSUE TITLE
rotary control doesn't work with jacdac/micro:bit jukebox

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1317]
when I download the latest jacdac jukebox for micro:bit it seems to work fine apart from with rotary controls. if you restart the mirco:bit then plug in a rotary control the micro:bit crashes with error 989: 
https://github.com/microsoft/jacdac/assets/12393831/28e36935-bbb9-4b26-9916-1d2885561d63

if the rotary control is already plugged in when the micro:bit restarts the device is recognised (e.g. a '1' appears on the micro:bit display) and I don't see the crashes and the button click of the rotary control works. but rotating the control doesn't work - nothing happens on the micro:bit:
https://github.com/microsoft/jacdac/assets/12393831/fa1b2b3b-131e-40f0-a3e2-53a6e0d5a7e6

when I use an old microbit-jukebox.hex file (which I'd downloaded a year ago) everything seems to be fine.

**Comment by pelikhan** [comment]
Fixed. Please try again with v1.9.14
