### ISSUE TITLE
led strip(RGB Strip) can't be turned off in Makecode

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1319]
No response occurs when pressing both buttons A and B

https://makecode.microbit.org/_VuJHtFacrbWW
![image](https://github.com/microsoft/jacdac/assets/3880290/e16313a1-a227-4274-8ce4-a24d92565a47)

Also I can't turn off the led strip by setting the brightness.
https://makecode.microbit.org/_ViqWCcViWMi5
![image](https://github.com/microsoft/jacdac/assets/3880290/dd286df5-a30e-4989-b128-84dd0851e40f)

https://github.com/microsoft/jacdac/assets/3880290/b8f21961-23dc-46e3-af2f-fa5598cea638

**Comment by pelikhan** [comment]
The rendering update was skipped when setting all pixels to 0... In which case MakeCode actually turns off the power on the strip.

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac-ts/compare/d5dc3fb56a443226222f3dea9af3c1fcc5363753...506c1e39c52b7204c87cfa861c7e6012a43e9fa3#diff-292eb7d73cbeac6600b5f2a4688e0d3b3a32c1e6ce767bff7f52d1ed20913a97

**Comment by pelikhan** [comment]
Better brightness support https://github.com/microsoft/jacdac-docs/commit/2d8fd72ed159b4d26023c352e76764636b08c875

**Comment by smfox10** [comment]
@xmeow

**Comment by smfox10** [comment]
https://makecode.microbit.org/_41gU7V35V1gs

**Comment by smfox10** [comment]
@xmeow 

https://github.com/microsoft/jacdac/assets/3880290/38cecd2e-ecff-4649-92c5-8b61e64932d9

**Comment by pelikhan** [comment]
Can you turn it off through the dashboard?
