### ISSUE TITLE
Ultrasonic Sensorv1.0 pic and name incorrect in the simulator

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1326]
last week I just update the image of Ultrasonic Sensor and I haven't changed the config file.
![image](https://github.com/microsoft/jacdac/assets/3880290/5c06de25-7aef-482b-8ff7-de061fa92787)

**Comment by pelikhan** [comment]
what product identifier do you have in the tools? 
![image](https://github.com/microsoft/jacdac/assets/4175913/74a0dec4-5642-4901-88e2-af04b7acdab0)

**Comment by pelikhan** [comment]
This must be the firmware returning the wrong product id since it is registered in the catalog.

**Comment by smfox10** [comment]
Thx~peli
I'll figure out why. My rp2040's ID was conflicting with the ultrasonic module's. I have made the modification.
Both devices are randomly generated through 'device registration' and normally they shouldn't duplicate!

**Comment by pelikhan** [comment]
I like the new name nanoscript better!
