### ISSUE TITLE
The servo is set to 180 degrees, but it comes up 135 degrees

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#1327]
I have the servo servo angle set to 100% (180°) on my program, but when running in the real thing, the simulator shows 135° (and the real thing is really only 135° as well).When I press the button again, the angle goes back to normal
![servo](https://github.com/microsoft/jacdac/assets/3880290/db5b8e69-c6a0-4f45-9bd5-8674d86d7d0d)

https://makecode.microbit.org/_e8fRPs4atah4

**Comment by pelikhan** [comment]
is this a firmware issue? The simulator shows 180

**Comment by pelikhan** [comment]
what is the correct procedure to repro this issue?

**Comment by pelikhan** [comment]
please attach a jacdac trace

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-jacdac/pull/101

**Comment by pelikhan** [comment]
Fix deployed, please test.

**Comment by smfox10** [comment]
Yes，It's fixed. Thank you.
