### ISSUE TITLE
Some links broken

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1334]
on the jacdac docs page https://microsoft.github.io/jacdac-docs/reference/protocol/#network-interface-layer some of the links are broken. examples include:
- https://microsoft.github.io/jacdac-docs/reference/protocol/service-specification/ (text is [custom markdown language])
- https://microsoft.github.io/jacdac-docs/reference/protocol/single-wire-serial/ (text is [Single Wire Serial])

neither of these should have /protocol/ in the path (I think?). since they are auto-generated maybe there are broken links elsewhere too?

**Comment by pelikhan** [comment]
Maybe keep reporting.
