### ISSUE TITLE
3 dotmatrix program isn't working well with hardware

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#1336]
Perhaps related to: https://github.com/microsoft/jacdac/issues/1335

https://makecode.microbit.org/_8Ut0jYYJxbHT

**Comment by tballmsft** [comment]
Problems noted:
1. packets are lost, so sometimes some LEDs toggled, not others
2.

**Comment by tballmsft** [comment]
[trace.jd.txt](https://github.com/microsoft/jacdac/files/13034403/trace.jd.txt)

**Comment by pelikhan** [comment]
what hardware is that?

**Comment by tballmsft** [comment]
https://microsoft.github.io/jacdac-docs/devices/microsoft-research/jmmatrix87v40/

**Comment by pelikhan** [comment]
@tballmsft please retest.
