### ISSUE TITLE
Missing german translation in Jacdac for Gamepad

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/jacdac#1380]
**Describe the bug**

working on a softwarejacdac for a new gamepad I discovered that at jacdac for gamepads the german translation is still missing.

![Image](https://github.com/user-attachments/assets/d21cc462-8ef8-4d0c-ae6f-d90ecd1d8f86)

perhaps you can fix it

**Comment by tballmsft** [comment]
we accept PRs

**Comment by pelikhan** [comment]
@tballmsft I can show how to run the AI scripts to create translations

**Comment by MKleinSB** [comment]
@pelikhan That would be great! The other AI translations are very good!

**Comment by pelikhan** [comment]
Please review the translations at https://github.com/microsoft/pxt-jacdac/pull/112/files . What other libs do you want translated?

**Comment by MKleinSB** [comment]
Thanks. That´s all for now.
