### ISSUE TITLE
Errors in sparkfun gamer:bit example, error using 'on (Gamepad) buttons changed'

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/jacdac#1381]
pins.pushButton(DigitalPin.P0);
seemes not to pullup the pin in Jacdac. In the normal extension it works correctly. So you have pullup all used pins manually.

![Image](https://github.com/user-attachments/assets/1dc08085-207e-4e04-b507-58e64133262e)

second error:
on buttons changed seemes not to work. The digital twin shows button up is pressed (simply connect Pin P0 to ground) , but there is no event triggered.
Program including extension: https://makecode.microbit.org/_EFAV9dJhcMJC

![Image](https://github.com/user-attachments/assets/100176fe-163e-410d-afeb-e247811025f6)

**Comment by tballmsft** [comment]
This extension was done by @pelikhan - https://github.com/pelikhan/pxt-gamer-bit/tree/master/jacdac. But you are not using it. Your pxt.json has:
```
        "jacdac": "github:microsoft/pxt-jacdac#v1.9.28",
        "jacdac-gamepad": "github:microsoft/pxt-jacdac/gamepad#v1.9.28"
```
That is, there is no code in your project bridging jacdac to the device.
