### ISSUE TITLE
jacdac-ts: support new protocol features: qos, version, events

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#143]
* [x] QoS counter sending
* [x] QoS counter usage
* [x] version bit
* [x] triplicate event sending
* [x] triplicate event reception

**Comment by mmoskal** [comment]
events implemented in https://github.com/microsoft/pxt-jacdac/pull/28

**Comment by pelikhan** [comment]
Is QoS going to be a register i can query from jacdac-ts? Since only a physical device can collect those, I'll need to poke the Makecode device to give me that info.

**Comment by mmoskal** [comment]
You can actually check the counter in announce packet (supported by latest JM firmware) that lists the number of packets sent and see if you got all of them. 

What you cannot do from website is the flood ping (ie if you enable it, the webusb probably won't keep up)

**Comment by mmoskal** [comment]
This was for jd-ts, I think it's now all done
