### ISSUE TITLE
Auto load of JD extension when JD module plugged in

### ISSUE THREAD

**Issue by tracyttran** [microsoft/jacdac#146]
- [x] cleanup editor extensions in pxt https://github.com/microsoft/pxt/pull/7785
- [x] create editor extension for jacdac
- [x] update pxt to register known extensions for message types
- [x] the simulator must know which extension is loaded and if need send a message to the editor to add additional messages
- [ ] enable editor extensions by default in micro:bit
- [ ] enable editor extension by default in arcade
-

**Comment by tracyttran** [comment]
Peli, do you think this is possible? Or does the user _have_ to add the JD extension and we cannot prompt them?

**Comment by pelikhan** [comment]
Auto loading extensions will lead to a bad experience. Loading an extension modifiés the project. so not happening automatically.

**Comment by pelikhan** [comment]
This is mostly done.
