### ISSUE TITLE
Mark JD extension as having simulator support

### ISSUE THREAD

**Issue by tracyttran** [microsoft/jacdac#149]
- [ ] merge this https://github.com/microsoft/pxt/pull/7785
- [ ] add extension to target config
- [ ] enable editor extensions in microbit pxtarget

**Comment by tracyttran** [comment]
Peli, do we need some kind of new badge/icon for the extension, or do you think we can just say it in the text, title, or extension image?

**Comment by pelikhan** [comment]
We can show an image per extension, that’s it.

________________________________
