### ISSUE TITLE
Arcade shield for microbit repo logistics

### ISSUE THREAD

**Issue by tracyttran** [microsoft/jacdac#157]
Release of Microsoft Code under MIT License
Take the following steps to release your project.

Place the Following in the Project's Root Directory:

- [ ] LICENSE. A copy of the MIT license text in a file called "LICENSE.TXT." Include your project name above the copyright statement.

- [ ] README. A "README.md" file that must include a link to the Microsoft Open Source Code of Conduct, a trademark notice, and security reporting instructions. Consider including additional details about the project in the README.

- [ ] CONTRIBUTING. A CONTRIBUTING.md file that contains instructions how to contribute to the project. Here is the minimum information required. All contributions must be done subject to Microsoft's Contributor License Agreement ("CLA"). Releases on GitHub have CLA's enabled by default. If your project is not on GitHub, ensure that contributors first sign our CLA.

- [ ] File Header. Include the following header in each source file.

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

**Comment by mmoskal** [comment]
There are two repos:

* https://github.com/microsoft/pxt-arcade-hardware-designs
* https://github.com/microsoft/pxt-arcade-smart-shield

Both now fulfill the conditions.

Reopen if needed.
