### ISSUE TITLE
Create low power JACDAPter

### ISSUE THREAD

**Issue by tracyttran** [microsoft/jacdac#159]
- [x] Create schematic
- [x] Create PCB layout
- [x] Send design for manufacture
- [X] Order components
- [ ] Assemble boards 
- [ ] ESD testing
- [ ] EMI testing

**Comment by jamesadevine** [comment]
Whoop! 🥳

**Comment by jamesadevine** [comment]
- [x] Create schematic
- [x] Create PCB layout
- [x] Send design for manufacture
- [ ] Assemble boards 
- [ ] ESD testing
- [ ] EMI testing
