### ISSUE TITLE
Batch mode for fast sensor

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#16]
Fitbit supports a batched reading mode to reduce the frequency of packets and send multiple readings at once. 
https://dev.fitbit.com/build/guides/sensors/accelerometer/#batched-readings

Specifically, the sensor might be able to poll the data at a faster rate internally but unable to stream fast enough. 

Practical example: measure forces when an object falls and hits the ground. It will typically a very short large spike which will probably be missed by the sampling.

How many devices can we sample on the bus when we are streaming at 100Hz?

**Comment by mmoskal** [comment]
We can batch multiple packets into a single frame (already supported in the protocol), but there are no timestamps. I guess we would need some way of configuring this.

**Comment by jamesadevine** [comment]
Why would you do this event detection on the brain? have you currently got accel events?

**Comment by mmoskal** [comment]
the accel module probably won't run complex ML models, these may need to be run on the brain; in some cases you want high freq data to be streamed and it's good to be flexible here

**Comment by jamesadevine** [comment]
Peli's use case was fall detection, which can easily be analysed without significant compute resource. If you're planning to stream accelerometer data for custom gesture detection, you'd have a dedicated module for gesture recognition would you not? When training you'd send batch data as described to reduce load on the bus.

I'm generally in favour of batching to improve bus, but it didn't seem necessary for fall detection!

**Comment by mmoskal** [comment]
I think the important bit is batching when sending data from accel to dedicated ML module during recognition. Training is secondary as long as we have enough bandwidth.
