### ISSUE TITLE
Create high power JACDAPter

### ISSUE THREAD

**Issue by tracyttran** [microsoft/jacdac#160]
- [x] Create schematic
- [ ] Create PCB layout
- [ ] Send design for manufacture
- [ ] Order components
- [ ] Assemble boards 
- [ ] ESD testing
- [ ] EMI testing

**Comment by jamesadevine** [comment]
- [x] Create schematic
- [ ] Create PCB layout
- [ ] Send design for manufacture
- [ ] Order components
- [ ] Assemble boards 
- [ ] ESD testing
- [ ] EMI testing

**Comment by tracyttran** [comment]
@jamesadevine  given today's discussion and decision about the power module instead of a high power JACDAPter, can you update this task appropriately? I'm not sure who is in charge of designing the power module.
