### ISSUE TITLE
mixin services

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#162]
These are services that augment existing module and are connected to "parent" service. For example,

- [ ] LED inside an Arcade button
- [ ] analog position reader in a analog servo
- [ ] position encoder in a motor
- [ ] matrix keypad + LED matrix

* A auxiliary service is defined in the sub range ``0x4...``
* Auxiliary services must be following the parent service immediately in the control service list.

```
control
servo
|-- analog reader service
arcade button
|-- led service
```

Other idea:

```
-- light service
-- matrix keypad
--- matrix keypad light service
```

```
[0] control
[1] matrix keypad light service --> 2 sub services following me
[2] matrix keypad
[3] light service
```

**Comment by mmoskal** [comment]
* let's call them mixin services, see https://en.wikipedia.org/wiki/Mixin
* let's use `0x2....` range

**Comment by pelikhan** [comment]
We are not doing this.

**Comment by mmoskal** [comment]
Well, I think we are, just not quite yet.

**Comment by tballmsft** [comment]
Documentation needed

**Comment by pelikhan** [comment]
https://microsoft.github.io/jacdac-docs/reference/service-specification/#mixins
