### ISSUE TITLE
button should have a frac unit

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#20]

**Comment by mmoskal** [comment]
You mean you want a button with pressure reading?

**Comment by pelikhan** [comment]
It does not have a reading right now. But yes a pressure button might be nice but different beast.

________________________________

**Comment by jamesadevine** [comment]
Hopefully a pressure button would be a separate specification that inherits from the button spec?

**Comment by mmoskal** [comment]
It does heave a boolean reading - https://github.com/microsoft/jacdac/blob/master/services/button.md#registers

You want to change that to say u8 frac? so the derivation makes sense?

**Comment by pelikhan** [comment]
Let's keep the button simpled. We could have a new register "pressure" in a derived button that provides a u8. I got dumb and didn't connect that boolean didn't need a unit. will fix the ui.

**Comment by pelikhan** [comment]
What  about "!" which denotes on/off? essentially a unit for boolean values?
