### ISSUE TITLE
Cannot use speech synthesis sim after deleting text

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#200]
# Steps to reproduce:

1) goto https://microsoft.github.io/jacdac-ts/dashboard/
2) add speech synthesis simulator
3) delete text from simulator
4) try to enter new text

# Expected behaviour

The user is able to enter any text they want for the reader to read out.

# Actual behaviour

After deleting all text, the text field is no longer editable.

**Comment by pelikhan** [comment]
Fixed.
