### ISSUE TITLE
reporting cause of power issues

### ISSUE THREAD

**Issue by tracyttran** [microsoft/jacdac#201]
If there is physical modules plugged into the micro:bit JACDApter is estimated* to draw too much power than can be provided, show a warning to the user in MakeCode with 1) an explanation of the potential problem and 2) a suggested way to fix it. 

*use some basic (but not exact) heuristics, such as "we detect a servo is plugged in but do not detect a power module. this is likely to draw too much power from the micro:bit"

**Comment by pelikhan** [comment]
I'm not sure what this entails. Could you specify the scenario?

**Comment by pelikhan** [comment]
This problem is deeper than makecode, it's really a protocol question.
