### ISSUE TITLE
sunset jacdac.org

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#22]
If you search jacdac today, most of the hits land on jacdac.org. In order to send a consistent message, we need sunset the jacdac v1 web site and redirect to the new web site.

**Comment by pelikhan** [comment]
There is also the question of have a domain for jacadac which would be nice.

**Comment by tballmsft** [comment]
why can't we use jacdac.org

**Comment by pelikhan** [comment]
If you search JACDAC on google, it's pointing almost exclusively to the old stuff.

**Comment by tballmsft** [comment]
jacdac.org has been retired.
