### ISSUE TITLE
https://microsoft.github.io/jacdac-ts/tools/js/packets.html broken

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#222]
seems to be missing some file - see JS console

**Comment by pelikhan** [comment]
The npm build failed so it's failing to download the files...

**Comment by mmoskal** [comment]
https://microsoft.github.io/jacdac-ts/tools/packets.html broken

**Comment by pelikhan** [comment]
It's fixed again. Make sure to do "patch: ..." or "feat: "... when you want TS updates to be picked up as the published pages always pull the latest released npm package sources.

**Comment by mmoskal** [comment]
thank you!
