### ISSUE TITLE
role manager improvements

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#231]
* [ ] should disable auto-bind while on role mgr page I think, otherwise use assigning stuff may have strange effects
* [x] if several services share a host like `left_leg/acc`, `left_leg/gyro` (and possibly we have device definition that has both), can we start a combined simulator for them?

**Comment by pelikhan** [comment]
Not sure about disabling autobind, if the user leaves the page then auto-bind stays off?

**Comment by mmoskal** [comment]
start using the restart_in register with say 1.5s delay, every announce. If you re-enable auto-bind, put 0 in restart_in.

**Comment by mmoskal** [comment]
we probably should have some utility functions that time-limit changes with reset_in

**Comment by pelikhan** [comment]
I think this item is done. Auto-bind is always running and the web client listens to change events.
