### ISSUE TITLE
_base has all sensor register?

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#24]
There's a bunch of registers on base that are sensor specific, like cablirate and so forth. But sensor does not have calibrate.

**Comment by mmoskal** [comment]
`_base` is there to reserve register/command codes for common use. No service actually derives from `_base`, so they don't have to include *all* these registers. However registers do derive from `_sensor`, so if it had `calibrate()` all sensors would have to have it (in fact none do currently).
