### ISSUE TITLE
accelerometer units

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#240]
Should we use `m/s2` as the unit? I think this is what various standards say, but all devices ever use `g`.

We surely should increase precision, maybe to `i12.20` ?

@pelikhan @tballmsft @jamesadevine

**Comment by pelikhan** [comment]
G is easier to use.

________________________________

**Comment by mmoskal** [comment]
see https://github.com/microsoft/jacdac/pull/243
