### ISSUE TITLE
service names (eg.: thermometer vs temperature)

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#241]
Some of our services use the name of a sensor (thermometer, accelerometer) and some use the name of thing measured (humidity, wind speed).

Should we unify these? 

We may also have general guidance, but have some exceptions (I would rather have gyro rather than rotational force).

**Comment by pelikhan** [comment]
We could not come up with a better scheme. The name is meant to represent the device or class of devices. Sometimes, the sensor name is good; but something the physical quantity is better.
