### ISSUE TITLE
block range picker does not hangle 0...1 range

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#244]
Blockly range expects integer. Does not play well with our 0..1 ranges.

**Comment by mmoskal** [comment]
Maybe % wouldn't be so bad, even in TypeScript.

We could even have a function like - `(v | 0) == v ? Math.idiv(v<<16, 100) : v * ((1 << 16)/100)` - no floating point ops when no floating point input

**Comment by pelikhan** [comment]
Yes better. The value in code match the one displayed.

________________________________

**Comment by pelikhan** [comment]
@mmoskal do we have % support in jdpack?

**Comment by pelikhan** [comment]
Note that 0..100% is generally more intuitive than 0...1 for users (specially younger ones who don't understand decimals well)

**Comment by mmoskal** [comment]
it may be problematic for math (you'll have to divide by 100 every now an then), but I guess it's the price worth paying.

to be clear - we're not changing anything in the services, only in the MakeCode APIs, right?

**Comment by pelikhan** [comment]
Yeah I will change the code generator of MakeCode to do the conversion

________________________________

**Comment by pelikhan** [comment]
Use 0..100 range now.
