### ISSUE TITLE
physical and virtual micro:bits

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#248]
When we download a program to connected micro:bit, we end up having the same program running in the simulator and on the virtual micro:bit.  Let's discuss possible ways to address this.

**Comment by mmoskal** [comment]
do we have any other issue tracking this? this is something we'll need to implement - only running program on one of the microbits.

**Comment by pelikhan** [comment]
Here is the current potential plan:

- when a new device N joins the JD bus with a role manager, any existing other role manager device R queries the uptime of th  device N, if uptime of N is shorter, device N wins and become the new role manager. Device R disables itself and acts as a proxy if needed.

**Comment by pelikhan** [comment]
- early simulator restart: https://github.com/microsoft/pxt/pull/7993
