### ISSUE TITLE
"START SIMULATOR" title confusing

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#249]
The new "START SIMULATOR" button is confusing, as we already use the term "simulator" to refer to the micro:bit simulator. I think the purpose of this button is to start the Jacdac simulator, correct? We should probably refer to Jacdac somehow. Also, pushing the button right now does nothing - I have no way to add virtual devices. 

![image](https://user-images.githubusercontent.com/10767146/107808283-2c9f0e80-6d1e-11eb-84dc-9e3825a1bd96.png)

**Comment by tballmsft** [comment]
Ah, when I go to full screen, after pushing "START SIMULATOR" I see the full iframe. Somehow in the default view, the iframe is not being resized correctly.

![image](https://user-images.githubusercontent.com/10767146/107808603-ba7af980-6d1e-11eb-8c23-dbae60dcbf7e.png)

**Comment by pelikhan** [comment]
Button gone.
