### ISSUE TITLE
packet identifier already used

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#25]
Try this in https://microsoft.github.io/jacdac-ts/tools/service-editor
```
# Pressure Button

A button with pressure reading.

        identifier: 0x16e8c679
        extends: button

## Registers

    ro pressure2: u8 @ reading

Reads the current pressure of the button.
```

![image](https://user-images.githubusercontent.com/4175913/90839380-4120c200-e30c-11ea-809b-406155219aab.png)

**Comment by mmoskal** [comment]
Yeah, currently there is no override facility. We need to think what it actually means though - is it allowed to change return types?

**Comment by pelikhan** [comment]
I think the problem is that the tool should allocate a new register

**Comment by pelikhan** [comment]
I see it’s a reading so that’s the problem?

**Comment by mmoskal** [comment]
Yes. You have to allocate registers, `@ 0x180` or something

**Comment by mmoskal** [comment]
Note that if it's not. the `reading` register, it will not stream.
