### ISSUE TITLE
jacdac-ts reading_error is not displayed

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#252]
**To Reproduce**
* Start humidity simulator
* Go to tree
* Observe no value for humidity_error

Same happens on hardware - we never ask for error.

**Comment by pelikhan** [comment]
The TS client assumes that a sensor also sends the reading error packet in the same frame as the streaming (as specified).

https://github.com/microsoft/jacdac-ts/blob/main/src/jdom/bus.ts#L849

I've updated the simulator to do the same for humidity... but it would be nice to be able to assemble a frame in TS as well. It's currently 2 packets being sent.

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/108195313-e380fd00-7117-11eb-900f-2aa76ed8914c.png)

Ok my bad, it's only when it changes. I'll fix up the logic.

**Comment by pelikhan** [comment]
Fixed.

**Comment by pelikhan** [comment]
Hardware must send the error if it changes.

**Comment by mmoskal** [comment]
The hardware doesn't currently auto-send error

**Comment by tballmsft** [comment]
@pelikhan - status of this?

**Comment by pelikhan** [comment]
how do i test this with hardware?

**Comment by pelikhan** [comment]
@mmoskal

**Comment by mmoskal** [comment]
Sensors still don't auto-send errors. Our temp sensor should have different error outside of 0-65C range, but I'm not sure we can product such temperatures...

**Comment by pelikhan** [comment]
fixed
