### ISSUE TITLE
button twin not responding to button events

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#253]
Since Michal removed streaming from buttons, the button twin no longer shows button presses. In general, all twins should be responsive to events and not default to relying on streaming.   Do we need to implement polling on the client side for registers?

**Comment by mmoskal** [comment]
It should still be possible to have button stream data; it could be broken.

I think for most sensors streaming makes sense, though not for button. However, if it's just generic code, then streaming is fine.

**Comment by pelikhan** [comment]
The button is treated as a sensor; thus the UI will set the streamSamples registers and the button should start streaming. At least, that's the specified behavior. We could special case the button in the future but streaming should work.

**Comment by tballmsft** [comment]
It's not currently working.
