### ISSUE TITLE
test suggestions from Steve

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#256]
We want to think about the tests that a manufacturer might do, compared to the tests that the firmware designer will want to do.

For example, for the rotary encoder:
- a firmware designer will use the specification tests to do check off that they meet the functional requirements
- a manufacturer will perhaps just want to test that turning the knob changes the value

**Comment by pelikhan** [comment]
Operator might not speak / read english on factory floor.

**Comment by pelikhan** [comment]
IMO, focus on 1st scenario first, probably build another test suite for manufacturer.
