### ISSUE TITLE
move CRC to the end of the frame?

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#276]
From #273 :

> > Maybe we should move the CRC at the end of the frame so that smaller processors can compute crc in spare cycles during transmission.

> This is another breaking change to the protocol format.

This needs some careful consideration, because lots of code depends on this - much more than the last global breaking change that we did - the triplicate events (the previous such change was introduction of registers about a year ago).
* it would be more natural to have CRC follow the data
* maybe it would simplify ASIC implementation? or even a specialized Jacdac perisperhal in an MCU could easily compute CRC on the fly
* there are problems with data alignment - the device ID is 8 bytes, and we would like it to be 4-byte aligned; we also need packet length which is 1 byte, and we want the packet (not frame) header to be also 4-byte aligned

**Comment by pelikhan** [comment]
Looks we need to make those changes to support 8bit now and synchronize who does what.

________________________________

**Comment by jamesadevine** [comment]
I think it makes sense to move CRC to the end. Not sure what to do about alignment though...
