### ISSUE TITLE
test framework todos

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#282]
- [ ] checking for events
- [ ] sending of commands
- [ ] writing of registers
- [ ] dealing with noisy data (approximate matching, use of error register)
- [ ] support reading fields of registers
- [ ] inherit superclass tests

**Comment by tballmsft** [comment]
@pelikhan, @mmoskal - I want to collect ideas for what else may be needed in the test infrastructure.  Of course, this list can grow without bound, so let's also chat to prioritize.

**Comment by pelikhan** [comment]
not sure about inheritance of tests. we basically have 1 subclass: sensor. The rest is not shared.

**Comment by pelikhan** [comment]
That looks like a great start. You should do a round of writing tests and it will reveal the pieces your are missing.

**Comment by pelikhan** [comment]
We should probably move this kind of "issue" into the discussion section.

**Comment by tballmsft** [comment]
oh, i forgot about discussions. thanks.
