### ISSUE TITLE
semantics of button service

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#289]
What is the meaning of long_click and hold? Here is the current service spec: https://microsoft.github.io/jacdac-docs/services/button

**Comment by tballmsft** [comment]
@mmoskal said:

```
[10:57 AM] Michal Moskal
    so hold and long_click are the same but with different timeouts
    long_click used to be emitted with up
    but that makes for a really bad ux
    you hold it, and you don't know if you held it long enough
    we should rename: long_click -> hold, hold -> long_hold

```

**Comment by jamesadevine** [comment]
We have used the following button semantics from the inception of MakeCode/micro:bit dal/CODAL:

Click: down, delay < 500 ms, up, click.
Long click: down, delay of 500 ms-1500 ms, up, long click.
Hold: down, delay >1500ms, hold, up. There may be an indefinite time between hold and up.

**Comment by mmoskal** [comment]
Well, this doesn't mean it's a good idea. I've never seen an appliance (even such wonder of UX design as my dishwasher) that would do something on long click in the above definition - the reason being there's no feedback - you hold it, and hold it, and you never know.

**Comment by mmoskal** [comment]
another way to slice it, is:

Click: down, delay < 1000 ms, up, click.
Hold: down, delay >1000ms, hold, up. There may be an indefinite time between hold and up.

**Comment by pelikhan** [comment]
We should drop long click and keep hold.

________________________________

**Comment by jamesadevine** [comment]
How can you have a long hold? It's either held or not held IMO.

**Comment by jamesadevine** [comment]
If we are dropping an event, I'd like to retain the ability to roughly know how long a click or a hold is. Having differentiation is important when considering accessibility scenarios. We should also talk about the ability to tune the length of time it takes to trigger a click or a hold.

**Comment by mmoskal** [comment]
The up event could have a time argument. If you want differentiation you could then implement it that way (just ignore click events).

Or we could add `click_threshold` register, but that may be overdoing it ?

**Comment by tballmsft** [comment]
We have flexibility with MCU, so I think adding some time information is a great idea.

**Comment by pelikhan** [comment]
We never used long click in MakeCode btw.

________________________________

**Comment by tballmsft** [comment]
Do we need some design principles around services? Like exposing time for time-sensitive actions/events.

**Comment by mmoskal** [comment]
I think we'll learn more as we try to use these services.

So I propose: removing long_click, changing click/hold threshold to 1s, and adding time to up event. Anyone against?

**Comment by jamesadevine** [comment]
I think that sounds good. Time might be hard on the padauk? Maybe it'll be fine. At least we will be able to tune the event detection in software.

**Comment by mmoskal** [comment]
well, whatever we do, I do think we'll need at least 24bit timer on Padauk

**Comment by tballmsft** [comment]
OK. I will make changes to spec and the C code.

**Comment by tballmsft** [comment]
I was thinking to add a register to allow programming of the hold time (minimum 500ms)

**Comment by pelikhan** [comment]
We need to be careful about setting ranges so that we don't end up with franken-buttons that all behave differently.

**Comment by tballmsft** [comment]
OK. I was thinking that the default would be 500ms.  Do you prefer a small set of presets? Or just jettison the idea altogether?

**Comment by pelikhan** [comment]
What are the scenarios that would require to change the timings on the buttons?

**Comment by pelikhan** [comment]
Let's track this here: https://github.com/microsoft/jacdac/pull/292

**Comment by jamesadevine** [comment]
If someone is not unable to press a button in the time frame we define. For example, if someone has cerebral palsy, it's unlikely they will be able to press and release a button in under 500 ms.

**Comment by pelikhan** [comment]
Okie. So we have:
- click minimum time
- hold time
what else?

**Comment by mmoskal** [comment]
I think for sanity we should have click min time == hold time.

**Comment by pelikhan** [comment]
For many bike lights, it's not uncommon to use "hold" as a way to turn off the device. That hold requires several seconds to trigger, which click is just a few hundred ms.

**Comment by tballmsft** [comment]
> I think for sanity we should have click min time == hold time.

Ah, a dependent type! But seriously, is this just English in spec with some tests?

**Comment by mmoskal** [comment]
I think we should just have one register, and in the English description we use it for both events.

**Comment by tballmsft** [comment]
I don't understand how you can use one value for both events.  click is faster than hold. I guess I don't understand what you mean by click min time == hold time.

**Comment by mmoskal** [comment]
I think there should be one threshold. If the button is pressed less than that, you get a click, and if it's pressed more than that you get a hold.

**Comment by tballmsft** [comment]
OK. I'm not sure that will work for James' accessibility requirements...

**Comment by tballmsft** [comment]
I updated the PR.

**Comment by jamesadevine** [comment]
I think the threshold would work. 

I'm just worried about arbitrarily making decisions without going and asking the people who use the hardware. What if in a few months we decide these button changes were net bad? Sure we can change the spec, but if we're going to be burning button code into OTP flash (i.e. on PADAUK) then we have no facility to change button behaviour in the future and no backwards compat story.

**Comment by mmoskal** [comment]
It's a button, how complicated it can be? :) If we put that much deliberation into other services we would never get anywhere.

Anyway, you can implement whatever behavior you want with the timestamp in up event.

**Comment by jamesadevine** [comment]
Have a look at other software implementations and look for yourself how much though goes into button API design :smile:

**Comment by mmoskal** [comment]
I think I value my sanity too much... 

;)

**Comment by pelikhan** [comment]
Is this done? @tballmsft

**Comment by pelikhan** [comment]
I got some new headphones and they use 2 second = on, 3 seconds = off

**Comment by mmoskal** [comment]
Let's do what @pelikhan suggested - let's send `hold` event with duration every `500ms`. Let's also remove the `click` event and `click_threshold` - this will simplify impl on Padauk - we'll never (...well, very rarely) have to send two events right after another - and it will also simplify the mental model - it's up to the client to decide what is hold and what is click.

**Comment by mmoskal** [comment]
(which is not to say we should encourage people to design such horrible interfaces, like two different functions on 2s and 3s hold...)

**Comment by tballmsft** [comment]
Interesting idea - I am happy to implement/test.  OK with you @jamesadevine?

**Comment by jamesadevine** [comment]
So we are proposing to remove the smarts from the button? What is the microcontroller actually doing in this case then?

**Comment by mmoskal** [comment]
Well, if we send the time the button was down, this is strictly more information than a click event. Similar for repeated hold.

My general rule of thumb is that programmable logic belongs on brain, unless there are compelling reasons to put it on the module (eg. because of limits in the transmission rate, or because the logic depends on hardware (eg. servo gets degrees not microseconds because that can be calibrated by the manufacturer).

**Comment by tballmsft** [comment]
On the other side, we need to have the module expose enough information for the brain to make decisions. We have added time to up event and are now repeating the hold event every 500 ms and eliminating click, so I think the brain has all the information it needs with up, down and hold (though we are fixing the hold to only send every 500ms). Everyone OK with this?

**Comment by tballmsft** [comment]
Unless I hear otherwise, I'll work on this tomorrow.

**Comment by tballmsft** [comment]
Here is the update spec and tests: https://github.com/microsoft/jacdac/pull/315

**Comment by tballmsft** [comment]
done

**Comment by tballmsft** [comment]
Reopening this issue. To recap, we have now (implemented in spec, firmware, test):
- a fixed 500ms threshold for generating a hold event
- up and no down for >=500ms generates a hold event, and as long as no down, for every 500ms after that
- the trace [up,down] (no hold event) is a "click"
- the trace [up,hold,down] is a "long click"

The only issue here I see is that we force the user program (client) to recognize sequence of events in order to implement click and long-click.  We could have a concept of client-side events that are functions of traces of server-events.

**Comment by pelikhan** [comment]
Or have "hold", "long hold", no repeats.

**Comment by mmoskal** [comment]
You don’t need traces to detect events on client (you may want to check them for testing though) - up with time less than 300ms or whatever is click and hold with time between 500 and 999 is hold (where the client sets the thresholds)

**Comment by tballmsft** [comment]
Good point, Michal.   There's still some logic needed. My point is we could define such events and have code generated automatically.

**Comment by tballmsft** [comment]
I think we should keep the repeated hold event.  It's useful to have the MCU communicating that the button is still being pressed (like a "i'm still alive" at the user-level).   Otherwise, we are dependent on client code getting the up event, which it might miss.

**Comment by mmoskal** [comment]
Yes, definitely keep them - they allow client code to respond to any hold period (with 500ms granularity)

we could have synthetics events; would it also require synthetic register (click time, hold time)?

**Comment by mmoskal** [comment]
most definitely client-side; no reason to complicate providers

**Comment by tballmsft** [comment]
Right. Do you think we should define these synthetic events in the spec? If so, we could use my little test language to define the conditions under which a synthetic event fires.  Most synthetic events should be very simple stated in terms of events. If more computation is needed then we just define the synthetic event and tests for it, and it is up to (probably us) to implement it.

**Comment by tballmsft** [comment]
Let's continue discussion of synthetic events here: https://github.com/microsoft/jacdac/issues/318
