### ISSUE TITLE
spec revisions

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#29]
- [x] factor out frames and packets @jamesadevine 
- [ ] reserve version bits in frame flags @mmoskal 
- [x] history section with dates and deltas -- not needed now
- [x] sws, replace physical @jamesadevine 
- [x] frames/packets move into separate doc @jamesadevine 
- [x] remove requirements page @jamesadevine 
- [x] commands/actions/registers in specification/service layer @jamesadevine 
- [ ] glossary @tballmsft 
- [ ] Pipes and events in Service page @mmoskal 
- [x] copy content from current jacdac site to docs/pages/index.mdx @pelikhan 
- [ ] hardware/power/electrical specification @sehodges @jamesadevine 
- [ ] connect specification @sehodges
- [x] html redirect and comment @jamesadevine 
- [ ] cool images of connectors @sehodges @mgabrieledamone
- [ ] bus architecture image @tballmsft 
- [x] JACDAC favicon? @mgabrieledamone
- [ ] hardware connector repository @jamesadevine 
- [x] update color scheme for material ui @mgabrieledamone https://in-your-saas.github.io/material-ui-theme-editor/

**Comment by pelikhan** [comment]
@mgabrieledamone could you start adding rendering of the devices/connectors?

**Comment by mgabrieledamone** [comment]
> @mgabrieledamone could you start adding rendering of the devices/connectors?

Hey @pelikhan, I haven't uploaded renderings yet as the connector will probably change quite a bit in the next few days...
In the meantime, could you tell me the specific areas (and context) of where you want images? This way I can start drafting out the rendering layout!

**Comment by pelikhan** [comment]
@mgabrieledamone just add as many renderings as you can so that we can pick and choose.

**Comment by tballmsft** [comment]
@jamesadevine, let's revisit this list at the next spec meeting.

**Comment by pelikhan** [comment]
Closing this in favor of separate items.
