### ISSUE TITLE
support for number constants in specs

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#293]
We have a few constants here and there in our specs that are not captured and code generated. I'm proposing to add syntax for numerical constants.

```
    constant: magic= 0x42
```

**Comment by mmoskal** [comment]
I think this is a good idea, why close?

**Comment by mmoskal** [comment]
I would rather use `const magic = 0x42` in the code section though, to align with enums

**Comment by pelikhan** [comment]
it would be good to prioritize this so that we can move all the magic constants of the protocol in the spec and code-generate them for any environment. @mmoskal

**Comment by pelikhan** [comment]
Implemented as "define foo 0
