### ISSUE TITLE
no digital twins in simulator

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#294]
on microbit/beta I plug-in a jacdac network that appears fine in jacdac-ts, and it doesn't appear in simulator (pxt-jacdac extension is loaded).

**Comment by tballmsft** [comment]
![image](https://user-images.githubusercontent.com/10767146/111681155-2d750580-87e0-11eb-8560-34d42f892741.png)

**Comment by pelikhan** [comment]
- share the MakeCode project
- did you flash the device with the latest MakeCode binaries
- is MakeCode connected to the microbit?

**Comment by tballmsft** [comment]
did you flash the device with the latest MakeCode binaries

- No

**Comment by tballmsft** [comment]
I did with https://makecode.microbit.org/_epKVvm3WYJXf - same result - no digital twin. 

micro:bit is paired over USB with JACDAC devices plugged in.

**Comment by tballmsft** [comment]
app above uses latest version of pxt-jacdac

**Comment by tballmsft** [comment]
Even though simulator has no digital twins, I get this when I press Add Blocks, which accurately reflects the devices plugged in: 

![image](https://user-images.githubusercontent.com/10767146/111687031-0b32b600-87e7-11eb-8b57-a17fa9edf9b8.png)

**Comment by pelikhan** [comment]
Fixed in the next build.
