### ISSUE TITLE
invalid memory; try power-cycling the micro:bit

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#296]
micro:bit requires power cycling after a few connect cycles.

- 1 open https://microsoft.github.io/jacdac-docs/dashboard/]
- 2 connect microbit
- 3 disconnect micro:bit
- repeat 2,3 until the error shows up.

**Comment by mmoskal** [comment]
did it several times, no issue

**Comment by pelikhan** [comment]
Closing since it does not seem to repro.
