### ISSUE TITLE
support new format of dist/ folder

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#297]
The dist/ folder will now have .uf2 files for all releases - we no longer need to use github release API, and instead just go here:

https://api.github.com/repos/microsoft/jacdac-msr-modules/contents/dist

and then use downloadUrl for files matching `*-VERSION.uf2`. @pelikhan can you look dropping gh releases from github.ts and using this instead? We'll also need to update firmware repo in the device catalog.

**Comment by mmoskal** [comment]
there's also now this https://github.com/microsoft/jacdac-msr-modules/blob/main/CHANGES.md which will be auto-updated when tagging a new version; not sure what we do about it though

**Comment by pelikhan** [comment]
Is version with v or no v?

**Comment by mmoskal** [comment]
No v. Also no need to look at tags - it’s all on main/master

**Comment by pelikhan** [comment]
There is 2 versions of the file right now.

________________________________

**Comment by mmoskal** [comment]
Correct, there will be more as we'll build more releases. They should show up in dropdown just like gh releases do now.

**Comment by pelikhan** [comment]
Should be done now. Would be good to have a second release to check sorting.
