### ISSUE TITLE
temperature what does it mean?

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#30]
The operating temperate of device may vary and we curerntly don't have enough info to raise an alarm or not.

My GPU runs at 84deg when playing CoD, it's normal. But this temparure might not be acceptable for other devices.

When does a device run hot? does it raise events?

**Comment by mmoskal** [comment]
I think it's informational only. The acceptable temperature will depend not only on device, but also on the it's casing (which may be user supplied) and use case. I think it would be nice to show it, but I would not sweat with alerts.

**Comment by jamesadevine** [comment]
Yes, I thought temperature was "ambient" temperature with respect to silicon die temperature. I also understand that temperature is optional, and not all devices will implement it (especially those without the capability to detect silicon die temperature).
