### ISSUE TITLE
Dash board does not update if a device "re-enumerates"

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#300]
**Describe the bug**
When viewing the dashboard, if a device changes the service it is advertising, the dashboard does not update the digital twin. It continues to display the previous service digital twin on the dashboard. A page refresh causes it to re-detect the services on the device and display the correct digital twin.

**To Reproduce**
Too hard to create a repro with hardware; do not have enough devices to ship. It might be easier to emulate a jacdac device in typescript to repro this bug.

1) go to dashboard
2) enumerate as a device e.g. potentiometer.
2) reset the device and enumerate a different service e.g. button
3) note the dashboard does not change

Note, if the device is unplugged for 10 seconds so the dashboard detects that the device has been unplugged, the dashboard will reflect the new service when the device is re-connected.

**Screenshots**

![Screenshot 2021-03-23 at 22 33 30](https://user-images.githubusercontent.com/4742697/112227583-cd3ef300-8c27-11eb-83e1-96dc8751085b.png)
![Screenshot 2021-03-23 at 22 33 55](https://user-images.githubusercontent.com/4742697/112227629-dcbe3c00-8c27-11eb-9bee-9c6b6277aae5.png)

**Comment by mmoskal** [comment]
pxt-jacdac just removes the device object and adds it back when the reset counter goes back. Maybe this is what we should do in device.ts:338 instead of emitting RESTART events?

**Comment by pelikhan** [comment]
It's probably a matter of not tracking the change event in react, it should auto update.

I need this for the role manager switching anyway (proxy device sends empty list of services).

**Comment by jamesadevine** [comment]
@pelikhan I'll demo to you later on our call, but the basic premise is that some modules may dynamically present different services based upon what is connected to them. A good example might be michal's click -> jacdac module. Potentially, the firmware might be able to detect multiple different click modules and re-enumerate itself at runtime depending on which one is connected.

For my specific example, the XAC input module, users may connect three different types of input: digital button, analog trigger (potentiometer), and x/y joysticks. When the module detects a different input has been connected, the module resets itself and begins advertising the corresponding service. I expected the dashboard to dynamically update in this case, but I guess I should send a reset event?

**Comment by pelikhan** [comment]
No we should be able to handle this in React.

**Comment by pelikhan** [comment]
>  Potentially, the firmware might be able to detect multiple different click modules and re-enumerate itself at run time depending on which click module is connected.

Is this plug and play though? Potentially, you'd want to do this before starting the jacdac stack.

**Comment by jamesadevine** [comment]
I do. The XAC input module detects the new configuration, and reboot the device. On start up it detects the input and enumerates the correct service.

It's meta plug and play

**Comment by jamesadevine** [comment]
https://github.com/microsoft/jacdac-msr-modules/blob/main/targets/jm-XAC-input-34-1.0A/profile/xac.c#L80

**Comment by pelikhan** [comment]
i see let me get a test for that

**Comment by jamesadevine** [comment]
Awesome, thanks @pelikhan  :smile:

**Comment by pelikhan** [comment]
![dynamicservices](https://user-images.githubusercontent.com/4175913/112327792-f5a00f00-8c72-11eb-9750-27e770488db7.gif)

**Comment by pelikhan** [comment]
So another scenario would be that a device has a power service, which only enables services when it's on (anyway it's my test)

**Comment by jamesadevine** [comment]
User reports that the sim still does not update if a device dynamically changes its services.

**Comment by pelikhan** [comment]
This should be fixed now. Reopen if it does not work again.
