### ISSUE TITLE
jacdac-docs domain hosting

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#302]
We need a compliant domain to host jacdac-docs.

**Comment by pelikhan** [comment]
Once the new domain is setup, update arcade/microbit/maker/pxt-jacdac with location

**Comment by pelikhan** [comment]
We could use https://docs.microsoft.com/en-us/azure/static-web-apps/ for hosting.

**Comment by mmoskal** [comment]
jacdac.github.io has to be hosted on gh pages; if we can use another domain, than these static web apps seems fine

**Comment by pelikhan** [comment]
deleted jacdac.github.io

**Comment by pelikhan** [comment]
Per discussion with release team, we are staying on https://microsoft.github.io/jacdac-docs for now.
