### ISSUE TITLE
lo-pulse delay

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#304]
**Describe the bug**

Waking up from sleep, transferring RTC timer to regular timer, and setting reception takes 50-60us on F0 running at 8MHz (depending on how much clock have to be updated). MakeCode on micro:bit has 14us lo-pulse and 42us delay, for a total of 56us, so sometimes we manage to set it up in time and sometimes we don't. This is why modules lose packets from micro:bit.

I did some fixes in https://github.com/microsoft/jacdac-stm32x0/commit/21d02d92e321f01a6829859643aa269bf590fc3a and now it generally falls under 56us, though every now and then it doesn't.

The spec has minimum delay of 40us, and I think we should rise that to 50us so that we have some buffer.

I don't think this is going to be a problem for lower-end MCUs as they won't have complicated timers to update on wake up (if they even sleep). It's also not a problem for G0 as it runs at 16MHz.

**Comment by mmoskal** [comment]
@jamesadevine comments?

**Comment by tballmsft** [comment]
wow, nice catch.

**Comment by jamesadevine** [comment]
This is after max cycle skimming? Again it feels like we shouldn't necessarily change the length of the low data gap without good reason. Are you also proposing to change the top threshold so low pulse data gap could be 50-100 us?

Even with 50 as the new minimum the stm32f0 will not be necessarily compatible with every other jd implementation...

**Comment by mmoskal** [comment]
Why wouldn't it be compatible? I was missing 3us or so with the 42us delay. The times I quoted for F0 are from the beginning of the lo-pulse (because that's when we get an interrupt).

I think F0 is pretty much the worst case - we sleep it, is slow when it wakes, and we use RTC because it doesn't have low-power timer (so we have to convert RTC to TIM17 on wake up).

**Comment by mmoskal** [comment]
As discussed offline with @jamesadevine we need to update the docs to say:
* min delay after low-pulse is 50us; implementations should stay as close as possible but above 50us
* we can increase the max time from 100us to 200us (we almost never pay that)
