### ISSUE TITLE
interoperability testing of protocol layer

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#305]
We will have 5 separate implementations of the JD protocol: 
- jacdac-c
- jacdac-ts
- pxt-jacdac (forked from jacdac-ts/jadac-c a while ago)
- assembly (Paduak)
- python

The issue here is to test that the various implementations of the JD protocol interoperate correctly with one another (that is, they all implement the same protocol).  Testing protocol from jacdac-ts over webUSB introduces too much delay, so @mmoskal suggested we write protocol level tests (acks, events) using MakeCode and run from micro:bit V2 (or better yet, Arcade so we have a screen for showing test status). I would like to start on this. Discussion?

**Comment by jamesadevine** [comment]
I think we should discuss this together. This is what Chandler is working on.

Best,

James
________________________________
From: Tom Ball ***@***.***>
Sent: Friday, March 26, 2021 12:30:53 AM
To: microsoft/jacdac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/jacdac] testing protocol layer from mkcd (#305)


We will have four separate implementations of the JD protocol:

  *   jacdac-c
  *   jacdac-ts
  *   pxt-jacdac (forked from jacdac-ts/jadac-c a while ago)
  *   assembly (Paduak).

Testing protocol from jacdac-ts over webUSB introduces too much delay, so @mmoskal<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmmoskal&data=04%7C01%7Ct-jamdev%40microsoft.com%7C3a739e01d3a54427ee9208d8efee6a28%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637523154548169187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iakILcy1S2OFkr%2FZydcYaY6DiYQw4CA1U%2B03NGSVuKY%3D&reserved=0> suggested we write protocol level tests (acks, events) using MakeCode and run from micro:bit V2 (or better yet, Arcade so we have a screen for showing test status). I would like to start on this. Discussion?

**Comment by sehodges** [comment]
Happy to involve more people in the work with Chandler, just conscious of previous feedback that there were too many meetings with too many people in them. 

Thanks @jamesadevine for pointing out this discussion was happening on github! And +1 on making sure the convo is inclusive.

**Comment by pelikhan** [comment]
A test infrastructure using an arcade screen/ui sounds like a good plan.

**Comment by sehodges** [comment]
yes, that is in part what we have on the r pi testing hat - it has an STMF4 with a connector for an arcade display. the pi is necessary in some scenarios, e.g. for running open OCD to flash a bootloader-less MCU in the factory, but we could make everything on the pi hat composable out of Jacdac modules - we could even have a Jacdac module that does SWD flashing to cover that scenario...

**Comment by tballmsft** [comment]
I understand the desire to test hardware modules - that is what I understand Chandler to be working on. I am also pointing out we need to test the four separate implementations, two of which run in the web browser.

**Comment by tballmsft** [comment]
@jamesadevine - is chandler on github?

**Comment by pelikhan** [comment]
I think in this scenario we assume that the hardware is "perfect" and we are interested in testing the protocol implementations/SDKs, so it's fine to have both efforts going in parallel.

**Comment by jamesadevine** [comment]
Yes @tballmsft, @airchandler! 

Well it might be all good and well to have both efforts going in parallel, but if parallel efforts are going to result in the same thing it might be better to coordinate work to reduce duplicate effort.

**Comment by pelikhan** [comment]
My understanding is that you assume the procotol SDKs are correct, while Tom will working on testing protocol implementations. So both sets of tests are looking at the different part of the stack.

**Comment by jamesadevine** [comment]
Eh? Chandler is working on the Pi testing hat that seeks to do testing and validation of electronics designs. On the Pi hat is a microcontroller connected to circuitry for diagnostics and analysis. We intend to use this circuitry for voltage and current testing, and in addition, for validating physical layer implementations. As part of this, he is creating low-level testing APIs...

Perhaps I misunderstood @tballmsft's first post, but it sounds the same to me?

**Comment by tballmsft** [comment]
I don't think we are talking about the same things, James. Let's have a call.

**Comment by tballmsft** [comment]
I updated the title and description to more accurately describe the issue, which is interoperability of the various implementations of the protocol.

**Comment by jamesadevine** [comment]
Got it! thanks @tballmsft apologies for the crossed wires :smile:
