### ISSUE TITLE
synthetic events

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#318]
Following on from the semantics of the button service (https://github.com/microsoft/jacdac/issues/289), there is a potential need for defining client-side events as well as server/host-side events. In particular, the button service defines three events:
- down
- up (time since down)
- hold (time (since down)

A click event can be defined at the user-side as an up with time < 300ms (for example). Should we have a way to describe such events at the specification level?

**Comment by mmoskal** [comment]
Would be good to figure out if there is more examples. Maybe servo could be simplified?

**Comment by tballmsft** [comment]
A general pattern might be that an event generated on a host has a time associated with it, and there are other events that depend on time.  If events that are time-sensitive don't advertise their time (like up), then the client-side can't (re)define click vs. long-click without doing its own timing.

**Comment by tballmsft** [comment]
The other (obvious) point is that the MCU close to the sensor/actuator is in the best place to record accurate timings for events, as the MCU is directly connected.

**Comment by mmoskal** [comment]
I thought we wanted both up and hold to have durations? You're right about measuring close to source (though this is a bit of  red herring here, since we don't expect more than a few ms processing delay, which doesn't matter for button; OTOH our triplicate event repetition has repeats at 20ms and 100ms, which may matter even for a button)

**Comment by tballmsft** [comment]
In the button spec, both up and hold do have durations.

**Comment by pelikhan** [comment]
I'd rather not specify the client side event. This will make it more flexible to fit within the given client coding style.

**Comment by tballmsft** [comment]
We eliminated click as an event for the button service. I do think that there are events that are generally expected for certain types of devices.  We need some way to specify them if we have chosen not to generate them at the host.

**Comment by pelikhan** [comment]
What is the status?

**Comment by tballmsft** [comment]
The status is that we no longer have click event in the button spec, per our discussions. Instead, you will need to register on the "up" event and then check that the time argument is less than some threshold.

**Comment by tballmsft** [comment]
i'd like to restart discussion around this topic. Perhaps tomorrow after standup?
