### ISSUE TITLE
assert in test crashes entire ui

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#329]
Use this test which asserts

```
# Compass tests

## North

Using another compass, turn the compass to the North

    check(closeTo(heading, 0, 1))
```

and crashes the entire UI. All runtime exception in the test framework need to be swallowed and surfaced to the user.

![image](https://user-images.githubusercontent.com/4175913/113584640-6fe57180-962b-11eb-9256-53b68fa9fde9.png)

**Comment by tballmsft** [comment]
oops. sorry about that. Do

    closeTo(heading, 0, 1)

instead of wrapping in check.

**Comment by pelikhan** [comment]
The bug is more about guarding those exception so that the UI does not crash.

**Comment by tballmsft** [comment]
got it - I am finishing off the implementation.
