### ISSUE TITLE
(field-like) references to common constant values (absolute_minimum, etc). 

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#335]
The test parser currently doesn't handle (the field-like) references to the following:

- [ ] max_bytes
- [ ] typical_min
- [ ] typical_max
- [ ] absolute_min
- [ ] absolute_max
- [ ] preferred_interval

Also, note that the above are hardcoded in jdspec.ts. Should we have a more general way of adding such constant fields"?

Furthermore, the spec uses the one-line { ... } notation, which is odd as { ... } over multiple lines is used to give structure to a register/command/event.

**Comment by pelikhan** [comment]
They are hardcoded in the parser :)

**Comment by tballmsft** [comment]
yeah, i know... :(
