### ISSUE TITLE
jacdac icon

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#337]
We are starting to have multiple variants of the icons flying in our decks and around. We need to finalize and settle on 1. Here are place where the icon lives:

- [x] pxt-microbit (for the bloc category)
- [x] jacdac-docs
- [x] pxt-jacdac icon.png fie

Probably forgetting some additional ones.

**Comment by jamesadevine** [comment]
@pelikhan I think @mgabrieledamone has the different design skews for the logo. He showed them on a call last week when you were away!

**Comment by mgabrieledamone** [comment]
[Jacdac_Logo_2021.zip](https://github.com/microsoft/jacdac/files/6270817/Jacdac_Logo_2021.zip)

Here it is Peli :)

**Comment by pelikhan** [comment]
@mgabrieledamone can you export it in a way where it is completely centered. There is some kind of large white space defined in the path encoding.
![image](https://user-images.githubusercontent.com/4175913/113863547-a8399c80-975e-11eb-9638-62f52be9e0f6.png)

**Comment by pelikhan** [comment]
Looks like there was some junk points in the path. updated.
![image](https://user-images.githubusercontent.com/4175913/113865010-71fd1c80-9760-11eb-9546-df1710039717.png)

**Comment by pelikhan** [comment]
We might want to consider the previous flatter design for small icons. Here's a compare:
![image](https://user-images.githubusercontent.com/4175913/113866200-e1274080-9761-11eb-9dc3-f5369f6e589a.png)
