### ISSUE TITLE
unique names in specifications

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#339]
Currently, names in specifications are divided up by packet types, so it is possible for a register and event to have the same name. I propose that we disallow multiples uses of same name in a specification to reduce change for confusion.

**Comment by pelikhan** [comment]
@mmoskal this seem like a good idea

**Comment by mmoskal** [comment]
yes; I'll do it next time I get to the spectool unless someone beats me to it ;)

**Comment by pelikhan** [comment]
lemme take a look

**Comment by pelikhan** [comment]
Seems thiat this is already being done.

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac/blob/fcecddd951984fb4839ffc486d2f19070c5ccad4/spectool/jdspec.ts#L585
