### ISSUE TITLE
role manager

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#34]
Refactor do "role" -> "device"

**Comment by jamesadevine** [comment]
Sorry, trying to interpret the cryptic todo. I assume that you are not proposing renaming Devices to Roles? A role is separate from a device. A device can take on many different roles in an application.

**Comment by mmoskal** [comment]
Currently, each brain stores a mapping from device-id to "name" (which we renamed to "role").

The idea is that the mapping should be from "role" to device-id.

**Comment by jamesadevine** [comment]
Yes, agree with that! Thanks for clarifying @mmoskal :smile:
