### ISSUE TITLE
Use different syntax for default values than for structure

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#340]
The structure ({...}) syntax is used for different purposes. First, to give a register a structured value (over multiple lines):
```
    ro acceleration @ 0x182 {
        x: i16.16 m/s2
        y: i16.16 m/s2
        z: i16.16 m/s2
    }
```
Second, to provide a variety of (fixed) constant values that define acceptable ranges for a value, as for the delay field below:
```
    command launch @ 0x80 {
        launch_secret_code: u32
        delay: u32 ms { absolute_min = 1000, absolute_max = 3_600_000 }
    }
```
I would suggest we use a different syntax for the latter case, such as below:
```
    command launch @ 0x80 {
        launch_secret_code: u32
        delay: u32 ms with absolute_min = 1000, absolute_max = 3_600_000
    }
```

**Comment by tballmsft** [comment]
A related comment. In the case of a register R with a field F where the field F has an associated value D, we need two dereferences to refer to D:
```
    R.F.D
```
So, this is perhaps an argument for keeping the { } syntax for both fields and associated values.

**Comment by mmoskal** [comment]
let's keep it then
