### ISSUE TITLE
Servo simulator does not respect angle range.

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#347]
**Describe the bug**
The servo sim only appears to allow control over the range -90 to +90. When hardware is configured to operate in the range 0  to +180, the similator restricts operation to 0 to +90
![Screenshot 2021-04-16 at 13 27 15](https://user-images.githubusercontent.com/4742697/115024047-77243f00-9eb7-11eb-8c6d-1c9dcf4e7c0c.png)

**Comment by pelikhan** [comment]
Fixed.

**Comment by pelikhan** [comment]
Heads: I changed the register code for min_angle and max_angle, so you'll have to rebuild your firmware. @jamesadevine
