### ISSUE TITLE
service_command uses big endian order

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#349]
**Describe the bug**
In packet inspector (when you click on packet in the history window) the fields are displayed as sequences of bytes, which seems to imply big endian order. The actual order is little endian. I think we can leave device_identifier as is (though we could also reverse it so it matches uint64), but we do need to swap bytes of service_command and CRC.

<img width="729" alt="Screen Shot 2021-04-20 at 2 41 46 PM" src="https://user-images.githubusercontent.com/10673976/115467661-294e6480-a232-11eb-88fe-00d9af06b2be.png">

**Comment by pelikhan** [comment]
Added a "value" column to show unpacked value.
![image](https://user-images.githubusercontent.com/4175913/115557573-adbada80-a266-11eb-9bcc-c40c07daa5bd.png)
