### ISSUE TITLE
read only registers look editable

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#350]
**Describe the bug**
For example color register on LED (single) looks editable, but it can't be edited.

**Comment by pelikhan** [comment]
In which view in particular?

**Comment by mmoskal** [comment]
https://microsoft.github.io/jacdac-docs/services/led/playground/

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/jacdac-docs/commit/72396c704f931e1778d5c8062998a830b84d2a8f
