### ISSUE TITLE
Version number on jacdac website

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#353]
I'd like to know if my browser has the latest version of the website. This is useful for validating that fixes have been deployed and are working as expected. Could we please have a version number and a way of checking what the latest version number is? 
- [x] force reload when update is downloaded
- [x] currently service worker checks for updates daily, force check on every nav
- [x] display link to commit sha in footer

**Comment by pelikhan** [comment]
See short sha in footer 
![image](https://user-images.githubusercontent.com/4175913/115776817-68cb9c80-a369-11eb-9ac7-10af539fb7c1.png)
