### ISSUE TITLE
panic on micro:bit not detected

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#367]
Basically, put the micro:bit in panic and you won't notice anything on the jacdac browser side. There does not seem to be any error raised over the webusb transport.

Repro:
flash a new jacdac program on micro:bit v2
go to https://microsoft.github.io/jacdac-docs/tools/settings
click on "clear" a few times
the device will crash with 921
nothing detected on the web site

**Comment by mmoskal** [comment]
I guess we should update the protocol code on the website to detect that micro:bit is not picking up (or sending) any packets. If it doesn't for a second or two, we should assume it paniced. We talk to it via debugger interface, so all we can tell is that it's not modifying the transport buffers. Same would happen in hard fault (though possibly we could detect hard fault).

**Comment by jamesadevine** [comment]
watch point on target_panic?

**Comment by mmoskal** [comment]
imho too complicated - just look for timeouts - bullet proof method

**Comment by mmoskal** [comment]
I also don't know the address of target_panic(); it could be also that program gets stuck somewhere else.

**Comment by jamesadevine** [comment]
makes sense :smile:
