### ISSUE TITLE
micro:bit disappears from jacdac dashboard

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#372]
Repro:
- load the micro:bit program onto V2 from pxt-jacadc
- connect to webusb and bring up micro:bit simulator in jacdac-docs dashboard
- wait a few minutes, navigate away from dashboard in same tab, and then back 
- see that micro:bit simulator has disappeared from dashboard, though it says still connected via USB

**Comment by tballmsft** [comment]
navigate within the app, away from the dashboard, then back to the dashboard

**Comment by pelikhan** [comment]
I can't repro.

**Comment by pelikhan** [comment]
@mmoskal i think this is related to the panic bug where the micro:bit stops sending packets but daplink is still up and running. Is this something i should be fixing at the jacdac-ts level?

**Comment by pelikhan** [comment]
This should be fixed by https://github.com/microsoft/jacdac-docs/commit/fbba063552860cd2755cda4fa753d153aae86698
