### ISSUE TITLE
start of "jacdac vm"

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#374]
- [x] make the vmrunner async in order to properly handle errors
- [x] create VMRunnerException class
- [x] track the blocky ids
- [x] what happens if service is no longer available?
- [x] add support for if-then-else
- [x] shadow blocks
- [x] support for watch block
- [x] errors into program structure
- [x] add support for event fields (named by role.event.field)
- [ ] add support for state variables (think about a type system for tracking units)
- [x] start adding test programs
- [ ] need retry logic for dealing with undefined values and devices going away
- [x] debugger interface (role->service, register->value, handler->block_ids)
- [ ] document the language
- [ ] efficient (bytecode) representation of program and service (slice)
- [ ] compilation to bytecode
- [ ] Jacdac service for VM
- [x] raise CHANGE on any VM state change
- [x] commands to send "commands"
- [x] static role (id,serviceName) for type checking and compilation
- [x] harden the evaluation of expressions in the face of failed register reads (wait)
- [x] commands to read/write local state
- [x] commands to read/write registers 
- [x] waitEvent command
- [x] waitExpression command
- [x] parser for language

**Comment by tballmsft** [comment]
The JD-VM runs a program, which is a set of handlers. Each handler is of the form
•	wait on event/condition, followed by a
•	sequence of guarded commands – the sequence is executed atomically (though may suspend if it contains a wait)
After a handler finishes executing, it restarts (there is an implicit event loop around all the handlers, as usual). 
 
We will have a small key-value store to keep program state (perhaps we will have the ability to store lists of values as well as basic values) across the handler executions.
 
Commands can talk to JD services (probably via roles), as well as read/write program state, and wait on events/expressions. Any command can be guarded by an expression, for conditional execution.
 
Expressions can be against service registers (as in the test case) and program state.

**Comment by pelikhan** [comment]
The JD-VW should itself be a jacdac service.

**Comment by finneyj** [comment]
yup - thanks @tballmsft!

**Comment by tballmsft** [comment]
BTW, this little language is Turing complete, as long as key-value store can grow..., but each handler is loop-free. There is an implicit event loop around the whole thing, as usual.

**Comment by pelikhan** [comment]
@tballmsft maybe we should move this to the discussions section (to have better discussions support)

**Comment by tballmsft** [comment]
https://github.com/microsoft/jacdac/discussions/379

**Comment by tballmsft** [comment]
Peli says.

As discussed, let's decouple the role manager from the VM by introduction some kind of "service resolver" service that takes care of mapping names to device/service index (role maanger is an example of this).
For scripting purposes in the browser, a user should be able to write things like this (all match case insensitive)

- [ ] ``up`` , match any service that exposes a up event and use it (note: let's make sure our spec has unique event names)
- [ ] ``button.up``, match any button use up event
- [ ] ``A.up`` match any service whose instance name is "A" and pick the up event
- [ ] ``deviceid|shortid.up`` precise match on device id + find any event called up
- [ ] ``button.B.up``, match any button service, service instance "B", use up event

**Comment by mmoskal** [comment]
if you ever want to run these things on devices, you will need to know the type of service; for that you'll want to have something like:

```
service A : button
service B : button
service light : lightlevel

when (A.up) { ... }
```

Which is much like the role manager.

This will let you compile `A.up` into register number and format, without having to have access to all specifications on device.

I honestly don't see what's wrong with role manager, other than UI.

**Comment by tballmsft** [comment]
Exactly, Michal. That is next on my plate. I already have service-based type checking working for test language. I will reuse that to statically check the VM language.

**Comment by pelikhan** [comment]
we need a browser impl of the role manager to make this work.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by tballmsft** [comment]
There can be different policies for resolving services.

**Comment by mmoskal** [comment]
We may want to extend role manager to take more hints, which some implementations would take into account when auto-binding. However, I think we should stick to it as the sole mechanism for determining which device is which.

**Comment by tballmsft** [comment]
I agree - let's discuss hints.
