### ISSUE TITLE
Playground not working for HID Keyboard

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#380]
**Describe the bug**
I am using the playground page for HID Keyboard. I want to press the character "a" without any modifiers. The playground requires a modifier to be sent and gives an error when no modifier is specified and "Key" is clicked:

![Screenshot 2021-05-12 at 11 09 06](https://user-images.githubusercontent.com/4742697/117958069-91183c80-b312-11eb-86a0-4298aa0b990c.png)

```
TypeError: Cannot read property 'length' of undefined
    at packArguments (command.ts:57)
```

I next tried to specify a modifier but when I did this all the modifier options appeared in the modifier input box:

![Screenshot 2021-05-12 at 11 06 28](https://user-images.githubusercontent.com/4742697/117958293-c91f7f80-b312-11eb-8e5d-0dfd25015990.png)

**Comment by jamesadevine** [comment]
Why do modifier values start at 0xeY?

**Comment by pelikhan** [comment]
Probably want to buidl a custom UI for it.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
