### ISSUE TITLE
HID keyboard desired key mappings

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#383]
- [x] alt+tab
- [x] cmd + tab
- [x] cmd + tilde
- [x] ctrl + letter
- [x] cmd + letter
- [x] ctrl + shift + letter
- [x] cmd + shift + letter
- [x] function keys

**Comment by pelikhan** [comment]
Can we get a padauk button with a keyboard cap footprint?

**Comment by jamesadevine** [comment]
Other than time, I don't see any reason why not!

**Comment by pelikhan** [comment]
I think I'm covered now.

**Comment by jamesadevine** [comment]
awesome! Thanks peli...
