### ISSUE TITLE
pxt-jacdac: Support event parameters

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#389]
**Describe the bug**
The up button event has a time parameter but the button client does not have the ability to access the time parameter:

https://github.com/microsoft/pxt-jacdac/blob/master/button/client.g.ts#L72

Same with hold: 

https://github.com/microsoft/pxt-jacdac/blob/master/button/client.g.ts#L84

Presumably the handler should just have a time parameter passed to it...

**Comment by mmoskal** [comment]
we could pass the event packet to avoid polymorphic arguments

**Comment by pelikhan** [comment]
yeah that's probably best but I need to make sure it won't confuse our block wrapper.

**Comment by tballmsft** [comment]
@pelikhan - close this?

**Comment by pelikhan** [comment]
not implemented yet
