### ISSUE TITLE
VM should catch all exception and expose a error event

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#395]
If anything decides to crash on the VM, we should not crash the UI.

**Comment by tballmsft** [comment]
what do mean "expose an error event"? Do you have an example?

**Comment by pelikhan** [comment]
use 
```
this.emit(ERROR, e)
```
to emit the error and the UI will handle it. Either show in UI or using AppContext setError.

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac-docs/blob/ff0a2ad0b2fee956c34248c52334eedb82a17342/src/components/vm/VmEditor.tsx#L66

**Comment by tballmsft** [comment]
@pelikhan - catch exceptions and expose error events everywhere now, can you please do UI work?

**Comment by pelikhan** [comment]
Yup will do. Are those error surfaced on the vmrunner instance?

**Comment by tballmsft** [comment]
yes
