### ISSUE TITLE
led simulator doesn't update promptly

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#398]

**Comment by pelikhan** [comment]
You need to issue a register get command after animation to reflect the animation in the UI.

**Comment by pelikhan** [comment]
In general, we should specify this kind of data dependencies in the spec.

**Comment by tballmsft** [comment]
I don't understand why the reception of a command at the JDService for the LED doesn't raise a CHANGE event that will cause the UI of the LED to update.

**Comment by pelikhan** [comment]
Nothing in the spec says that it should send a packet. The UI is listening to packets.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mmoskal** [comment]
I think that could happen client-side - when the client sees packets being directed at a service (either from itself or from elsewhere), it could rise some event

**Comment by pelikhan** [comment]
not clear what the strategy here since some commands have long lasting effects

**Comment by pelikhan** [comment]
This where we need richer models for our services. Otherwise, every client will have different heursitics.

**Comment by tballmsft** [comment]
I am confused why this isn't a policy specific to the LED client, as Michael suggested.
