### ISSUE TITLE
VM: don't leak promised

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#405]
Currently the VM runs synchronously, but really it is async.

We're leaking promises whenever we do an operation that sends a packet or requires an ack. For example, this may fail

https://github.com/microsoft/jacdac-ts/blob/main/src/vm/environment.ts#L87

**Comment by tballmsft** [comment]
@pelikhan - I am a promise noob - what is the pattern to deal with this?

**Comment by pelikhan** [comment]
Entire VM has to be async.

**Comment by tballmsft** [comment]
OK. Maybe we can do pair programming on that?
