### ISSUE TITLE
Blockly: register_change_by should support negative values

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#406]
The title says it all - the field editor doesn't allow specification of negative values in register_change.

**Comment by mmoskal** [comment]
I think it's absolute value delta, so if you set it to 10, and it last triggered at 27 then it will next trigger at 17 or 37. Is that right @pelikhan ?

**Comment by pelikhan** [comment]
Yes it's absolute delta w.r.t. to the value at the last event.

**Comment by tballmsft** [comment]
I expect it to be sign sensitive.

**Comment by tballmsft** [comment]
Maybe we need an accessor for that?

**Comment by pelikhan** [comment]
Use can have a local variable.
