### ISSUE TITLE
PR feature in service editor hard to use

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#409]
**Describe the bug**
I found it difficult to work out how to get the site to make a pull request to the service specification repo. Firstly, it asked for me to generate a personal access token which seemed a bit weird... After I'd done that, it then asked for organisation access, which was hard to work out what I was actually supposed to do (I had to grant SSO access from the PAT page). Then, after the PAT had access, the repository was not found! 😢 

I figured out I had to give the token both access to the "org" and to "repo"... Seems a bit risky to me... Can't we just redirect to github with the complete PR text filled out?

**Comment by pelikhan** [comment]
Unfortunately not. And yes Microsoft has enabled SSO on tokens as well.

**Comment by mmoskal** [comment]
We should see how it works from non-MS account
