### ISSUE TITLE
two button blocks doesn't create new simulator

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#415]
I created a second button variable (b2) and dragged a second button simulator out, but it didn't create a new simulator. It was the same as "button 1"'s simulator (MZ57).  My expectation is to get a new button simulator. 

![image](https://user-images.githubusercontent.com/10767146/120093382-ba84e680-c0ce-11eb-95fb-61b51c5f6756.png)

**Comment by pelikhan** [comment]
Not implemented yet, it vaporware

________________________________
