### ISSUE TITLE
watch without expression should be no-op

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#421]
All "meta" commands should be ignored if not well configured.

e.g. no warning here.
![image](https://user-images.githubusercontent.com/4175913/120671096-e7762800-c445-11eb-8cb4-878b883118f2.png)

**Comment by tballmsft** [comment]
Both Watch and If-Then-Else are translated to NOP if expression is missing. Probably want a different treatment for If-Then-Else
