### ISSUE TITLE
crash on watch event

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#425]
![image](https://user-images.githubusercontent.com/4175913/120678461-f3b1b380-c44c-11eb-9aad-b92d89f24aad.png)

![image](https://user-images.githubusercontent.com/4175913/120678497-fd3b1b80-c44c-11eb-9e36-4ec1e3c7d236.png)

**Comment by tballmsft** [comment]
Fixed in https://github.com/microsoft/jacdac-docs/commit/48f36b59b3e06eb6bbc0379dc9f987e00821bd69
