### ISSUE TITLE
robust handling of roles in the VM

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#426]
register read/write failing during handler

**Comment by pelikhan** [comment]
I think we just want to handle read/write. User may have logic to handle missing roles.

**Comment by tballmsft** [comment]
@pelikhan, @mmoskal - the question here is what we should do on failure of an instruction (because of absence of a role, or bus problem). Options
- the instruction is treated as a NOP, and execution of the handler continues.
- the handler is aborted and execution starts from beginning

Note that if a handler works with two roles, one of which is not present and we keep executing the handler partially, at some point the state could get very much out of sync.  So there is also the question of what to do with a handler that has failed. We could
1. retire the handler from execution and restart when its roles become available
2. retire the handler from execution for a period of time and then restart
I prefer option 1. Should we do this whenever a handler fails? Or must it fail N times (for small N).

**Comment by tballmsft** [comment]
fixed by https://github.com/microsoft/jacdac-ts/commit/f0e7ba6e242308296f97c12f565c5228e9e1afc4.

I only restart a handler when all its roles are bound.
