### ISSUE TITLE
implement connection block

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#428]
![image](https://user-images.githubusercontent.com/4175913/120683743-da136a80-c452-11eb-8c51-ced96739e689.png)

**Comment by tballmsft** [comment]
@pelikhan - question on the semantics here.  This should obviously fire whenever the role transitions from "disconnected" to "connected. But on program start, it should also fire if the button is already connected. Do you agree?

**Comment by pelikhan** [comment]
Correct, it should fire once if the role is already connected.

**Comment by pelikhan** [comment]
This should be done in the servicesdsl

**Comment by tballmsft** [comment]
done
