### ISSUE TITLE
too many events from single button.up event

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#430]
On a single button press in simulator, I get about 9 button.up events, spread over time, which causes the VM to be invoked three times (it used to be invoked just once per button press).

**Comment by pelikhan** [comment]
No repro here. See in the inspect block, the number of events is correct.
![Animation](https://user-images.githubusercontent.com/4175913/120744880-d7476280-c4b0-11eb-9f6f-eefbf4e95649.gif)

**Comment by pelikhan** [comment]
i need a repro @tballmsft

**Comment by tballmsft** [comment]
Yeah, I think it's my problem...
