### ISSUE TITLE
runner status does not reflect internal VM state

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#434]
In the gif below, you can see that the VM is running, however the "play" button is showing that the UI thinks it is stopped.
![statusbutton](https://user-images.githubusercontent.com/4175913/120825097-e5779c00-c50d-11eb-9498-7d0b1ede47fb.gif)

**Comment by tballmsft** [comment]
should be fixed by https://github.com/microsoft/jacdac-ts/commit/f0e7ba6e242308296f97c12f565c5228e9e1afc4
