### ISSUE TITLE
yarn failing

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#435]
$ yarn
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ yarn blocklymedia && cd jacdac-ts && yarn install --frozen-lockfile && yarn dist
yarn run v1.22.10
$ mkdir -p static/blockly && cp -r -f node_modules/blockly/media static/blockly
The syntax of the command is incorrect.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by mmoskal** [comment]
@pelikhan do we support running yarn on plain Windows without Unix tools?

**Comment by tballmsft** [comment]
I am running in git bash

**Comment by mmoskal** [comment]
I'm pretty sure `The syntax of the command is incorrect.` is from DOS `mkdir`. Maybe that's what node calls by default.

**Comment by pelikhan** [comment]
Removed command.
