### ISSUE TITLE
runner will not start

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#437]
It seems that the runner will not start on error until the program is modified.
![start](https://user-images.githubusercontent.com/4175913/120836908-f67ada00-c51a-11eb-9f81-c7c3005867d3.gif)

**Comment by tballmsft** [comment]
fixed by https://github.com/microsoft/jacdac-ts/commit/f0e7ba6e242308296f97c12f565c5228e9e1afc4
