### ISSUE TITLE
support for variables in vm

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#439]
Ability to create/update number/string/boolean variables
Query state of variable + change events to reflect values in UI.

**Comment by tballmsft** [comment]
@pelikhan, @mmoskal: I think that VM variables should be statically typed since we are going to very low resource MCUs.

**Comment by pelikhan** [comment]
In blockly, it's boolean, number or string, which should be inferred from the first use. I would argue that we don't need to have diferrent numberic types here. We have precise number types in jacdac to minimize packets on the bus, but at the VM level, we should only support a float.

**Comment by tballmsft** [comment]
OK. I will set type based on first use and then raise an error if there is a dynamic type error.
