### ISSUE TITLE
Cannot set single RGB LED colour from dashboard

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#443]
**Describe the bug**

Clicking on the different colours or editing the RGB value fields should update the colour of the physical LED, but it currently does not. From the packet inspector, it looks like packets are not being sent. 

![image](https://user-images.githubusercontent.com/4742697/121022512-4e734400-c79a-11eb-80f9-10311d7c60e3.png)

**Comment by pelikhan** [comment]
The VM needs support for 
- [ ] commands
- [ ] compiling expression of custom blocks as defined in https://github.com/microsoft/jacdac-docs/blob/main/src/components/vm/useToolbox.ts#L424

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/jacdac-docs/commit/3eaac24589ae23c309c1ecf66fa123330b0dbf31
