### ISSUE TITLE
Accelerometer twin does not resume updating after device reset.

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#447]
**Describe the bug**
Accelerometer twin stops updating and does not resume when a device resets.

<img width="960" alt="Screenshot 2021-06-07 at 21 52 07" src="https://user-images.githubusercontent.com/4742697/121086125-adf14400-c7da-11eb-9758-eb849d3f39b5.png">

**Comment by pelikhan** [comment]
Is the hardware device still sending updates?

**Comment by jamesadevine** [comment]
Probably not. This seems to happen sporadically, so I'll close for now and re-open if it crops up again.
