### ISSUE TITLE
VM runs in an infinite loop

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#451]
The VM currently runs in the same page as the UI and it seems to enter infinite loops. This program locks up the entire page.

![image](https://user-images.githubusercontent.com/4175913/121288506-544f4f00-c898-11eb-834b-ade0542d6448.png)

**Comment by pelikhan** [comment]
This happens as soon as the servo role is started.

**Comment by tballmsft** [comment]
oh yeah, i was just thinking about that case...

**Comment by tballmsft** [comment]
what if you remove the wait?

**Comment by tballmsft** [comment]
fixed
