### ISSUE TITLE
Stepper does not go over event

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#456]
![stepevent](https://user-images.githubusercontent.com/4175913/121390899-acbb3680-c902-11eb-8748-9568016ad7bc.gif)

**Comment by pelikhan** [comment]
After that, the runtime is deadlocked.

**Comment by tballmsft** [comment]
@pelikhan, in particular, this is only for "repeat" events? What about "on button pressed"?

**Comment by tballmsft** [comment]
fixed
