### ISSUE TITLE
block "change ... by" not support

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#465]
Blockly has a built-in block to increment.

**Comment by tballmsft** [comment]
@pelikhan - did you add plumbing for that?

**Comment by tballmsft** [comment]
I see it as "math_change". Is that the correct category. It's really difficult to know what type I should match on with Blockly.

**Comment by pelikhan** [comment]
Yes blockly is fun.

**Comment by tballmsft** [comment]
So what do I match on ?

**Comment by pelikhan** [comment]
On he block type?

________________________________
