### ISSUE TITLE
variable not initialized with default values

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#466]
In blockly, assume that the user does not initlaize variables explicitely.

![image](https://user-images.githubusercontent.com/4175913/121613913-6a811a80-ca12-11eb-93c4-08bcda4413a4.png)

**Comment by tballmsft** [comment]
@pelikhan: how can we have a default value if we don't know the type?

**Comment by pelikhan** [comment]
The problem here is that I don't have a start block. In this case, you could infer the type from the + operator, init to 0.
