### ISSUE TITLE
Support for querying variable values in runner

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#468]
To support a view of all global variable values, need to be able to query state.

https://github.com/microsoft/jacdac-ts/commit/262a8d6965ec2c1df70e472f97c52dbb733ba436#r52040796

Used in variables block

![image](https://user-images.githubusercontent.com/4175913/121706359-698bcf80-ca8a-11eb-9cf2-1beeb60982eb.png)

**Comment by tballmsft** [comment]
add requested code.
