### ISSUE TITLE
refreshRegistersAsync called in tight loop and killing perf

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#469]
![image](https://user-images.githubusercontent.com/4175913/121733903-eded4b00-caa8-11eb-99d5-5af8a95bf556.png)

Looks like we are calling this in a tight loop.

**Comment by pelikhan** [comment]
![refreshregisters](https://user-images.githubusercontent.com/4175913/121736030-d95e8200-caab-11eb-92e8-2dfa03666123.gif)

**Comment by tballmsft** [comment]
fixed
