### ISSUE TITLE
Status for services? stable/unstable

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#47]
Should we have a formal flag for service specifiaction that indicate the level of maturity of the specification. Maybe something like

```
    status: dev <-- still under development
    status: stable <-- no more changes allowed
```

**Comment by mmoskal** [comment]
node.js uses:
* experimental
* stable
* deprecated

https://nodejs.org/api/documentation.html#documentation_stability_index

Also, I think it should be fine to add optional packets to stable.

**Comment by pelikhan** [comment]
yes nice. node.js uses semantic versioning; what is the overall versioning story for our services?

**Comment by mmoskal** [comment]
no versioning; if there are any breaking changes (after reaching stable), we need to iterate service class identifier

**Comment by pelikhan** [comment]
@tballmsft we should write down the "versioning" policy in the spec. specifically that when a service hits stable; any change beyond adding optional packets basically generates a new service id.

**Comment by pelikhan** [comment]
Added in rendering.
