### ISSUE TITLE
role manager binding algorithm should be specified

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#491]
and have a consistent behavior on all platforms.

**Comment by tballmsft** [comment]
Agreed. We need to talk about this. Role management can be easier with UI in web browser. Maybe a configuration gets created and installed on brain? But what happens when we plug/unplug and we are no longer connect to web browser? What are failure models?

**Comment by mmoskal** [comment]
There should definitely be logic on the brain to re-assign roles, even if the assignment isn't optimal (and there is right now, in MakeCode). I can imagine different UIs for fixing up assignments - web browser, arcade device, etc.

**Comment by tballmsft** [comment]
@mmoskal - can you document this?
