### ISSUE TITLE
allow editor to create a service implementation

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#496]
- [x] separate category/DSL for servers/adapters
- [X] event generation
- [x] register R/W
- [x] command request
- [x] custom blocks
- [x] refactor (separate DSLs)
- [x] separate roles into client and server roles
- [x] compile to VM 
- [x] update VMenvironment to deal with serverRoles (sendEvent, R/W register/command requests) 
- [x] VM exposes JDServices via a JDDevice
- [x] UI to recognize the JDDevice and spin up twin for it

**Comment by pelikhan** [comment]
- [ ] refactor server role blocks into separate DSL

**Comment by tballmsft** [comment]
Do you mean at the user level, in the ToolBox, as we discussed. refactoring servicesdsl.ts into clientservicesdsl.ts and serverservicesdsl.ts will be a big refactor, as there is a lot of shared code. Can this wait?

**Comment by tballmsft** [comment]
Actually, I found a pretty good refactoring...
