### ISSUE TITLE
Handle arithmetic and logical operations between strings and numbers in table columns

### ISSUE THREAD

**Issue by seankross** [microsoft/jacdac#498]
Right now you can compare strings to numbers. This has some nice features for middle school students (`5 == "5"`) but also some confusing features (`"a" > 5`). Maybe we need two separate blocks.

**Comment by pelikhan** [comment]
We should always seperate strings and number in blocks and avoid relying on --very funky-- JS number -> string conversions. Also, type information allows for better field editors.
