### ISSUE TITLE
role manager should use serviceClass, not serviceShortId

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#502]
ServiceClass is more stable, requires less spec knowledge. Since this change impacts a lot of code you are currently working on, I'm letting you fix that one.

**Comment by tballmsft** [comment]
I really don't see the point of doing this, unless we don't guarantee that shortIds are not unique.

**Comment by pelikhan** [comment]
shortId requires access to the specification, which serviceClass requires zero knowledge. Service class is also easier to use with SRV_* constants generated by the spec tool.

**Comment by tballmsft** [comment]
Fixed in

**Comment by tballmsft** [comment]
fixed
