### ISSUE TITLE
Separate wall clock and simulator time in JDOM

### ISSUE THREAD

**Issue by ducky64** [microsoft/jacdac#506]
To support unit testing, see #505 for the larger context.

## Functional requirements
1. **Fast forward through time**, so test cases don't have to be limited to realtime, and to support tests that take a lot of simulated time (eg, scale of days for a thermometer) but mostly sleep through it
2. **Centralize access to the notion of time, including delays and time-based event scheduling**. We already have `bus.timestamp` which returns the time since the bus started, but everything needs to use that consistently. Required so that fast forwarding behaves properly with simulated devices (and in particular, adapters like the timeout on the button click detector)

### Open questions
- Should this work for physical devices too? How would it work for hybrid tests? Or would hybrid tests be restricted to real time? What would it even mean for a physical device to fast forward?

## Implementation paths
Since JDBus (JDOM) already handles timestamping, it probably makes sense to put this function there.
- Add JDBus.delay(...), which blocks the caller until the elapsed time has passed (either realtime, if in realtime mode, or simulator time).
  - In fast-forwarding (non-real-time mode), time only advances with a JDBus.delay(...). Compute and communication are "free" in terms of time - and timing is exact.
- Add event-based scheduling to JDBus, for use in adapters. For example, `bus.scheduleIn(() => {...}, 250)` to schedule an event in 250 simulator milliseconds.
  - This isn't a true bus function, but JDBus is probably the best place unless we want to introduce a separate class to keep track of time. It wouldn't do much else though.
- Modify JDBus to allow fast-forwarding - probably based on an event queue architecture that doesn't advance simulator time except explicitly.

### Open Questions
- Does having "free" compute and communication cause any problems? Are there any services which depend on those things not being free?
- Does it make sense to separate JDBus into a separate interface, which can be extended by a wall-clock-timed bus and a simulator-timed bus? This seems like the clean OO approach, though is unclear if it's overkill.
- Can regular events (announcements, streaming values) be suppressed - mainly for very long simulator time tests (eg, days)? Would this be an opt-in mechanism, or is this generally safe to do (won't cause wonky side effects)?

**Comment by tballmsft** [comment]
A very good idea. Also super useful for debugging, IMO.

**Comment by pelikhan** [comment]
>  Are there any services which depend on those things not being free?

Not sure what free means.

> Does it make sense to separate JDBus into a separate interface, which can be extended by a wall-clock-timed bus and a simulator-timed bus? This seems like the clean OO approach, though is unclear if it's overkill.

We can do service-oriented architecture/composition here. Added a scheduler class (in scheduler.ts) that allows to redefine setTimeout,setInterval in all bus related functions. ( https://github.com/microsoft/jacdac-ts/blob/main/src/jdom/scheduler.ts ).

> Can regular events (announcements, streaming values) be suppressed - mainly for very long simulator time tests (eg, days)? Would this be an opt-in mechanism, or is this generally safe to do (won't cause wonky side effects)?

This will have wonkey effect. Jacdac expects announcement packets every 500ms, and consider device losts when it misses a few of them.

**Comment by pelikhan** [comment]
> Should this work for physical devices too? 

There might be dragons trying to make this work with **live** physical devices as the firmware running on those does not have the ability to change time. Most firmware are using hardware interupt with fixed timings. I would say this is a non-goal.

However, if we had a recorded trace of a physical device and some kind of wrapper that simulates it in the bus, we could integrate some physical devices in the form of a trace-replay. IMO, this is actually more useful in practice because going throug traces inherently leads to better reproducibility/determinism of tests.

**Comment by pelikhan** [comment]
Jasmine has a mock clock that allows to determinise setTimeout, setInterval. https://jasmine.github.io/api/edge/Clock.html ​. Might be able to build on top of it.

**Comment by tballmsft** [comment]
Agree that it should be a non-goal to change time on physical devices. Don't try to mess with reality.

**Comment by ducky64** [comment]
I started looking through some of the JDOM code, and it looks like there might be some use of non-blocking async code (example: [serviceprovider.ts:127](https://github.com/microsoft/jacdac-ts/blob/main/src/jdom/serviceprovider.ts#L127)). I haven't tried implementing fast-forward yet (and it's not immediately on the docket) but could this be an issue? Is there a fix that doesn't require catching all the instances of this, or is this go in and refactor all the async stuff to be blocking, so we make sure to drain the event queue before advancing time?

(I might also be misunderstanding the code)

**Comment by pelikhan** [comment]
We would have to catch and inspect every instance to see if the fix is suitable and does not kill perf.

**Comment by ducky64** [comment]
Started to experiment on the [fast-forward branch on jacdac-ts](https://github.com/microsoft/jacdac-ts/tree/fast-forward). Initial results are promising, even with a bunch of printfs and 🗑🔥-worthy algorithms / data structures. the basic button test case runs in 50ms, and the worst one runs in 842 ms (wall clock times; down from 581ms and 2672ms). No changes were made other than creating a new scheduler in scheduler.ts, which de-schedules itself every loop with an await setTimeout - and it's unclear how necessary that is because the test runner can direct the scheduler to run until some condition.

**Comment by ducky64** [comment]
The right solution might be to have the scheduler handle testdriver events and simulated events concurrently but differently. Scheduler fires testdriver events are preconditions are satisfied, and keeps running until there are no testdriver events. When there are testdriver events pending, there can be a timeout (eg, 5s simulated time or so before the promise is rejected), but otherwise simulated time advances as fast as possible.
