### ISSUE TITLE
Indicate a device has not been seen after 1.5 seconds

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#507]
We have some > 10 second delay in the jacdac stack before a device is considered removed from the bus. I understand this was because devices that randomly reset would disrupt, say, the dashboard experience.

It would be great if we could indicate that a device has not been seen in the dashboard before the >10 second delay to keep the plug and play experience. Right now it seems like we have buggy code that does not detect a device has been unplugged for some time.

Feedback via @mgabrieledamone

**Comment by pelikhan** [comment]
We have the concept of lost device, which is before disconnected. It is visible in the dom tree but not yet in the dashboard.

**Comment by jamesadevine** [comment]
I can make a PR?

**Comment by pelikhan** [comment]
Sure you probably want to update DashboardDevice.tsx
________________________________

**Comment by jamesadevine** [comment]
PR Merged https://github.com/microsoft/jacdac-docs/pull/68
