### ISSUE TITLE
Category names for server don't read well.

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#509]
IMO add a label on top of the group and drop the ":S" which  is cryptic.
![image](https://user-images.githubusercontent.com/4175913/124346473-4fec2c80-dbdf-11eb-9c7f-7364065faf15.png)

**Comment by tballmsft** [comment]
<LabelDefinition> doesn't work at the top

**Comment by tballmsft** [comment]
See line 208 of serverservicesdsl.ts

```
        return [
            <SeparatorDefinition>{
                kind: "sep",
            },
            <LabelDefinition>{
                kind: "label",
                text: "Servers",
            },
            ...serverServicesCategories,
        ]
    }
```

**Comment by pelikhan** [comment]
Hummm blocky may not support those at top level then.
________________________________
