### ISSUE TITLE
Server blocks should use different colors from client blocks

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#512]
Things can get confusing.
![image](https://user-images.githubusercontent.com/4175913/124374876-f9debe00-dc9e-11eb-983b-6c072e9ae883.png)

Maybe: use different colors for the server categories, prepend all server block with "server" to emphasize they are the server part.

**Comment by pelikhan** [comment]
We could move all server blocks under a "servers" category.

**Comment by tballmsft** [comment]
Yes, I moved all server blocks under a single category. There's still the question of colors.

**Comment by pelikhan** [comment]
You should use nested categories under server. Putting everything under the same category can create performance issues once the number of blocks increseases.
![image](https://user-images.githubusercontent.com/4175913/125328600-cfe36680-e344-11eb-823c-89dd4e2b43ac.png)

**Comment by tballmsft** [comment]
does your data structure support that?

**Comment by pelikhan** [comment]
You should be able to change the color field
________________________________

**Comment by tballmsft** [comment]
I was talking about "nested categories".

**Comment by pelikhan** [comment]
I added those.
________________________________
