### ISSUE TITLE
Server simulator leaks into devices, cannot be stopped

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#513]
A simulator is started for servers and I cannot stop it:

- my server block is disbled
- the VM is not running

![image](https://user-images.githubusercontent.com/4175913/124374927-6b1e7100-dc9f-11eb-8e2e-2be4d3204061.png)

The simulator shows up under devices instead of simulator, so there is no close icon on it.

![image](https://user-images.githubusercontent.com/4175913/124374950-8f7a4d80-dc9f-11eb-8c4e-015313553ffa.png)

**Comment by tballmsft** [comment]
yeah, I still don't understand why it shows up as a physical device.

**Comment by pelikhan** [comment]
The why is here: https://github.com/microsoft/jacdac-docs/blob/main/src/components/dashboard/Dashboard.tsx#L85 . If there is a service provider on the bus for the given device id, it is treated as a simulator.

**Comment by tballmsft** [comment]
thanks

**Comment by tballmsft** [comment]
But there is another path in which this leak is happening, since Dashboard.tsx is not active when the serviceProvider the VM spins up is added. Somehow, it's leaking via another path. Ideas?

**Comment by pelikhan** [comment]
Hack stack, needle, go!

(Add logging to the locations you start a service producer to trap the leak)

**Comment by tballmsft** [comment]
yep....

**Comment by tballmsft** [comment]
fixed
