### ISSUE TITLE
No visual indication of servers

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#514]
Code users server block and simulator spins up since I can see the (1) indicator on the dashboard. However, there is no support display that simulator in the bloc editor.

![image](https://user-images.githubusercontent.com/4175913/124375010-ef70f400-dc9f-11eb-8d06-70de82eba98a.png)

**Comment by tballmsft** [comment]
yes, still working on getting server to appear via role manager...

**Comment by tballmsft** [comment]
fixed
