### ISSUE TITLE
VM servers reset many times

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#515]
If you switch between the bloc editor and the dashboard, you'll notice that the VM is restarting many times. At least, the device restarted popup shows up 5,6 times.

React does not batch updates so this maybe be due to multiple render of react that also regenerate the VM, regardless something is up.

![2021-07-04 08 20 06](https://user-images.githubusercontent.com/4175913/124375166-02d08f00-dca1-11eb-8826-cd36e6f58f33.gif)

**Comment by tballmsft** [comment]
fixed
