### ISSUE TITLE
inconsistent naming of deviceIdentifier

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#517]
**Describe the bug**
In JDOM, JDDevice has a field called "deviceId". JDService and Packet have a field called deviceIdentifier. We should pick one!

**Comment by pelikhan** [comment]
248 hits for deviceId vs 43 for deviceIdentifiers, looks like deviceId wins.

**Comment by pelikhan** [comment]
We need to wait for big PRs to come in to address this or it'll be merge fest.
