### ISSUE TITLE
testing of VM programs

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#520]
- [ ] save VMProgram as json file
- [ ] load, run and test VMProgram
- [ ] VMProgram as tester of VMProgram

**Comment by pelikhan** [comment]
I am working on the file load/save stuff
________________________________
From: Tom Ball ***@***.***>
Sent: Thursday, July 8, 2021 9:08:08 PM
To: microsoft/jacdac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/jacdac] testing of VM programs (#520)


  *    save VMProgram as json file
  *    load, run and test VMProgram
  *    VMProgram as tester of VMProgram

**Comment by tballmsft** [comment]
Cool.

**Comment by tballmsft** [comment]
I will look at the test DSL
