### ISSUE TITLE
Jacdac website resetting devices.

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#521]
**Describe the bug**
I _think_ the jacdac website is still resetting devices every so often. When the website is not connected to the bus, no devices reset, only when the website is connected do modules reset. In particular the rotary control module.

**Comment by pelikhan** [comment]
We do have a pulse check with the transport that sniffs if we haven't received any packet from a device. Could you paste the js console output when you have a repro? How should i test this?

**Comment by jamesadevine** [comment]
I suspect this is more likely an issue with USB on the NRF Brain...

The minimal setup I have is a rotary control and either a jacdapter + micro:bit, or the NRFBrain. Leave it connected to the website for a couple of minutes and the rotary control will reset. This is probably down to the reset_in packet not be sent on the bus by the NRFBrain?

**Comment by pelikhan** [comment]
But the reset_in stuff should really only be used by actuators, not the rotatry encoder? Is this the padauk or stm32x0 version?

Browsers have been more aggressive about shutting down inactive browser pages so it might be the case that we are being "deactivated".

**Comment by jamesadevine** [comment]
STM32x0 rotary encoder. I think I kept the rotary control in the foreground...

**Comment by pelikhan** [comment]
try to record a trace and attach it to the bug


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by jamesadevine** [comment]
[trace.jd.txt](https://github.com/microsoft/jacdac/files/6808055/trace.jd.txt)

**Comment by pelikhan** [comment]
I think it's more of a case of the firmware crashing. Here are the last breath of the device before reset:
![image](https://user-images.githubusercontent.com/4175913/125439568-a3ed4af2-dbe2-49e0-a1db-29e2c87e183b.png)

I need to improve trace analysis mode; it's mixed up with the self device packets which does not help.
