### ISSUE TITLE
Rotary encoder SPINNING BY ITSLEF and reaching crazy high numbers

### ISSUE THREAD

**Issue by mgabrieledamone** [microsoft/jacdac#523]
**Describe the bug**
Every time I start the rotary encoder on the dashboard, as soon as I start moving the slider it reaches very high numbers. Occasionally it starts spinning by itself for 15-30 seconds no stop. 

**To Reproduce**
1. Go to 'https://microsoft.github.io/jacdac-docs/dashboard/'
2. Click on 'Start simulator'
3. Scroll down to 'Rotary encoder'

**Expected behavior**
The number should increase slowly as I move the slider and I assume it shouldn't be spinning. 

**Screenshots**
![image](https://user-images.githubusercontent.com/71759622/125339491-41bdaf00-e349-11eb-8719-38e842c0865a.png)
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pelikhan** [comment]
but it looks so cool! :)
![2021-07-12 21 08 15](https://user-images.githubusercontent.com/4175913/125342608-5f911100-e355-11eb-827b-a7d4a4e5cdac.gif)

**Comment by pelikhan** [comment]
Improved by https://github.com/microsoft/jacdac-docs/commit/c774a04663a8ebd5d339b557ce613f649dfcf62c . Reopen if this is not good enough.
