### ISSUE TITLE
Button state aria announcement

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#524]
**Describe the bug**

Accessibility report submitted by user:
> I was able to hear NVDA’s announcements saying “button down” and “button up” after a little bit of trial and error. The ARIA announcements convey the state of the button, but do not convey which button the update is corresponding to. An easy fix for this would be to modify these aria announcements such that the button name is announced; e.g. “button A down” and “button A up”. Further, I hear NVDA announcing each state 2 times e.g. “button down button down” is announced when I press the button. At first, I assumed this could be due to multiple events firing (I recall similar behavior when I was trying to understand keydown events in the past) so I tested this assumption by pressing and holding the button on the Microbit. I however still hear the announcement only twice so I am not sure what is causing the issue.

**Comment by pelikhan** [comment]
Fixing double read from NVDA
