### ISSUE TITLE
Accessible LED display simulator state

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#525]
**Describe the bug**
Accessibility feedback from a user:

> Screen (LED) state. I liked being able to toggle individual LEDs through buttons in the browser; I was able to understand the numbering of LEDs (e.g. LED 0,0) and their corresponding location on the board by toggling individual LEDs. However, it may be nice to have some sort of textual representation of the current state of the screen as it would prevent the screen reader user from having to check 25 button states to recall the state of the screen.

**Comment by pelikhan** [comment]
We could treat the LED matrix as a sequencer.

**Comment by pelikhan** [comment]
Something like this: https://glitch.com/edit/#!/tone-example-sequencer?path=sketch.js%3A13%3A38

**Comment by jamesadevine** [comment]
Neat, let’s discuss this on our call tomorrow

James


From: Peli de Halleux ***@***.***>
Date: Wednesday, 14 July 2021 at 14:25
To: microsoft/jacdac ***@***.***>
Cc: James Devine ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/jacdac] Accessible LED display simulator state (#525)

Something like this: https://glitch.com/edit/#!/tone-example-sequencer?path=sketch.js%3A13%3A38<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fglitch.com%2Fedit%2F%23!%2Ftone-example-sequencer%3Fpath%3Dsketch.js%253A13%253A38&data=04%7C01%7Ct-jamdev%40microsoft.com%7C8cb527e0e68e4208f41a08d946cac7be%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637618659018421622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z8eVu6axPSL20vBmodbVRCPeUyn1CI5zWH0BYvkRy6M%3D&reserved=0>
