### ISSUE TITLE
Toggles to enable sensor aria features?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#530]
**Describe the bug**

User feedback:

> While having all the different outputs marked up as aria regions makes it screen reader accessible, it may make the output noisy, consequently making it hard for the BVI users to focus on specific things. I am thinking aloud here, but I wonder if adding a set of toggles that let the user select the list of sensors they want live feedback about might reduce the cognitive load. I will keep you posted as I continue exploring.

It seems like we need to think more deeply about how to accessibly expose sensor data in the dashboard.

**Comment by pelikhan** [comment]
We could have a toggle on the card that enables "polite" announcements or even use sounds.
