### ISSUE TITLE
VM bytecode and (Static) TypeScript implementation

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#531]
- [ ] compile away jsep.expression to stack-based evaluation
- [ ] compile away symbols (roles, service references, variables)
- [ ] tables for role -> serviceclass, opcodes -> functions, fast lookups
- [ ] new interpreter in Static TypeScript to work at bytecode level

**Comment by pelikhan** [comment]
Maybe first rewrite the bytecode interpreter as regular typescript (that can be compiled to STS) and also move it to a webworker.
