### ISSUE TITLE
Button module firmware not consistent.

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#534]
**Describe the bug**
It seems that the padauk button implementation is more up to date than the STM implementation. STM modules do not implement `pressure` functionality. This means they return no reading when asked.

**Comment by pelikhan** [comment]
We should give another look at this button and maybe split the spec one more time so that button is events only.

**Comment by tballmsft** [comment]
@mmoskal ?

**Comment by jamesadevine** [comment]
From looking at the rotary control module today, it seems that the button implements only 8-bit pressure reads as opposed to the required 16-bit value

**Comment by jamesadevine** [comment]
Do we still do firmware upgrades via the browser? we don't seem to auto build the firmware anymore on jacdac-msr-modules

**Comment by mmoskal** [comment]
you need to run `make bump` to generate a release; I just did - hopefully it works
