### ISSUE TITLE
VM servers missing service registers and events

### ISSUE THREAD

**Issue by ducky64** [microsoft/jacdac#536]
When using VM programs with server roles (where services / devices are automatically spun up), these problems show up with the JDOM test system:
- Service registers read `undefined`, for both `.data` and `.unpackedValue`
- Events fail to fire when listening on the service (`service.on(EVENT, (ev: JDEvent) => { ... })`).

It's also totally possible I'm missing some critical setup code, and that's the root cause.

**To Reproduce**
On the [VM tests branch / PR](https://github.com/microsoft/jacdac-ts/pull/231) on jacdac-ts, run [tests/vm/buttontoswitch.spec.ts](https://github.com/microsoft/jacdac-ts/blob/vmprogramorama/tests/vm/buttontoswitch.spec.ts). It will fail. There is (currently) some debugging information printed. Note that bus events also include the button server that is controlled by the test scenario.

**Expected behavior**
Registers read non-undefined values and events fire.

**Desktop (please complete the following information):**
 - Node tests w/ Mocha on Windows 10

**Comment by tballmsft** [comment]
@ducky64 I made some fixes in the PR around the register read and am investigating the event problem.  Whenever you read a register (that may have changed), you need to first issue a  GetAsync command. You may want to provide a helper function for this.

**Comment by ducky64** [comment]
Clarification: is GetAsync a workaround or an intentional part of the API?

**Comment by pelikhan** [comment]
Use refresh on the register if you want to force fetching new data
