### ISSUE TITLE
MakeCode + Jacdac experience not functional

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#539]
**Describe the bug**
Previously, when the Jacdac extension was added to MakeCode, Jacdac devices would appear underneath the simulator. Currently, no device appears beneath the simulator:

![image](https://user-images.githubusercontent.com/4742697/127025102-2dac3f4c-272e-4684-ba03-ed7ec94e2267.png)

**To Reproduce**
1. Go to makecode.microbit.org/beta
2. add jacdac extension
3. connect jacdac device to micro:bit via jacdapter
4. see no device appear

**Comment by jamesadevine** [comment]
@pelikhan

**Comment by pelikhan** [comment]
The preferred editing experience will be at https://microsoft.github.io/jacdac-docs/editors/makecode# where we can enjoy both the whole jacdac editor and makecode editor. @jamesadevine

**Comment by jamesadevine** [comment]
might need some discussion on this one

**Comment by jamesadevine** [comment]
Opted for side-by-side editor.

Need to work on add blocks feature for MakeCode from side-by-side experience.
