### ISSUE TITLE
Clean up old repositories

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#54]
The top hits on google are still garbage.

![image](https://user-images.githubusercontent.com/4175913/98923934-23857380-2489-11eb-9e87-4675cedec9e2.png)

**Comment by pelikhan** [comment]
Humm... JACDAC leads to 0 search hits now. Looks like we are out of the index.

**Comment by jamesadevine** [comment]
Is this good or bad? :smile:

jacdac-ts shows up first for me on bing and google
