### ISSUE TITLE
on-register-change block should request streaming from client

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#541]
VM needs to set 

rw internal streaming_samples: u8 # @ streaming_samples

on client service to an appropriate value in order to get updates for the on-register-change block

**Comment by pelikhan** [comment]
Once you register the REPORT_UPDATE, the bus will refresh the register for you

**Comment by tballmsft** [comment]
Done and tested: https://github.com/microsoft/jacdac-ts/pull/234
