### ISSUE TITLE
get rid of microsoft.github.io/jacdac-ts?

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#545]
searching for jacdac on google yields https://microsoft.github.io/jacdac-ts/ as first result:

![image](https://user-images.githubusercontent.com/10767146/127580402-29be7c51-44c8-4052-af25-deb2eef924d2.png)

**Comment by pelikhan** [comment]
it's convinient to use these github pages to host the javascript documentation. I need to figure why is the SEO is so bad on the jacdac-docs project.
