### ISSUE TITLE
what is the purpose of max_force

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#550]
I am writing about the accelerometer spec, but really don't understand the max_force register (or see it implemented):
```
rw max_force?: i12.20 g @ 0x80

Configures the range forces detected. Read-back after setting to get current value.
```
What is the use case for this register?

**Comment by mmoskal** [comment]
accelerometer can often be configured to detect forces up to 2g, 4g and 8g (for example). You will get different precision depending on which range you ask for, and higher accelerations will get clamped. So the idea is, you know you never exceed 1.5g but need precise data so you try to set it to 1.5g; the device will then decide to set it to the lowest higher number, say 2g which you can confirm by reading back.

**Comment by tballmsft** [comment]
thanks!
