### ISSUE TITLE
Represent smart phone hardware on dashboard?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#551]
It might be fun to implement web apis for things like accelerometers, compass and microphone--core components of modern smartphones--and represent them on the dashboard/potentially use them for VM programs

Do we have access to these pieces of hardware via web apis on mobile devices? I remember seeing a few cool demos years ago...

This would be great as a quick demo of the power and universal nature of Jacdac.

**Comment by pelikhan** [comment]
Surfacing the sensors should not be too hard but we need a way to somehow link the phone to a desktop running the dashboard. We could do this with websockets if we had a backend.

**Comment by jamesadevine** [comment]
Yeah, for sure. I'm thinking this might be useful to get an idea of what jacdac is about without having low cost hardware. You mentioned a long time ago about having a jacdac experience built into the web page... Perhaps the home page could show digital twins for live sensor data from a smartphone?

**Comment by pelikhan** [comment]
CLosing this. From the web, you only get access to the accelerometer. YOu need an app to access the rest of the sensor.
