### ISSUE TITLE
ESP32-S2 does not appear over WebSerial

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#562]
**Describe the bug**
When connecting via WebSerial to ESP32-S2 on my windows PC the device does not appear in the WebSerial dialogue. The same device worked correctly on my mac.

**To Reproduce**
1. Connect JacdacIoT board to Windows PC.
2. Click on Connect Serial
3. See no devices appear in the selection dialogue.

**Comment by mmoskal** [comment]
it did appear for me, but was otherwise broken. fixed now.
