### ISSUE TITLE
add command-not-understood report

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#564]
Right now we never know if the command (including register get/set) was lost or is it not supported. We could add a generic not-understood response.

One way to do it would be to use high bit of `service_number` field (and repeat `service_command` with `service_size==0`). I think that can be implemented in 1 bit of memory and 10-20 instructions on Padauk (which may still be too much for some services). This will be hacky, in the sense that if someone sends two commands very quickly one after another, and the first one is not understood, only the second one would be acted upon. The same is true for ACKs on Padauk though.

**Comment by jamesadevine** [comment]
Is `service_number` == `service_index`?

According to the spec, this is what we use for ACKs:

<img width="1208" alt="Screenshot 2021-08-12 at 11 21 54" src="https://user-images.githubusercontent.com/4742697/129181071-74ccdc67-d413-468d-bb5f-6f2b38bb178b.png">

Are you suggesting we use one of these numbers (e.g. 0x3b) to represent a NACK, or something else?

**Comment by pelikhan** [comment]
yes service_number -> service_index https://github.com/microsoft/jacdac-ts/commit/f27ae205d7b52c94527a5a7c10a7e1d3f4813fff

**Comment by mmoskal** [comment]
I was thinking of doing `0x80 | service_index`

**Comment by tballmsft** [comment]
makes sense to me - very useful.

**Comment by pelikhan** [comment]
Much better than the retried we have to do now

**Comment by pelikhan** [comment]
Updated at https://github.com/microsoft/jacdac/pull/809/files?authenticity_token=bd67Z9ReZKVxBJK9vV4QGIFr%2BhLAl41g74jmljXyFkSbvXUijk%2BaxjlooLOVqei5JFTDD%2BVIvlqv3Ohv3fWCGw%3D%3D&file-filters%5B%5D=.mdx#diff-228e4a143bb8029bfd3a1e61d49d59c2108ca871607774f5599b9c29b8d4dcd3

**Comment by pelikhan** [comment]
The JDOM stores the information in the .notImplemented field of registers.
