### ISSUE TITLE
HID Mouse Jacdac Server (via pxt-jacdac)

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#584]
Need to be able to translate Jacdac input devices to USB HID Mouse events!

**Comment by pelikhan** [comment]
Do we have a USB HID mouse driver for micro:bit v2? @jamesadevine

**Comment by pelikhan** [comment]
Use F4 brain to run makecode servers.

**Comment by pelikhan** [comment]
This is done. Needs testing once hid layer is working.
