### ISSUE TITLE
HID Joystick Jacdac server (via pxt-jacdac)

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#585]
Need to be able to translate Jacdac input devices to USB HID Joystick events!

**Comment by pelikhan** [comment]
In MakeCode?, please specify scenario/requirements.

**Comment by jamesadevine** [comment]
pxt-jacdac (as in title), so yes makecode. Do you have a preferred makecode label?

**Comment by jamesadevine** [comment]
current set of labels are confusing, out of date, and potentially duplicative.

**Comment by pelikhan** [comment]
Which editor? micro bit or maker?
________________________________

**Comment by jamesadevine** [comment]
both preferably. ~extra redundancy

**Comment by pelikhan** [comment]
which brain do you plan to use for this? we do not have USB HID support for micro:bit v2.

**Comment by pelikhan** [comment]
Good to have, but less critical than mouse/keyboard.

**Comment by pelikhan** [comment]
Moving down to p3

**Comment by pelikhan** [comment]
done
