### ISSUE TITLE
USB HID Joystick on RP2040

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#588]
Title ** note lower priority **

**Comment by pelikhan** [comment]
We don't have a HID joystick specification yet. Do we need this?

**Comment by jamesadevine** [comment]
I think adding this is a stretch.

We do not even currently have a joystick extension for makecode, though the code for hid joystick exists in codal. I think P2 is the correct priority to have for now.

**Comment by pelikhan** [comment]
Moving it to p3

**Comment by pelikhan** [comment]
udpated platform
