### ISSUE TITLE
LED Bar firmware

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#589]
Title

**Comment by pelikhan** [comment]
- [ ] finish firmware
- [ ] add to device catalog

status: in progress.

**Comment by jamesadevine** [comment]
firmware: https://github.com/microsoft/jacdac-msr-modules/pull/26

**Comment by pelikhan** [comment]
@mmoskal picture needed in catalog

**Comment by mmoskal** [comment]
I don't have hardware...

**Comment by jamesadevine** [comment]
Peli has a couple led bars

James
________________________________
