### ISSUE TITLE
rename service_number field everywhere

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#59]
I suggest we rename service_number to service_index, which more accurately reflects that the value of the field is an index into a device's advertised list of services.

**Comment by mmoskal** [comment]
`JD_SERVICE_NUMBER_CRC_ACK` (and also one for pipes) is an encoding trick to save bits. Service numbers only go up to 58 or so (because of packet size limits in announcement) but there's 5 bits reserved for it, so numbers 59-63 would otherwise go unused.

**Comment by mmoskal** [comment]
Oh, and also the CRC_ACK or PIPE messages are not tied to any particular service, so they don't need service index.

**Comment by pelikhan** [comment]
Renaming is done. I think the current conversation if for another bug.
