### ISSUE TITLE
Device catalogue updates

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#591]
Support all hackathon devices.

Includes:

* pictures
* QR code / csv file productid
* catalogue entry

Device details to be enumerated later.

**Comment by pelikhan** [comment]
Test QR code routing too

**Comment by pelikhan** [comment]
here is how you get to the device registration tool: 
![image](https://user-images.githubusercontent.com/4175913/131718790-2fd276dd-42b3-4ab6-bee3-66c04cbba272.png)

**Comment by pelikhan** [comment]
@mmoskal upload the pictures and i can do the rest
