### ISSUE TITLE
import uf2 random number generator

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#6]
@pelikhan can you import the uf2 random number generator as a react component so i can embed it in the spec page?

https://github.com/microsoft/uf2/blob/master/patcher/index.html

**Comment by pelikhan** [comment]
See https://github.com/microsoft/jacdac/commit/fa941fbc701935d206290af153c60e4804c89cfe

**Comment by jamesadevine** [comment]
Thanks Peli!
