### ISSUE TITLE
Power module

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#603]
We need to make a firm decision on the power story for Hackathon.

I think we are at the point where we decided that high power modules will have a dedicated micro usb connector on them (e.g. RGB LED generic and Braille).

**Comment by pelikhan** [comment]
Putting 2 power modules on the same network creates havoc.

**Comment by jamesadevine** [comment]
Could you elaborate? The padauks will turn off their power if they detect another power provider on the bus.

**Comment by pelikhan** [comment]
How are we supposed to have more than one power module on a single bus?
Also the power module I got seems defective, can’t get it to work properly.
________________________________

**Comment by jamesadevine** [comment]
Not priority for hackathon
