### ISSUE TITLE
micro:bit + Jacdac OOB experience

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#607]
Need to flash micro:bits so that they work with the dashboard first time.

- [x] Create an OOB program (Tom)
- [x] upload binary to this issue
- [x] create landing page in web site for OOB (peli + gabi) https://github.com/microsoft/jacdac/issues/621
- [ ] Flash micro:bits with OOB program

**Comment by jamesadevine** [comment]
map buttons/potentiometers to rgb led controls 

Based on number or buttons configuration changes. On/off/rotate. Sounds on micro:bit.
Show on screen buttons are pressed.
Slider changes properties about the LEDs? screen? sound?
Humidity sensor turns micro:bit into weather station.

**Comment by pelikhan** [comment]
In playground currently: 
![image](https://user-images.githubusercontent.com/4175913/132508221-32fec77b-8ec7-492a-a21d-883eefcad318.png)

**Comment by tballmsft** [comment]
https://github.com/microsoft/pxt-jacdac/tree/master/tools/v2oob

**Comment by jamesadevine** [comment]
James to link issues here

**Comment by jamesadevine** [comment]
@tballmsft @pelikhan are we ready to go with the V2 OOB experience for Jacdac?

**Comment by pelikhan** [comment]
Yes it looks ok.

**Comment by jamesadevine** [comment]
@tballmsft to upload binary

**Comment by tballmsft** [comment]
[microbit-jacdac-microbit-oob.zip](https://github.com/microsoft/jacdac/files/7212724/microbit-jacdac-microbit-oob.zip)

**Comment by jamesadevine** [comment]
Requires new modules to be added and new version to be uploaded here!

https://github.com/microsoft/jacdac/issues/671

**Comment by jamesadevine** [comment]
50 micro:bits flashed
