### ISSUE TITLE
Server APIs in jacdac docs

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#610]
Maybe I'm just bad at it, but currently, I think it is quite tricky to send a packet to servers as we do not have typed APIs on the module class. Right now, I think we have to manually craft a packet and send it on the jacdac bus.

It would be great if we could brainstorm someway to make it more intuitive to interact with the hardware programmatically from docs pages. 

A better dev x would be great for hackathon.

**Comment by pelikhan** [comment]
let's chat about what you're looking for.

**Comment by pelikhan** [comment]
In playground currently: 
![image](https://user-images.githubusercontent.com/4175913/132508221-32fec77b-8ec7-492a-a21d-883eefcad318.png)

**Comment by pelikhan** [comment]
Closing for now.
