### ISSUE TITLE
jacdac + VR integration

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#611]
- [ ] create a VR base to work from (@microsasa)
- [ ] consume jacdac-ts

**Comment by pelikhan** [comment]
Not sure what we can do on that one besides having them use our Ts package....

**Comment by pelikhan** [comment]
Unclear where to start there. We can use A-Frame, and use jacdac-ts, most of the work is VR-related.

**Comment by jamesadevine** [comment]
@microsasa, any updates your side?

**Comment by pelikhan** [comment]
Not in scope for hackaton.

**Comment by pelikhan** [comment]
It seems that we would get a lot of freebee by emulating a gamepad (which the browser supports natively)

**Comment by jamesadevine** [comment]
The code for game pad maybe exists in codal??

James
________________________________
