### ISSUE TITLE
Incorrect register format crashes device tree?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#612]
**Describe the bug**
I have written the speech synthesis service implementation for jacdac-c. Two of the fields ([`rate`, `pitch`](https://microsoft.github.io/jacdac-docs/services/speechsynthesis)) are in u16.16 format. I set these fields to the default value `1 << 16` which I think is a "1" in u16.16.

When this value is set, and I inspect the device in the tree view, the tree view crashes with the following diagnostics:

```json
{error: TypeError: humanValue.indexOf is not a function
    at decodeMember (https://microsoft.github.io/ja…, pkt: Packet, data: '00000100'}data: "00000100"error: TypeError: humanValue.indexOf is not a function
    at decodeMember (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:38906:50)
    at https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:38953:19
    at Array.map (<anonymous>)
    at decodeMembers (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:38952:17)
    at decodeRegister (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:38982:17)
    at decodePacket (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:39022:10)
    at decodePacketData (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:39059:12)
    at Packet.get (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:38191:110)
    at JDRegister.get (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:68342:138)
    at JDRegister.get (https://microsoft.github.io/jacdac-docs/app-81855bd4caf0e30ec386.js:68335:36)pkt: Packet {_meta: {…}, key: 26121, _header: Uint8Array(16), _data: Uint8Array(4), timestamp: 2402934.699999988, …}[[Prototype]]: Object
decodePacketData @ pretty.ts:492
get @ packet.ts:283
get @ register.ts:283
get @ register.ts:268
useRegisterHumanValue @ useRegisterValue.ts:14
RegisterTreeItem @ JDomTreeViewItems.tsx:219
Ch @ react-dom.production.min.js:157
li @ react-dom.production.min.js:180
ck @ react-dom.production.min.js:269
bk @ react-dom.production.min.js:250
ak @ react-dom.production.min.js:250
Tj @ react-dom.production.min.js:250
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
push.60053.exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
Jg @ react-dom.production.min.js:237
Oh @ react-dom.production.min.js:170
(anonymous) @ useChange.ts:24
emit @ eventsource.ts:211
processAnnouncement @ device.ts:146
processAnnouncement @ device.ts:644
processPacket @ bus.ts:868
handleFrame @ transport.ts:306
handleMessage @ workertransport.ts:60
```

**Comment by jamesadevine** [comment]
cc @tballmsft

**Comment by pelikhan** [comment]
The browser  should not crash anymore (https://github.com/microsoft/jacdac-docs/commit/05f742da4643b81149a90fb89cb3570331d5f041)

Can you post a trace or a dump of your packets?

**Comment by pelikhan** [comment]
Look for copy icon in packet inspector (new)
![image](https://user-images.githubusercontent.com/4175913/132777361-9d862143-96bd-4c1f-a4b4-6bf9ce595851.png)

**Comment by pelikhan** [comment]
Also, i'm doing more checks about the integrity of the packet in the client. You'll see error messages when there's a format issue.
![image](https://user-images.githubusercontent.com/4175913/132799502-1611ebf0-55a9-4e6b-b213-43c0b9921cae.png)

**Comment by jamesadevine** [comment]
No longer crashes, but NaN is displayed in the tree view:

![image](https://user-images.githubusercontent.com/4742697/132830860-f20bc715-d694-4751-9519-e8a66670707b.png)

packaet data:
3b01080042c353764a19c8440401831000000100 from AA90/SPEECH SYNTHESIS (1): undefined; sz=4; GET rate: NaN; USB

**Comment by jamesadevine** [comment]
![image](https://user-images.githubusercontent.com/4742697/132830970-158e2c3a-e5fd-4e0f-96ea-54cad297e011.png)

**Comment by pelikhan** [comment]
can you attach a packet trace?

**Comment by pelikhan** [comment]
Make sure to run with `?dbg=1` so that i collect those.

**Comment by pelikhan** [comment]
@jamesadevine attach full trace so that i can replay this issue

**Comment by jamesadevine** [comment]
[trace.jd.txt](https://github.com/microsoft/jacdac/files/7145067/trace.jd.txt)

**Comment by pelikhan** [comment]
Fixed in https://github.com/microsoft/jacdac-docs/commit/2c272e4cc7d53b189ec3cf16bb95f87794043b45

**Comment by jamesadevine** [comment]
when will this be live?

**Comment by pelikhan** [comment]
It's live now.

**Comment by jamesadevine** [comment]
Looks good 
![image](https://user-images.githubusercontent.com/4742697/132895688-333b8ef5-cf0b-47f7-b820-1d35eb4c5ed2.png)
