### ISSUE TITLE
client not triggering events

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#613]
Working on OOB experience (https://github.com/microsoft/pxt-jacdac/tree/master/tools/v2oob)

The program below never shows a duck, despite changing the position of the rotary encoder (virtually)
```
modules.rotaryEncoder1.setStreaming(true)
modules.rotaryEncoder1.onPositionChangedBy(1, () => {
    basic.showIcon(IconNames.Duck)
})
```

**Comment by pelikhan** [comment]
It seems that roles are not encoded properly in the packer.

![image](https://user-images.githubusercontent.com/4175913/132775928-582e7ee5-1656-4be0-8f33-82ce47aabdcc.png)

**Comment by pelikhan** [comment]
``00000042`` should be ``42``

**Comment by pelikhan** [comment]
fixed in https://github.com/microsoft/pxt-jacdac/pull/48

**Comment by pelikhan** [comment]
Fixed with https://github.com/microsoft/pxt-jacdac/commit/04944f3fff9d777a5ebdc2df6b78189a39d6a091
