### ISSUE TITLE
How do I add Jacdac blocks to MakeCode?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#614]
I remember there being an easier way to add module blocks, but it is not clear to me how I do it other than through the extensions dialogue and the github url.

For me, the makecode editor does not have an add blocks button, and it still looks a bit broken (even when connected to micro:bit via webusb):

<img width="998" alt="Screenshot 2021-09-10 at 12 54 06" src="https://user-images.githubusercontent.com/4742697/132849571-8a3ed120-33bc-4c15-b9bd-273df3a95d00.png">

When I add a rotary control module, add blocks button does appear: 

<img width="1610" alt="Screenshot 2021-09-10 at 12 53 25" src="https://user-images.githubusercontent.com/4742697/132849513-044f9fdb-fbdc-49ed-9a5b-dd0aeb37918d.png">

What are the random rectangles in the device area in both instances?

If we don't want people to use the viewer in MakeCode, we need to show the add blocks prompt.

**Comment by pelikhan** [comment]
What kind of hardware do you have connected? Those empty boxes are devices for which we don't have a rendering of the services.

**Comment by jamesadevine** [comment]
I had a micro:bit and a speech synthesis module only.

**Comment by jamesadevine** [comment]
also, the jacdac view doesn't show up at all in the side-by-side view. How do users click the add blocks button?

**Comment by pelikhan** [comment]
There is a add blocks button in the dashboard.
________________________________

**Comment by jamesadevine** [comment]
I do not see it in the side by side editor

**Comment by jamesadevine** [comment]
![image](https://user-images.githubusercontent.com/4742697/132884759-4c6de733-54a1-4b9a-8b70-2cae94120184.png)
I also can't see the modules I've got connected either!
