### ISSUE TITLE
autopopulate makecode editor with pxt-jacdac?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#615]
Can we pre-load a makecode editor with the pxt-jacdac extension?

It is a bit cumbersome to open the side by side, then add the pxt-jacdac extension, then add the packages for your modules.

**Comment by pelikhan** [comment]
We don't intend to maintain a separate instance of makecode so no.

**Comment by jamesadevine** [comment]
why would we require a separate instance of makecode? could we just open a default project with pxt-jacdac?

**Comment by jamesadevine** [comment]
try explaining all the steps to someone who has not used makecode before. It is a bit overwhelming!

**Comment by jamesadevine** [comment]
So lets have two buttons that say "open existing jacdac project" and "create new jacdac project"

**Comment by pelikhan** [comment]
Where do you want those buttons?

**Comment by pelikhan** [comment]
So we could create a set of makecode tutorials for jacdac.

**Comment by pelikhan** [comment]
This would require a change in the makecode editor, not happening. We've beefed up the docs on getting started with jacdac.
