### ISSUE TITLE
MakeCode Modules category Green on Green

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#616]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4742697/132881298-3b048108-873a-4694-bf52-1d3bd0bdad0e.png)

Jacdac logo remains green and becomes invisible when "modules" is selected.

**Comment by pelikhan** [comment]
Unlike other icons which are SVG font icons and recolored in CSS, the Jacdac icon is an image imported as background-uri css. Thus does not get recolored.

**Comment by jamesadevine** [comment]
Could we not just add an SVG Jacdac icon?

**Comment by pelikhan** [comment]
we are done changing the logo?

**Comment by jamesadevine** [comment]
well it's now printed on boxes, so yes, I think so

**Comment by pelikhan** [comment]
This would require quite a bit of support in MakeCode, which does not have good support for custom icon display. Won't fix.

**Comment by jamesadevine** [comment]
So SVG icon won’t work?

James
________________________________
