### ISSUE TITLE
MakeCode "Modules" category rename?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#617]
Can we rename to something like "Jacdac Modules"? Modules is a bit unspecific!

**Comment by pelikhan** [comment]
Too long, we can just do "Jacdac"


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by jamesadevine** [comment]
Sounds good

**Comment by pelikhan** [comment]
Logo needs to be rotated too.

**Comment by pelikhan** [comment]
It's too late to do this kind of renaming at this point.
