### ISSUE TITLE
on start block does not work with jacdac modules?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#619]
**Describe the bug**
Jacdac code placed in on start does not run, presumably because jacdac hasn't started up!

Repro MakeCode program:

```ts
modules.led1.animate(0xffff00, 100)
```

**Comment by pelikhan** [comment]
could be many things, like led1 is not role-bound yet

**Comment by jamesadevine** [comment]
right... but what should the behaviour be? 

CC @tballmsft

**Comment by pelikhan** [comment]
For register, we remember and set the value when the device connects but commands are lost at the moment. You should pause until connected really
________________________________

**Comment by pelikhan** [comment]
tell peple to use on connected

**Comment by tballmsft** [comment]
got it. we need to document those APIs too
