### ISSUE TITLE
MakeCode forever loops have inconsistent timing

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#620]
Lost packets? Program was not loaded on the micro:bit, program was running via the split editor. 

Repro program:

```ts
basic.forever(function () {
    modules.led1.animate(0xff0000, 100)
    basic.pause(500)
    modules.led1.animate(0x00ff00, 100)
    basic.pause(500)
})
```

**Comment by pelikhan** [comment]
What is the bug?

**Comment by jamesadevine** [comment]
Bug is that the led does not change colour every 500 ms.

I can't seem to save trace in the split editor view

**Comment by pelikhan** [comment]
Saving fixed in https://github.com/microsoft/jacdac-docs/commit/944961c99365d131aa9437f20e388c8245bb52a1

**Comment by pelikhan** [comment]
It looks like the command is lost sometimes. We should discuss the strategy here.

**Comment by tballmsft** [comment]
@mmoskal  - we talked about having "reliable commands", the dual of events = "reliable reports".

**Comment by tballmsft** [comment]
The plumbing is already available for events, and can be reused for "reliable commands", as discussed with @mmoskal.

**Comment by mmoskal** [comment]
So the plan here would be to use the same `service_operation` range as events (`0x8000` to `0xffff`), but with the `command` flag set on the frame. This leaves us with a 7-bit counter for commands and 8-bit namespace for command codes. We should probably allocate a bit in the announce flags indicating this is supported, and then allow all commands to be sent via this channel. This (as well as the NACK feature) will definitely not fit on the smallest PADAUK, but I think we already decided to drop it in future.

Do we need this for the hackathon?

**Comment by jamesadevine** [comment]
No, I think we should wait till after hackathon to implement a change like this

James
________________________________

**Comment by tballmsft** [comment]
@jamesadevine - is this really a P0?

**Comment by jamesadevine** [comment]
Nope, adjusted
