### ISSUE TITLE
Kit page experience for jacdac-docs 

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#621]
**Describe the bug**

It would be great to have a walkthrough experience for the dashboard.

**Comment by pelikhan** [comment]
We need a design meeting to discuss exactly what you're trying to do here. Simplest is recording a video.

**Comment by jamesadevine** [comment]
@mgabrieledamone can you set up a meeting to discuss some kind of guided experience for the dashboard?

**Comment by mgabrieledamone** [comment]
Yup, will do!

**Comment by pelikhan** [comment]
I think we got confused with the kit meeting and missed the meeting.

**Comment by pelikhan** [comment]
@mgabrieledamone package me the images, you can drag and drop them into this issue if you want.

**Comment by mgabrieledamone** [comment]
[Jacdac Kit Images.zip](https://github.com/microsoft/jacdac/files/7179967/Jacdac.Kit.Images.zip)

**Comment by pelikhan** [comment]
Those SVG are somewhat extremely hard to work with. Can you send JPG or PNGs? SVG might work for the laptop infrgraphics but pictures of the kit should be HD JPEGs.

**Comment by jamesadevine** [comment]
This needs a priority -1 and delivering ASAP. @mgabrieledamone is working on the images.

**Comment by pelikhan** [comment]
https://microsoft.github.io/jacdac-docs/hardware/kit , the more images the merrier.

**Comment by pelikhan** [comment]
@mgabrieledamone images of the kit?

**Comment by mgabrieledamone** [comment]
[Project image graphics (1).zip](https://github.com/microsoft/jacdac/files/7203198/Project.image.graphics.1.zip)

**Comment by mgabrieledamone** [comment]
![Group 102](https://user-images.githubusercontent.com/71759622/134210128-0164fbfa-b5ea-4a8f-a7d9-8989fd2dd5ee.jpg)
![Group 103](https://user-images.githubusercontent.com/71759622/134210132-d6052b78-c19e-4bf8-ae98-c0b45ba2e829.jpg)

**Comment by mgabrieledamone** [comment]
![Group 103 (1)](https://user-images.githubusercontent.com/71759622/134212956-54cda195-1cfe-44e8-b2d4-e05c2477af7a.jpg)

**Comment by jamesadevine** [comment]
@pelikhan can we get rid of the packaging render to the left of the title? 

Key user actions render below the fold on my huge screen. The three boxes should be the most prominent thing on the page.

![image](https://user-images.githubusercontent.com/4742697/134304793-bcf98967-c8ef-4861-b260-27becc6933ae.png)

**Comment by pelikhan** [comment]
Not sure I understand, please circle ui Elements
________________________________

**Comment by jamesadevine** [comment]
![134304793-bcf98967-c8ef-4861-b260-27becc6933ae](https://user-images.githubusercontent.com/4742697/134322487-50d4838a-7951-4606-9ad3-cf6c6c18d784.png)

**Comment by pelikhan** [comment]
how about 
![image](https://user-images.githubusercontent.com/4175913/134326313-6a0ac432-1fb8-4608-b664-b0f154040956.png)
 ?

**Comment by jamesadevine** [comment]
Better, but why do we need image in top right? The unbox render shows it all.

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/134327002-db233b28-be53-44e0-af78-57496f490165.png)

**Comment by jamesadevine** [comment]
Oh that looks awesome! :smile: 

@mgabrieledamone ?

**Comment by mgabrieledamone** [comment]
A few more final suggestions:
1) Can we scale up the Jacdac logo next to "Hardware kit" so that it's as tall as the lower-case letters?
2) Can we make the title "Hardware Kit" in **bold**?
3) Can we move the titles "Unbox", "Explore" and "Build" slightly down. It looks like they are too attached to the image.
4) Can we move all the green buttons down a tiny bit so they are distanced a bit more from the text above them? And can we have the buttons all on the same vertical level?

Thanks :)

**Comment by mgabrieledamone** [comment]
Other suggestion... can we have the website background in full white? And without the faded Jacdac logo in the background? :)

**Comment by jamesadevine** [comment]
These are good suggestions, thanks @mgabrieledamone

**Comment by pelikhan** [comment]
> can we have the website background in full white?

What do you mean by full white?

**Comment by mgabrieledamone** [comment]
Just a normal white coloured background rather than the light grey we have now if possible! :)

**Comment by pelikhan** [comment]
please provide html color #....

**Comment by mgabrieledamone** [comment]
#FFFFFF (White)

**Comment by pelikhan** [comment]
Sorry, lots of different "white" tones, #.... is always going to be easier to process (Ctrl+C, Ctrl+V, no confusion).

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/134331605-0521af4a-8953-469f-9fa8-0d62f7f2aaad.png)

**Comment by mgabrieledamone** [comment]
I'm not sure I understood... do you want me to paste a picture?

**Comment by pelikhan** [comment]
When you specify a color, always provide HTML hex description, or HSL.

**Comment by mgabrieledamone** [comment]
That still looks grey though no?

**Comment by pelikhan** [comment]
I tried the white but Material UI does some stuff with colors in the theme code. Unclear where this happens.

**Comment by mgabrieledamone** [comment]
Aaaaaah got it!

**Comment by mgabrieledamone** [comment]
Without the faded logo in the background is already way better anyway! Thanks!

**Comment by pelikhan** [comment]
Can't seem to figure out why material ui is not picking up the white background change for now

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/134335359-14c8c6de-c015-479f-be95-daf41d405045.png)

**Comment by pelikhan** [comment]
somewhat complicated to get a decent alignment of the icon and text when the icon gets big

**Comment by pelikhan** [comment]
other suggest a CSS height for the image

**Comment by pelikhan** [comment]
I'll close this and we can reopen with more tweaks.

**Comment by jamesadevine** [comment]
Dark mode broken:
![Screenshot 2021-09-22 at 17 10 23](https://user-images.githubusercontent.com/4742697/134381365-a6c1cc6b-1847-4eaf-99e1-d5335d7855b4.png)
