### ISSUE TITLE
Assign product id to micro:bit

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#622]
- [x] assign product id (@pelikhan)
- [ ] take picture (@mmoskal )
- [ ] add to device catalogue (@jamesadevine)

**Comment by pelikhan** [comment]
product id: 0x32f6253d

**Comment by pelikhan** [comment]
Added to https://github.com/microsoft/pxt-jacdac

**Comment by jamesadevine** [comment]
I can't add the micro:bit via the device registration page. Should I just do it manually?

**Comment by pelikhan** [comment]
Manually is fine.

**Comment by pelikhan** [comment]
Added to device catalog.

**Comment by pelikhan** [comment]
@mmoskal might want to take a picture with the standardized lightning
