### ISSUE TITLE
jacdac usb packets not routed to parent frame

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#623]
In split view, jacdac physical packets are not being bridged to the parent iframe.

**Comment by pelikhan** [comment]
One solution would be to issue a simmessage in routing.ts when we receive a native packet from usb.

**Comment by jamesadevine** [comment]
Sounds like the neatest solution IMO. What are the alternatives?

James
________________________________

**Comment by pelikhan** [comment]
Go back to integrated makecode experience and focus on fixing that one.
