### ISSUE TITLE
add blocks github link does not go to correct URL

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#624]
**Describe the bug**
In the add blocks dialogue within MakeCode, there are links to the various github repositories to be imported from. When I clicked on one of these links (joystick, as in the image below) it took me to https://github.com/pxt-jacdac :

![image](https://user-images.githubusercontent.com/4742697/132950310-c32a2aa5-81a5-4465-a240-7a5a4c45524c.png)

**Expected**
Links should redirect to the actual github repository.

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8489
