### ISSUE TITLE
Laggy joystick simulator

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#625]
**Describe the bug**

The joystick simulator sometimes freezes in use: 

![laggy-joystick](https://user-images.githubusercontent.com/4742697/132951145-b676a9b0-5abd-40ac-ad9d-687c30f8f3eb.gif)

It seems to go away when I have a hex file with an app that uses a joystick is flashed to the micro:bit (attached).
[microbit-joystick.zip](https://github.com/microsoft/jacdac/files/7148006/microbit-joystick.zip)

packet trace:
[trace.jd.txt](https://github.com/microsoft/jacdac/files/7148001/trace.jd.txt)

(it's not the hardware as the makecode console view never freezes, and the attached program works reliably).

**Comment by pelikhan** [comment]
Every now and then the joystick emits a ton of events and stops generate reading values.

![image](https://user-images.githubusercontent.com/4175913/132998667-3cf6991a-1dcc-45a7-a8a3-9e41e944dd5a.png)
[trace.jd (4).txt](https://github.com/microsoft/jacdac/files/7150097/trace.jd.4.txt)

**Comment by pelikhan** [comment]
Looks like it's the packet console that's introducing lags

**Comment by jamesadevine** [comment]
Awesome! I was worried it was the hardware!

**Comment by pelikhan** [comment]
Was a bug in the logic to collect streaming samples interval
