### ISSUE TITLE
basic.showNumber (scrolling) blocks Jacdac

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#633]
Title says it all - if you are using jacdac with microbit and issue
```
basic.showNumber(123)
```
you will lose control events and devices will reattach.

**Comment by pelikhan** [comment]
Show* are blocking. We need to run handlers in a new fiber

**Comment by pelikhan** [comment]
Please share a repro

**Comment by jamesadevine** [comment]
Tom to share repro.

Need to run jacdac packets in a fiber.

**Comment by tballmsft** [comment]
Repro

- add jacdac extension
- add a simulator (button)
- open console in developer tools
- create the program
```
forever(() => {
basic.showNumber(12345689)
})
```
- See that the button gets detached and reattached.

**Comment by tballmsft** [comment]
this is resolved by peli's fix
