### ISSUE TITLE
firmware updater always shows "up to date"

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#636]
**Describe the bug**
<img width="1456" alt="Screenshot 2021-09-15 at 15 46 58" src="https://user-images.githubusercontent.com/4742697/133455909-3042c437-7234-406a-9474-23af6b9a7de0.png">

As can be seen in the image, one of the modules (DG50) is not up to date, yet the updater displays the message "Up to date!"

It's important we have the firmware updater displaying accurate messages for hackathon so we can push firmware updates as required.

**Comment by pelikhan** [comment]
@jamesadevine I've added a check to ignore devices that are not part of the catalog. What kind of hardware should I be trying this with?

**Comment by pelikhan** [comment]
Add ``?dbg=1`` i've added diagnostics. The modules need to be added to the catalog to be firmware updatable.

**Comment by pelikhan** [comment]
fixed some of the UI inccorrect updates.

**Comment by pelikhan** [comment]
@jamesadevine can you test it is to your tasting now?

**Comment by jamesadevine** [comment]
I think this is much better, although, the module i tested today was up to date, and the page still said requires update?

**Comment by pelikhan** [comment]
Closing for now until i have a repro. This whole firmware upgrade need an rewrite eventually.
