### ISSUE TITLE
makecode documentation

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#637]
Document the MakeCode clients for following Jacdac services
- [x] button
- [x] potentiometer
- [x] thermometer
- [x] barometer
- [x] humidity
- [x] accelerometer
- [x] lex pixel (strip)
- [x] relay
- [x] light level
- [x] rotary encoder
- [x] mouse
- [x] keyboard
- [x] color
- [x] eco2
- [x] flex
- [x] joystick
- [x] tvoc

**Comment by pelikhan** [comment]
Probably dup of https://github.com/microsoft/jacdac/issues/639

**Comment by pelikhan** [comment]
Avoid using on start --> https://github.com/microsoft/jacdac/issues/619

**Comment by pelikhan** [comment]
Some of the blocks don't render properly.
![image](https://user-images.githubusercontent.com/4175913/134338938-3de9a18c-7b1d-4b2c-8358-e3e590e37d8a.png)

**Comment by pelikhan** [comment]
You probably want to open/close the relay using buttons A/B
