### ISSUE TITLE
Define Haptic service

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#638]
Thoughts on how we should present a haptic service on the bus? 

As a Buzzer perhaps? Or shall we have a haptics service?

- [x] define haptics service --> use vibration service
- [ ] makecode client (@pelikhan)
- [ ] jacdac-stm32 server (@jamesadevine)

**Comment by pelikhan** [comment]
We can try to use https://microsoft.github.io/jacdac-docs/services/vibration/
