### ISSUE TITLE
ensure pxt-jacdac client services are implemented

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#639]
**Describe the bug**
Some services are not yet implemented in pxt-jacdac (e.g. [relay](https://github.com/microsoft/pxt-jacdac/tree/master/relay)). Adding them as an extension causes a `Network Request Failed` error because `pxt.json` does not exist.

We need to make sure all client services are working and available in `pxt-jacdac`. If you click the "Add Blocks" button and one of the modules results in a `Network Request Failed` error, none of the packages are added.

Check:

- [x] relay
- [x] accelerometer
- [x] button
- [x] ambient light
- [x] potentiometer
- [x] temp
- [x] humidity
- [x] rotary encoder
- [x] #640

**Comment by pelikhan** [comment]
It seems that they were all there minus relay. Next, is testing them all with hardware + sim.

**Comment by pelikhan** [comment]
@tballmsft you can add your test programs as "test.ts" in the source

**Comment by tballmsft** [comment]
@pelikhan - what test programs are you referring to?  The programs that are going in the docs?

**Comment by pelikhan** [comment]
Lumping this into docs work.
