### ISSUE TITLE
clean out JACDAC of CODAL

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#64]
We still have the legacy JACDAC implementation in CODAL. How much of it do we still need?

**Comment by jamesadevine** [comment]
Good question! I believe all we're using now is the single wire serial abstraction and I put that in common codal, not in the JACDAC folder. Will remove!

**Comment by jamesadevine** [comment]
@mmoskal Do you think anything different?

**Comment by mmoskal** [comment]
nuke it
