### ISSUE TITLE
Ensure simulator and block units are consistent

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#641]
**Describe the bug**

Simulator for potentiometer units are 0-100%, blocks units 0-1. We should be consistent.

**Comment by tballmsft** [comment]
Which way did we agree to go?

**Comment by pelikhan** [comment]
We’ll got 0..100 in the makecode side
________________________________

**Comment by jamesadevine** [comment]
Yeah, we decided blocks should only deal with whole numbers and should match the units of the simulator.

For potentiometer, simulator goes 0-100% whereas the blocks currently range 0-1. We’d like for the blocks to range 0-100.

James
________________________________

**Comment by pelikhan** [comment]
MakeCode sliders don’t handle decimal numbers anyway.
________________________________
