### ISSUE TITLE
deprecate @jacdac/jacdac-ts

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#642]
@jamesadevine possible to try those steps? https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by jamesadevine** [comment]
When I hit the deprecate button i get:
<img width="1413" alt="Screenshot 2021-09-20 at 10 07 28" src="https://user-images.githubusercontent.com/4742697/133979100-4b1ed99c-9c43-42fc-b3eb-7c3117dfe51c.png">
