### ISSUE TITLE
implement button MakeCode client register `pressed`

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#643]
title says it all

**Comment by jamesadevine** [comment]
I don't think STM-based buttons implement the pressure register.

Before we do this, let me just check the STM code. I have to go through and flash them all anyway, lets see if i can fix this too in the same pass.

**Comment by jamesadevine** [comment]
https://github.com/microsoft/jacdac-c/pull/28

Button code updated, awaiting review.

**Comment by jamesadevine** [comment]
FYI, STM buttons implement the pressure register, but it was not outputting the correct range.

**Comment by jamesadevine** [comment]
This is now merged. I will program the G0 buttons again today.

**Comment by jamesadevine** [comment]
The STM G0 buttons are now reprogrammed and output a pressure value.

@tballmsft, is this what the original issue was about? Or is "pressed" still not available in MakeCode.

**Comment by tballmsft** [comment]
@jamesadevine, @pelikhan: pressed needs to be implemented in MakeCode, which is the issue here.

**Comment by jamesadevine** [comment]
Over to you @pelikhan

**Comment by pelikhan** [comment]
Implemented in v0.6.26
