### ISSUE TITLE
MakeCode temperature client doesn't expose constant registers

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#645]
The temperature service defines the registers below, as well as the temperature_error reading_error.
None of these registers are available in the MakeCode client.

```
const min_temperature: i22.10 °C @ min_reading
Lowest temperature that can be reported.

const max_temperature: i22.10 °C @ max_reading
Highest temperature that can be reported.

ro temperature_error: u22.10 °C  @ reading_error
The real temperature is between temperature - temperature_error and temperature + temperature_error.

enum Variant: u8 {
    Outdoor = 1,
    Indoor = 2,
    Body = 3,
}
const variant?: Variant @ variant
```

**Comment by pelikhan** [comment]
They should be optional.
________________________________
From: Tom Ball ***@***.***>
Sent: Sunday, September 19, 2021 3:37:58 PM
To: microsoft/jacdac ***@***.***>
Cc: Peli de Halleux ***@***.***>; Assign ***@***.***>
Subject: [microsoft/jacdac] MakeCode temperature client doesn't expose constant registers (#645)


The temperature service defines the constants below. They are not available in the MakeCode client

const min_temperature: i22.10 °C @ min_reading

Lowest temperature that can be reported.



const max_temperature: i22.10 °C @ max_reading

Highest temperature that can be reported.



ro temperature_error: u22.10 °C  @ reading_error

The real temperature is between temperature - temperature_error and temperature + temperature_error.



enum Variant: u8 {

    Outdoor = 1,

    Indoor = 2,

    Body = 3,

}

const variant?: Variant @ variant

**Comment by pelikhan** [comment]
This is by design, we only expose reading. value and intensity registers to makecode blocks. The other register are considered advanced and TypeScript only. 

Specifically most of these registers are optional and the makecode user would have to handle missing data.
