### ISSUE TITLE
a way to bring up simulators based on blocks in project

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#647]
When you revisit a project, such as https://makecode.microbit.org/_HjmhTm2spRCe, there are no Jacdac simulators. It would be nice if there was some way to bring up a simulator for each service referred to in a project, so you don't need to do this manually.

**Comment by pelikhan** [comment]
Probably can make it so they automatically spin up
________________________________

**Comment by pelikhan** [comment]
Added button
![image](https://user-images.githubusercontent.com/4175913/134104307-a4ddafb0-1181-4c32-962d-ae6c3670c5cd.png)
