### ISSUE TITLE
Take and add photo of each module to github

### ISSUE THREAD

**Issue by PKos7777** [microsoft/jacdac#648]
take photos of all the modules and upload them to github so everyone can better visualize what the modules look like.  I actually suggest we take the photos on a white background next to a ruler (or on grid-paper still with a ruler).

**Comment by pelikhan** [comment]
Have you seen those?

**Comment by jamesadevine** [comment]
@PKos7777 Is this not sufficient?

https://microsoft.github.io/jacdac-docs/devices/

**Comment by PKos7777** [comment]
ya, thats cool.  Per our earlier conversation, I do think the wood background is not so easily to replicate.  We are about to complete many modules in Shenzhen and I don't think I can find something to match the background.

 I think we should just use white background ... or we suggest a grid paper with measurement markings (that people could print and use for background).

Or maybe we just don't care so much about background ....

**Comment by tballmsft** [comment]
let's not worry about making all the backgrounds the same.
