### ISSUE TITLE
document 'lifecycle' of Jacdac  and JD Client in MakeCode

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#657]
We need to have a page that describes the lifecycle of the Jacdac runtime and clients. This page can also describe the following methods that are in all clients:
- isConnected
- onConnected
- onDisconnected

**Comment by pelikhan** [comment]
fixed by https://github.com/microsoft/jacdac-docs/commit/895f9a55067d2fffba6942520a2dd4483b3b68e0
