### ISSUE TITLE
Test through USB mouse/keyboard server

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#658]
We need to test USB keyboard/mouse Jacdac servers via F4 brain before the pre-hackathon Jacathon scheduled for tomorrow. 

- [x] mouse
    - [x] Windows
    - [x] Mac
- [x] keyboard
    - [x] Windows
    - [x] Mac
- [x] keyboard + mouse
    - [x] Windows
    - [x] Mac
- [x] produce binary and upload here

**Comment by pelikhan** [comment]
Do you want a binary with both mouse/keyboard enabled?

**Comment by jamesadevine** [comment]
If we can do that, yes!

Otherwise one for each would be fine.

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-jacdac/tree/master/tools/hid-servers

Can i use the LED on that device with makecode?

**Comment by jamesadevine** [comment]
No, get rid.

**Comment by pelikhan** [comment]
Currently @mmoskal  investigating keyboard https://github.com/microsoft/jacdac/issues/666

**Comment by jamesadevine** [comment]
@pelikhan can you update the task list when you are online?

**Comment by jamesadevine** [comment]
If we could get a UF2 for todays pre-hackathon, that would be great.

**Comment by tballmsft** [comment]
test with RP2040

**Comment by jamesadevine** [comment]
Tested
