### ISSUE TITLE
MakeCode project samples page

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#659]
We need a page that contains all of the samples that @tballmsft has been working on to provide as starter projects to end users. We should use these example projects tomorrow in our pre-hackathon jacdacathon.

If the page already exists, please link the page and close the issue.

**Comment by tballmsft** [comment]
@jamesadevine - https://microsoft.github.io/jacdac-docs/clients/makecode/extensions/

**Comment by jamesadevine** [comment]
What's the difference between an extension and a project?

Would it be possible to merge?

**Comment by pelikhan** [comment]
@tballmsft  Projects are different, they may involve multiple jacdac servers so we need both.

**Comment by tballmsft** [comment]
Correct - an extension provides a Jacdac client for a particular service.

**Comment by tballmsft** [comment]
I can create a MakeCode project that would have most of the code in samples from the extensions.

**Comment by pelikhan** [comment]
I think we want multiple small project that use 2/3 modules. We should be able to author them in the docs for the most part as long as we don't need to define new roles.

**Comment by tballmsft** [comment]
Sure, that useful too.

**Comment by jamesadevine** [comment]
https://makecode.microbit.org/_VvJaXPH94585

**Comment by jamesadevine** [comment]
The extensions pages are great. Just wondering if we should associate them with module pages? i.e. usb brain F4 dongle should be associated with mouse and keyboard extensions. Accelerometer should be associate with accelerometer service for example.

Is this possible in code @pelikhan ?
