### ISSUE TITLE
bootloader LED light is blue on brain f4

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#660]
We typically use glowing green for bootloader mode, but the brain f4 is glowing blue.

**Comment by jamesadevine** [comment]
I don't think we do... Check your other boards?

**Comment by pelikhan** [comment]
Adafruit CPX uses green.

**Comment by jamesadevine** [comment]
It is aligned with the colour of the bootloader of our jacdac modules.

**Comment by pelikhan** [comment]
Why are we using a different bootloader color than other MakeCode? This is unecessarily confusing.
(title updated)

**Comment by jamesadevine** [comment]
Is there a convention for MakeCode?

**Comment by pelikhan** [comment]
Adafruit CPX uses green. In Arcade, it's all over the place.

Actually blue is the documented color. Alea jacta est.

![image](https://user-images.githubusercontent.com/4175913/134341428-0f1300c0-1293-4a88-97a9-344a5a716c04.png)

**Comment by jamesadevine** [comment]
Hahaha, I'm wiping my brow because at least I don't have to reprogram all those bootloaders...
