### ISSUE TITLE
Sample with button via micro:bit edge connector and croc clips.

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#661]
Could we create the following sample:

* Create a button via P0 (or P1, P2)
* Map to Jacdac Button service
* Button triggers by connecting P0 (or P1, P2) to ground

This would allow people to build custom Jacdac buttons with just croc clips.

**Comment by pelikhan** [comment]
The button server implementation in micro:bit is out of date. I would rather not push this kind of "create your own server" scenario.

**Comment by jamesadevine** [comment]
It's not a create your own server scenario, it is a create your own button scenario. We need a story for people in India who won't be able to get a kit, but can purchase a micro:bit and some croc clips.

Do you think button server support is unreasonable?

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-jacdac/commit/2b3f84747681c5c3dbaad015927ec6e3c03cd3bf

**Comment by pelikhan** [comment]
To be clear, the micro:bit v2 would act as a button server is that correct?

**Comment by tballmsft** [comment]
https://github.com/microsoft/pxt-jacdac/commit/37eae43a509ca690d136793213cc814536b94208
