### ISSUE TITLE
relay simulator and event handler terminology don't match

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#663]
A closed relay corresponds to 'on' and an open relay corresponds to 'off'. This is confusing, since the simulator uses 'closed' and the event handlers use 'on' and 'off'

```
modules.relay1.onOn(() => {
    basic.showString("Closed")
})

modules.relay1.onOff(() => {
    basic.showString("Open")
})
```

 Suggest we rename constently with 'open/closed' or 'on/off' terminology. I prefer the latter.

**Comment by pelikhan** [comment]
@jamesadevine can we do a review of the spec?

**Comment by pelikhan** [comment]
Spec updated. Needs probably a bit more review to encode pole/throw info.
