### ISSUE TITLE
test keyboard on stmf4

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#666]
Ensure keyboard extension work on brain f4

**Comment by jamesadevine** [comment]
The F401 only has 3 eps @pelikhan. You will have to disable hf2 if you want mouse and keyboard on a single binary

**Comment by mmoskal** [comment]
right now, keyboard-only doesn't work; the set idle, set protocol commands go through, but on set report, for whatever reason we hang here https://github.com/lancaster-university/codal-stm32/blob/master/src/USB.cpp#L358 when writing the confirmation ZLP

**Comment by mmoskal** [comment]
should be fixed in maker  v0.15.26

as for end points - 3 end points is enough for keyboard+mouse+hf2 but it was misconfigured; should be fixed now - you can have both keyboard and mouse.

**Comment by jamesadevine** [comment]
Awesome, thank you @mmoskal
