### ISSUE TITLE
opening a MakeCode sample from docs doesn't get latest jacdac

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#667]
Repro:
- visit https://microsoft.github.io/jacdac-docs/clients/makecode/extensions/potentiometer/
- press "Try in MakeCode" 
- note that program doesn't work
- See in explorer that it is not bound to latest jacdac

![image](https://user-images.githubusercontent.com/10767146/134423835-fa4cf31c-e5d6-41a9-a39f-0653d7eb10b7.png)

- update the jacdac in explorer
- see that program works
-

**Comment by pelikhan** [comment]
Fixed.
