### ISSUE TITLE
block for onConnected dropdown not correct

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#668]
See https://microsoft.github.io/jacdac-docs/clients/makecode/extensions/lightlevel/

Notice the JavaScript code is 

![image](https://user-images.githubusercontent.com/10767146/134445032-3ebb54b6-5ef4-4429-8eab-eaa8830e288b.png)

But the block rendering shows 'logger' in the 'onConnected' block

![image](https://user-images.githubusercontent.com/10767146/134445128-8700fa09-e561-4e98-bf66-a32f85d4b5de.png)

**Comment by pelikhan** [comment]
Weird….
________________________________

**Comment by pelikhan** [comment]
Note: light level works great with. Plotbargraph

**Comment by pelikhan** [comment]
This is some obscure bug. Looks like the list of fixedInstances is not populated correctly.

**Comment by pelikhan** [comment]
My hunch is this is a tricky one so we'll have to maybe do something else for those onConnected callbacks.

**Comment by tballmsft** [comment]
it's fine when loaded into the editor.

**Comment by pelikhan** [comment]
Yes something very weird
________________________________

**Comment by pelikhan** [comment]
This won't be fixed for the hack.

**Comment by pelikhan** [comment]
@tballmsft take a screenshot if needed for now.
