### ISSUE TITLE
Button hold crashes micro:bit oob

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#675]
Holding a G0 button for a long time some times crashes the micro:bit

**Comment by jamesadevine** [comment]
[trace.jd (1).txt](https://github.com/microsoft/jacdac/files/7219583/trace.jd.1.txt)

Trace attached

**Comment by jamesadevine** [comment]
(probably sound)

**Comment by tballmsft** [comment]
yes, i experienced this too.

**Comment by pelikhan** [comment]
Fixed.
