### ISSUE TITLE
F4 brain usb server needs to blink

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#677]
It's not clear that the F4 brain is working when in app mode. Please blink LED like other jacdac modules (if it is easy).

**Comment by pelikhan** [comment]
You mean the short green link when connected to bus? @jamesadevine 

https://microsoft.github.io/jacdac-docs/reference/led-status/#connected-to-bus

**Comment by jamesadevine** [comment]
Yes, exactly

**Comment by jamesadevine** [comment]
This is great! All flashed, and we're now good to go tomorrow.

Thanks everyone!
