### ISSUE TITLE
User guide for connecting F4 brain.

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#679]
F4 brain is a bit confusing to use, we need to document how to connect it to the bus.

@mmoskal is it possible to configure the brain to always boot into app if present, without reprogramming all the bootloaders on the boards?

**Comment by mmoskal** [comment]
You can update bootloader with uf2, so it's not very difficult. Would you like it to be app on first power-up and then go to flashing mode on first reset?

**Comment by jamesadevine** [comment]
@mmoskal see https://github.com/microsoft/jacdac/issues/682

**Comment by pelikhan** [comment]
Not clear what i should be doing here.

**Comment by pelikhan** [comment]
Raising this to p0 since this is a firmware change.

**Comment by jamesadevine** [comment]
We can beef up user guide later on.
