### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#68]
Models are commonly tagged to enable search, grouping, etc...

I'm proposing to align to https://project-haystack.org/doc/TagModel as far as the syntax.

**Comment by pelikhan** [comment]
frontmatter is quite common in markdown documents. https://ansonlowzf.com/markdown-front-matter/

**Comment by mmoskal** [comment]
Yeah, front matter is really good idea to make the .md files more standard.

I still don't understand how would we align with haystack.

**Comment by pelikhan** [comment]
We'll add this when we need it.
