### ISSUE TITLE
Make F4 Brain bootloader boot into app if app exists

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#682]
Bootloader needs to boot into app by default to make the user experience more understandable

**Comment by mmoskal** [comment]
fixed in bootloader 2.8.2; attached is file to update bootloader (you can also build yourself) @jamesadevine 

[flasher.zip](https://github.com/microsoft/jacdac/files/7228639/flasher.zip)

**Comment by jamesadevine** [comment]
Cheers, programmed!
