### ISSUE TITLE
Role manager not binding variables to server correctly

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#683]
![image](https://user-images.githubusercontent.com/4742697/134557558-401ea04a-a2ee-40f6-96ba-d0c48e2ee4a9.png)

**Comment by tballmsft** [comment]
repro steps?

**Comment by pelikhan** [comment]
Probably fixed by https://github.com/microsoft/pxt-jacdac/commit/45e0d7ca60e0e01bfa2c6d5902e0736056e1dc74
