### ISSUE TITLE
pxt-jacdac flex sensor client?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#684]
We will need client code for the flex sensor in pxt-jacdac

**Comment by pelikhan** [comment]
Looks like we have one. Did it not find it?

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/134570541-0e9c7722-18bf-431f-91dc-cdb15aee57d2.png)

**Comment by jamesadevine** [comment]
Sorry, thought we didn't do it... Thanks peli!
