### ISSUE TITLE
Rotary control LED blinking with dashboard?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#687]
What is the deal with the rotary control status light randomly blinking when connected to the micro:bit?

packet trace attached
[trace.jd (1).txt](https://github.com/microsoft/jacdac/files/7220480/trace.jd.1.txt)

**Comment by jamesadevine** [comment]
https://github.com/microsoft/pxt-jacdac/blob/ee67e596d250c03c5004c4e203e8b0669033c6f5/routing.ts#L853

I guess it's this? Why does it only effect the rotary control module? Can we turn it off?

**Comment by pelikhan** [comment]
We have this in the spec: https://microsoft.github.io/jacdac-docs/reference/led-status/#connected-to-brain

**Comment by jamesadevine** [comment]
This is the first time I've seen this in action...

**Comment by jamesadevine** [comment]
Can we disable for hackathon? I do not have time to reprogram every single module.

**Comment by pelikhan** [comment]
Could you give more details about the problem?

**Comment by jamesadevine** [comment]
If the rotary encoder is the only module with this feature enabled, it looks like the module is malfunctioning.

James
________________________________

**Comment by jamesadevine** [comment]
The feature is inconsistently implemented across modules. For example padauk modules do not blink on connect.  IMO it is confusing and should be disabled.

**Comment by pelikhan** [comment]
So basically all new modules don't support status light? Because MakeCode will do blink on anything that supports it.

Looks like the light sensor does not support status light.
![image](https://user-images.githubusercontent.com/4175913/134683344-513e9dd4-242c-4ccb-b75d-d9aa58561c76.png)

**Comment by jamesadevine** [comment]
All padauk modules do not implement status light. All stm modules do.

**Comment by pelikhan** [comment]
Disable blink in makecode. This needs to be reenabled or spec updated.
