### ISSUE TITLE
`reset_in` not keeping to time

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#688]
Devices reset due to the dashboard not keeping up with `reset_in` packets:

<img width="1166" alt="Screenshot 2021-09-23 at 21 15 14" src="https://user-images.githubusercontent.com/4742697/134577466-b0816e6b-abb1-4569-a415-519a064d48c0.png">

Trace attached
[trace.jd (2).txt](https://github.com/microsoft/jacdac/files/7220622/trace.jd.2.txt)

**Comment by pelikhan** [comment]
Are there too many packets?

**Comment by pelikhan** [comment]
sending every announce now https://github.com/microsoft/jacdac-ts

**Comment by pelikhan** [comment]
@jamesadevine could you give more details about this issue. "not keeping up"?

**Comment by jamesadevine** [comment]
It looked like the reset in 2s was sent and then 3-4 seconds later the next reset in 2s was sent. I thought this might be why the rotary module is resetting.

**Comment by pelikhan** [comment]
We are now sending reset every anounce packets. Let's test again on the next hack.

Use "grouping:false" in the packet editor to disable packet grouping which might be messing with your head here.
