### ISSUE TITLE
update drop list in jacdac-msr-modules

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#689]
@jamesadevine could you update this list https://github.com/microsoft/jacdac-msr-modules/blob/main/Makefile#L12 to contain the modules that we're shipping to people, or ones that many of us have? I made a stab, but I'm not sure how good that is.

**Comment by jamesadevine** [comment]
Looks good, just added the mikrobus module: https://github.com/microsoft/jacdac-msr-modules/pull/34

**Comment by pelikhan** [comment]
I am not strictly enforcing being in the catalog YET but I will once we add the hackathon modules to it.

**Comment by jamesadevine** [comment]
It will be done

**Comment by pelikhan** [comment]
There is no firmware update currently for newer modules because of this.
