### ISSUE TITLE
need drop-down for event type to reduce block clutter

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#690]
For services with lots of events, we get a ton of blocks in MakeCode. See, for example, the accelerometer extension (below). Should combine into a single block with dropdown whenever possible.

![image](https://user-images.githubusercontent.com/10767146/134613096-aabedc02-7b40-48bc-a874-f40581c94d70.png)

**Comment by pelikhan** [comment]
Best implemented "manually" for now.
