### ISSUE TITLE
microbit as Jacdac server problems

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#693]
- [x] dashboard keeps losing device
- [x] light level not working
- [x] button hold event not generated
- [x] pins P0, P1, P2 as button not working at all
- [x] logo, pressure not working, although events are
- [x] logo, hold not working

**Comment by pelikhan** [comment]
Also a copy paste issue for touch buttons (    //% fixedInstance whenUsed block="button A" <---)
