### ISSUE TITLE
Exception in OOB experience

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#697]
@sehodges sees an 999 error on the OOB experience:

https://github.com/microsoft/pxt-vm-built/blob/63b98eeb65f799f581247ace9703679e46aaa8e1/pxtbase.h#L289

Looks like there is an exception being triggered that is not handled. Could indicate some dragons.

It was triggered by clicking buttons, and unplugging and plugging the rgb led ring.

**Comment by tballmsft** [comment]
Repro?

**Comment by jamesadevine** [comment]
The best repro is described above. Maybe ask @sehodges for more detail?

**Comment by pelikhan** [comment]
@tballmsft are you looking at this?

**Comment by tballmsft** [comment]
I can't repro.

**Comment by tballmsft** [comment]
unable to reproduce. downgrading P1
