### ISSUE TITLE
firmware.hex file on kit is wrong

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#707]
Repro:
- visit https://microsoft.github.io/jacdac-docs/hardware/kit/oob/
- download firmware.hex
- See that it is only 1KB

![image](https://user-images.githubusercontent.com/10767146/135129012-bf8b708b-55cc-43d6-ad4c-232d9bbd137d.png)

**Comment by pelikhan** [comment]
Fixed with https://github.com/microsoft/jacdac-docs/commit/31799f71cbc0172ff6c2ddb032c00606a8a2fb4f
