### ISSUE TITLE
TOC for Extensions not in alphabetical order

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#709]
See title above and snapshot below

![image](https://user-images.githubusercontent.com/10767146/135163166-e2b33bcc-55e7-4dc8-828e-4f093082e1a6.png)

**Comment by pelikhan** [comment]
fixed by https://github.com/microsoft/jacdac-docs/commit/6cbc978035e4cc8d9c7b204c717699740b4c16a5
