### ISSUE TITLE
module markdown -> module json

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#71]
Since we expect module author to use the GUI, there isn't much value in having a markdown representation. Using JSON natively.
- [ ] add support for localized names, descriptions

**Comment by mmoskal** [comment]
I guess the other point is that we're not really using markdown features here - the only markdown fragment is description which is plain text with no formatting, and which needs to be localizable anyways

cc @tballmsft

**Comment by tballmsft** [comment]
makes sense to me.
