### ISSUE TITLE
MakeCode Jacdac projects

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#710]
Put a list of simple projects here (check them off as completed).  There should be a single page per project, under the directory:

https://github.com/microsoft/jacdac-docs/tree/main/src/pages/clients/makecode/projects 

We already have a sample per module, so a *project* should use >1 modules to achieve some simple objective.  DO NOT use more than one instance of a module in one of these projects (such projects should be put in https://github.com/microsoft/pxt-jacdac, as they require a full MakeCode project):

- [ ] button controls single LED (on/off); add slider to previous example to control brightness of LED
- [ ] make a mouse from joystick and buttons
- [ ] https://stackoverflow.blog/2021/09/28/become-a-better-coder-with-this-one-weird-click/

**Comment by pelikhan** [comment]
Rebuild a mouse from Jacdac modules: joystick + 1 button -> mouse.

**Comment by jamesadevine** [comment]
https://makecode.microbit.org/_fa5aKUgdu0fH 

Slider as scroll demo

**Comment by jamesadevine** [comment]
joystick + 2 buttons:

https://makecode.microbit.org/_J5ki7gLV85Vz
