### ISSUE TITLE
joystick docs don't decompile

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#712]
![image](https://user-images.githubusercontent.com/4175913/135212386-a609bcf7-e0cf-42d3-aad5-c10bb098fd62.png)

**Comment by pelikhan** [comment]
JoystickButtons is a bitflag.

**Comment by tballmsft** [comment]
it decompiles - it's just grey blocks - what do you suggest?

**Comment by pelikhan** [comment]
Always write your samples using the bloc editor -- or you can guarantee that your typescript is weiteable in blocks.

I've added a block to query the button state., isButtonDown

**Comment by tballmsft** [comment]
Fixed in https://github.com/microsoft/jacdac-docs/pull/110
