### ISSUE TITLE
distinguishing simulated/physical modules

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#718]
Testing the program:  https://makecode.microbit.org/_129hti4zocLH

The button simulator is not responding to mouse clicks

![image](https://user-images.githubusercontent.com/10767146/135340189-99129ea6-59cd-4115-9c85-b7144a3d6df1.png)

**Comment by tballmsft** [comment]
Aha, this was because I had micro:bit plugged in and the button was a twin of a physical button. Confusing!

**Comment by tballmsft** [comment]
It works when no hardware plugged in, but looks just the same. Can we have a way to distinguish simulated from physical module?

![image](https://user-images.githubusercontent.com/10767146/135341964-f20bca19-f7f8-48fb-9c9c-5e3fac2ba635.png)

**Comment by tballmsft** [comment]
When I have both simulator and device button, I see the difference:

![image](https://user-images.githubusercontent.com/10767146/135342100-ab46e59d-bd67-4c7a-ac08-f3d8dfefd47d.png)

**Comment by pelikhan** [comment]
The button UI only responds to the physical button. This seems to be by design.

**Comment by pelikhan** [comment]
All physical sim are under "devices", all others are under simulators. They also have different color typically albeit in this case it is not visible.

I can show a tooltip.

**Comment by tballmsft** [comment]
that would be good.
