### ISSUE TITLE
role manager not binding to physical or simulated button

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#719]
With  the program below, I have the micro:bit in proxy mode, but the micro:bit simulator is not responding to physical button press (the character always remains U, it never transitions to D on press of physical button). Note that the digital twin of the physical button is responding to button press:

![image](https://user-images.githubusercontent.com/10767146/135342818-2b6103e8-73ea-49c7-8e89-49097a024b6f.png)

**Comment by tballmsft** [comment]
OK. the same problem is occurring without hardware for the program:

```
basic.forever(() => {
    if (modules.button1.pressed())
        basic.showString("D")
    else
        basic.showString("U")
})
```

**Comment by pelikhan** [comment]
Please add shared project to githubs.

**Comment by tballmsft** [comment]
https://makecode.microbit.org/_7W7RWeTJ2AMU

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/pxt-jacdac/commit/45e0d7ca60e0e01bfa2c6d5902e0736056e1dc74
