### ISSUE TITLE
Device Registration of passive PCB

### ISSUE THREAD

**Issue by GakureKaruri** [microsoft/jacdac#720]
No FW on passive PCB modules. FW repository URL should be optional.

**Comment by pelikhan** [comment]
Fixed.

**Comment by GakureKaruri** [comment]
Without the URL the register device button is greyed out.

**Comment by GakureKaruri** [comment]
![image](https://user-images.githubusercontent.com/35522404/135589359-014b2ffa-4ae1-467c-b0a3-92783ce4718f.png)

**Comment by pelikhan** [comment]
do you have an image?

**Comment by GakureKaruri** [comment]
Fixed
