### ISSUE TITLE
define up/down left/right for all modules

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#722]
- when the accelerometer led is facing up (to the ceiling), the firmware is generating a face-down and event, and vice-versa
- according to spec, lying flat should give 0, 0, -1. but in the dashboard we got 0, 0, 1, where "flat" means "led is facing ceiling", as above

The hardware spec should say something about the position of the LED, because there's a plug on both sides. 

Need to define what "top" of board means, perhaps. If there is one plug, that's the top; otherwise, it's the side with the plug closest to the LED...

**Comment by tballmsft** [comment]
we should talk about the expected orientation (which way is the LED facing when I test). When the Led is facing me, Tilt events make sense. When it's facing away, they are opposite.

**Comment by tballmsft** [comment]
according to spec, lying flat should give 0, 0, -1. but we got 0, 0, 1, where "flat" means "led is facing ceiling".

**Comment by tballmsft** [comment]
We need to probably be more specific about left/right, up/down with respect to the LED.

**Comment by pelikhan** [comment]
Yes we need to be verrrryvspecific
________________________________

**Comment by jamesadevine** [comment]
Is the accelerometer firmware up to date? If you are using an out of date firmware, I was not particularly careful with the orientation. Later modules have the orientation as per the silk on the module.

**Comment by jamesadevine** [comment]
And that, imo, is how the user determines face up/face down

**Comment by jamesadevine** [comment]
If this is specific for our modules, we can for sure say "top == side with LED" for a given module (even then we have not been consistent across all our designs on LED position. However, other manufacturing partners are not going to have the same standards/positioning so that statement will not be universally true (e.g. all accelerometer modules certainly won't have the LED in a prescribed position).

**Comment by GakureKaruri** [comment]
MH1 marker is used to identify up/down of the modules. This has been implemented on the recent designs.

**Comment by GakureKaruri** [comment]
![MH1 marker](https://user-images.githubusercontent.com/35522404/135486987-0b7b9f70-85df-4ae3-b0ed-80ff9c83aee5.png)

**Comment by pelikhan** [comment]
@GakureKaruri @jamesadevine @sehodges we should consider adding a page that lists all the Jacdac specific markers, their names, what they look like and their role.

**Comment by tballmsft** [comment]
Yes, please. I need this for testing.

**Comment by tballmsft** [comment]
@jamesadevine - accelerometer firmware is up-to-date. Will you confirm the bug and please fix?

**Comment by jamesadevine** [comment]
What is the accelerometer board revision?

James
________________________________

**Comment by pelikhan** [comment]
@tballmsft post trace from web site which collects a bunch of info

**Comment by tballmsft** [comment]
@jamesadevine - how do I tell?

**Comment by jamesadevine** [comment]
Should be good, assuming fw is *actually* up to date. Not sure accelerometer 0.2 is in drop targets... https://github.com/microsoft/jacdac-msr-modules/blob/154ba036a73c80ab1a73211a3617f8824fd18cc1/targets/jm-accelerometer-30-0.2/profile/accelerometer.c

**Comment by tballmsft** [comment]
device: 
  id: DX19 (0x76f2fe8a92b285a8)
  product: microsoft-research-jmaccelerometer30v02 (0x33f9b086)
  firmware_version: v0.16.7
  services:
    accelerometer (0x1f140409)
