### ISSUE TITLE
micro:bit connected by WebUSB but getting error

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#729]
Uncaught (in promise) Error: Device in use or not found.
    at o.connectAsync (pxtapp.js:1)
    at async DAPWrapper.reconnectAsync (editor.js:3313)

![image](https://user-images.githubusercontent.com/10767146/135540555-e7f31b02-cfb6-4936-b317-956e3ac12669.png)

**Comment by tballmsft** [comment]
A browser refresh got back to a good state.

**Comment by tballmsft** [comment]
Can't repro easily.

**Comment by pelikhan** [comment]
Might be better now that we actively disconnect.
