### ISSUE TITLE
"ADD BLOCKS" button in multi-editor

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#732]
See screenshot below. Also it seems I can't connect to hardware from the dashboard, when run in the multieditor.

<img width="1902" alt="Screen Shot 2021-09-30 at 4 46 29 PM" src="https://user-images.githubusercontent.com/10673976/135545364-55755add-7f64-452f-ad61-5d3a1d20fef3.png">

**Comment by pelikhan** [comment]
Can you use https://microsoft.github.io/jacdac-docs/clients/javascript/devtools instead?

**Comment by mmoskal** [comment]
Sure thing - so I assume this is only really meant for makecode.
