### ISSUE TITLE
Site broken?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#734]
I'm trying to use the site today with V2 OOB experience, downloaded from pxt-jacdac just now.

It seems packets are not being processed, and as a result simulators do not appear to be working as before:

![image](https://user-images.githubusercontent.com/4742697/135613425-3dae27ea-b93c-4aa0-b4f2-72b2ce198343.png)

The above is with my micro:bit and a temp/humidity module connected...

Trace:
[trace.jd (2).txt](https://github.com/microsoft/jacdac/files/7266784/trace.jd.2.txt)

**Comment by jamesadevine** [comment]
site version: 7279ea82

**Comment by pelikhan** [comment]
@mmoskal i've reverted jacdac-ts prior to https://github.com/microsoft/jacdac-ts/commit/99deaeb128720b2449ad5d35a75c6199cb4f8721 which fixes the issue.

**Comment by pelikhan** [comment]
I've reverted it https://github.com/microsoft/jacdac-ts/commit/3eef086c9a196e7ba83de335c0332b354305db78 so we get more time to investigate.

**Comment by jamesadevine** [comment]
Thanks!

**Comment by pelikhan** [comment]
@mmoskal I've fixed our test suite to fail when the bus sees a ERROR event ( https://github.com/microsoft/jacdac-ts/commit/89d80646bb9a64444fd799ffe4209d452091211d) so the test suite fails now with invalid packets.

Also, you can start the uploader simulator from the simulator list in the dashboard (not visible yet, but runs in the background)
