### ISSUE TITLE
more meta-data in device description (orientation)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#742]
The service specification is not the place to describe module-specific features, such as orientation. We need some description in the device description that ties together the hardware, service and supporting firmware to present a complete picture of how the device works.

**Comment by tballmsft** [comment]
For an example of what I mean, see new page:

https://microsoft.github.io/jacdac-docs/clients/makecode/extensions/potentiometer/

This page refers to the JM Slider v1.1 so that it is clear which end of the slider corresponds to the position = 100, and which end corresponds to the position = 0.

Essentially, we have a constraint between the service and the module that needs to be specified. The service is not the right place for this information (and neither is the above page). This constraint should be mentioned in the device description for the JM Slider v1.1.

**Comment by pelikhan** [comment]
isn't it a matter of updating the silk to show where 0/100 are?

**Comment by tballmsft** [comment]
well, that would be one way... but there are three axes.
