### ISSUE TITLE
use lower case file names, snakified for .mdx files

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#749]
To keep consistent in jacdac docs: alll file names that generate routing are snakified, lower cased. 

https://github.com/microsoft/jacdac-docs/commit/55fd0e735e9c15dc10b6956c4096e16ad811a538

**Comment by pelikhan** [comment]
Invalid link alternate and old .JPG Should be cleaned out
________________________________

**Comment by pelikhan** [comment]
looks like there is an error In the markdown. Also deleted old u used files.

**Comment by tballmsft** [comment]
old files were deleted. fixed link
