### ISSUE TITLE
downloaded program doesn't work when disconnected

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#750]
Try this program with either the bar or ring.  Download the program to the micro:bit. 

https://makecode.microbit.org/_6t8MkcT00EM8

Notice that the program runs fine when the micro:bit is connected to MakeCode. 

- Now, get rid of MakeCode and plug and unplug the micro:bit, so it is not connected to WebUSB, or power it by battery.
- Note that the program doesn't work now.

The code is super simple and being used an example in doc:
```
input.onButtonPressed(Button.A, () => {
    modules.ledPixel1.setAll(0)
    let n = modules.ledPixel1.numPixels()
    for(let i = 0; i <= n - 1; i++) {
        modules.ledPixel1.setPixel(i, 0x00ff00)
        basic.pause(200)
    }
})

input.onButtonPressed(Button.B, () => {
    modules.ledPixel1.setAll(0)
    let n = modules.ledPixel1.numPixels()
    for (let i = 0; i <= n - 1; i++) {
        modules.ledPixel1.setPixel(i, 0x0000FF)
        basic.pause(200)
    }
})
```

**Comment by tballmsft** [comment]
Another need for reliable commands...

**Comment by pelikhan** [comment]
@mmoskal it seems that get num_pixels is always ignored in the disconnected case

![image](https://user-images.githubusercontent.com/4175913/135921508-383973d4-7c19-42e9-a5d4-e25c6731ccc4.png)

**Comment by pelikhan** [comment]
Add ?passive=1 to prevent the web site to send any packet.
