### ISSUE TITLE
setPixel command sometimes ignored

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#751]
Download this program to hardware and try out on hardware:

https://makecode.microbit.org/_6t8MkcT00EM8

Note that sometimes a setPixel command is lost.

**Comment by tballmsft** [comment]
Also see (perhaps related) issue https://github.com/microsoft/jacdac/issues/750

**Comment by tballmsft** [comment]
Peli, it works offline now, but I am still seeing the behavior where a setPixel command is ignored, leaving a light in the strip off:
```
input.onButtonPressed(Button.A, () => {
    modules.ledPixel1.setAll(0)
    let n = modules.ledPixel1.numPixels()
    for(let i = 0; i <= n - 1; i++) {
        modules.ledPixel1.setPixel(i, 0x00ff00)
        basic.pause(200)
    }
})

input.onButtonPressed(Button.B, () => {
    modules.ledPixel1.setAll(0)
    let n = modules.ledPixel1.numPixels()
    for (let i = 0; i <= n - 1; i++) {
        modules.ledPixel1.setPixel(i, 0x0000FF)
        basic.pause(200)
    }
})
```

**Comment by pelikhan** [comment]
We are losing packets probably. Needs to be traced with a logic analyzer @mmoskal
