### ISSUE TITLE
rotary encoder position rotation should be indicated on the silk

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#754]
Silk should be selfexplanatory w.r.t to rotation rate.

**Comment by pelikhan** [comment]
@tballmsft

**Comment by tballmsft** [comment]
@pelikhan what do you mean? the number of clicks per full rotation

**Comment by pelikhan** [comment]
numbers just like a safe lock?
________________________________

**Comment by jamesadevine** [comment]
I think you mean around the external of the dial it would show each number (like a clock). Quite hard to approximate, but could maybe be done.

Might be a bit confusing as the behaviour is accumulative, not absolute like a clock (e.g. it is current value + number of clicks)

James
________________________________

**Comment by pelikhan** [comment]
Maybe just an arrow + number?
________________________________

**Comment by pelikhan** [comment]
Not critical on rotary encoder.
