### ISSUE TITLE
jacdac-docs resets micro:bit when flashing

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#756]
Depending on how you do flashing, the site might interrupt the micro:bit during a flashing process initiated outside of the web browser.

For example, if you drag-and-drop a hex file onto the micro:bit drive with the site connected, it is highly likely that a reset will come from the browser and corrupt the flashing process. This creates a broken user experience, which we want to avoid.

Can we revisit the need for this reset behaviour?

**Comment by pelikhan** [comment]
Fixed.
