### ISSUE TITLE
ESP32 listed in the connect device dialogue?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#762]
Why is the ESP32 brain listen in the connect hardware dialog?

This is going to confuse people to no end during hackathon. It implies there is a mysterious ESP32 connected to their PC.

For my understanding, was this dialogue created to prevent users from having to know about webserial vs. webusb vs. BLE? 

![image](https://user-images.githubusercontent.com/4742697/135869571-5b938e4b-3de9-436f-b714-3c6794d0b331.png)

**Comment by pelikhan** [comment]
All connecteable brains should be listed on that dialog.

**Comment by jamesadevine** [comment]
You mean we will list all brains here in the future?

**Comment by pelikhan** [comment]
But we could mark certain hw as experimental and hide it

**Comment by pelikhan** [comment]
Anything we can connect to.

**Comment by jamesadevine** [comment]
I'm not against this dialogue, I just think it's another step to describe for hackathon.

**Comment by pelikhan** [comment]
ESP marked as experimental.
