### ISSUE TITLE
device twin for HID keyboard has problem

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#770]
It is not letting me specify the "Send Key event" (see greyed out in snapshot below):

![image](https://user-images.githubusercontent.com/10767146/136109796-2d9689cd-f7dd-4d87-91bf-4367ae6a0695.png)

Use this program:

https://makecode.microbit.org/_9WCdqkbz9FRy

**Comment by pelikhan** [comment]
You need a button or something on the bus
________________________________

**Comment by pelikhan** [comment]
You can bind an event from another module to send the key. Otherwise press “send key” to execute it
________________________________

**Comment by pelikhan** [comment]
Remove this event, confusing.
