### ISSUE TITLE
animate to black not working

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#774]
Try this program on micro:bit with single LED: https://makecode.microbit.org/_HLc7eWdYUdb3

- A button - animates to red
- B button - animates to blue
- A+B - should turn off LED, but it doesn't

I see the same problem when running program in simulator against physical module, so 
could be a firmware problem. The animate to black doesn't work only when the delay is 0.  

```
input.onButtonPressed(Button.A, function () {
    modules.led1.animate(0xff0000, 28)
})
input.onButtonPressed(Button.AB, function () {
    modules.led1.animate(0x000000, 0)
})
input.onButtonPressed(Button.B, function () {
    modules.led1.animate(0x007fff, 58)
})
``

**Comment by tballmsft** [comment]
I looked at the pxt-jacdac code - when you set second parameter of animate to 0, it actually sends 0x01:

```
CMD animate {     to_red: 0x0     to_green: 0x0     to_blue: 0x0     speed: 0x1 }; usb
```

For full trace, see:
[trace.jd (5).txt](https://github.com/microsoft/jacdac/files/7307508/trace.jd.5.txt)

**Comment by pelikhan** [comment]
Should be fixed by https://github.com/microsoft/pxt-jacdac/commit/09ffb545957a9ce423c22b04a965fe8440fdde02
