### ISSUE TITLE
micro:bit simulator printing to console on button press

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#776]
sim.js:4378 down 1
sim.js:4378 down 1
sim.js:4378 down 1
sim.js:4378 down 1
sim.js:4378 down 1
sim.js:4378 down 2
sim.js:4378 down 2
sim.js:4378 down 2
sim.js:4378 down 2

**Comment by pelikhan** [comment]
pxt bug

**Comment by tballmsft** [comment]
really? never saw it before...
