### ISSUE TITLE
Access switch input does not present a service if no access switch is connected

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#789]
bug or a feature?

**Comment by pelikhan** [comment]
sounds like a feature

**Comment by jamesadevine** [comment]
I think so, but I think Jon C disagreed!

**Comment by jamesadevine** [comment]
We could just run some sort of debug service with a message saying something like "connect a switch to me!"

**Comment by pelikhan** [comment]
The problem is that the service changes based on the hardware right?

**Comment by jamesadevine** [comment]
Yes, but with nothing connected it sits in a loop with a pulsing yellow LED. There is no other form of feedback in this mode.

**Comment by pelikhan** [comment]
Then having a generic "alert" service that will display a message would be fine.
