### ISSUE TITLE
configuration services

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#79]
Services may have a configuration service that allows to provide custom hardware configuration. This relationship should be in the specification.

For example,

* TCP is the common service
* WIFI / Ethernet are 2 instances of the configuration services

**Comment by mmoskal** [comment]
We expect this pattern to be used by module manufacturers - they would implement a vanilla temperature service and their own BBQ-thermometer config service.

**Comment by pelikhan** [comment]
Configuration services are instances of auxiliray services.
