### ISSUE TITLE
Better handling of USB resource contention

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#794]
Users get confused when two tabs try to grab the same USB interface. The error message "unable to claim interface" could be easier to understand. But broadly, I think we need a better way to handle resource contention between tabs running the jacdac stack.

**Comment by pelikhan** [comment]
Duplicated of https://github.com/microsoft/jacdac/issues/786 probably

**Comment by tballmsft** [comment]
@pelikhan - has this been resolved?

**Comment by dsssssssss9** [comment]
If you are having problems with this i have found a work around ,,,, at least it works for me

see the following video >>>>
https://youtu.be/tJb2mEvND8Q
