### ISSUE TITLE
network matching

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#80]
A user should be able to designer a matcher for the registers on the bus (See MQTT rules).

For example, when defining a device twin, matcher on device/service that defines the twin.

- star matchers for devices
- device id precise matching
- role-based matching
- role-based "starts with"

For services, we do precise match on service class.

If a device has multiple instances of the requested service, pick the first service or have an optional match to select the "ith" service.

- [ ] also need to be able to specify registers, events, commands

**Comment by tballmsft** [comment]
@pelikhan - is this a new service? It is built on top of protocol, so removing the protocol label..

**Comment by pelikhan** [comment]
This is application side so yes remove protocol
