### ISSUE TITLE
jacdac dev tools: responds to gamepad when not focused

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/jacdac#808]
The jacdac dev tools will automatically add a gamepad virtual device when it detects physical gamepad activity. But it will do this even when the window is not focused. In my project I'm adding jacdac support to an app that uses gamepad, and when I return to the dev tools I see a new control was auto-added. This is interruptive because once the new control is there, my project will start sending input from it to the app that I'm also controlling with the physical gamepad. It's receiving double input.

Auto-addition of the gamepad control to the simulator environment seems overly helpful to me. It makes assumptions that may not be true. I'd prefer it didn't to this, or have a way to turn it off.

**Comment by pelikhan** [comment]
fixed in https://github.com/microsoft/jacdac-docs/commit/d5bd03602dc375ace6540537f0fb51da2b331110 15 min to live

**Comment by eanders-ms** [comment]
nice!
