### ISSUE TITLE
remove temperature register

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#83]
This register is more confusing than others. Do we really needed?

**Comment by mmoskal** [comment]
Control service?

**Comment by pelikhan** [comment]
Sorry yes control service.

**Comment by jamesadevine** [comment]
A good reason for removing temperature from control is that it is not common to all microcontrollers. It also represents the silicon temperature of the microcontroller, not the actual temperature of the environment, so it cannot be relied upon when programming.

**Comment by pelikhan** [comment]
we could replace it with a "hot" event

**Comment by jamesadevine** [comment]
Perhaps HOT could be a flag in an advertisement?

**Comment by pelikhan** [comment]
Renaming it to MCU temperature.

**Comment by mmoskal** [comment]
and it's already optional; hot is relative, most MCU will work all right at 80C, you just don't want to touch them...
