### ISSUE TITLE
Marking registers as internal

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#84]
When exposing jacdac to IoT, some registers are just not useful. We could eighter "export" register or "hide" some. It seems that we are leaning towards hiding and we could mark registers as "internal", e.g. only useful on the JD bus.

**Comment by jamesadevine** [comment]
Hey @pelikhan 

Do you have an example for me?

**Comment by pelikhan** [comment]
streaming_samples and interval for example (https://microsoft.github.io/jacdac-ts/services/_sensor)
