### ISSUE TITLE
uploader imprvoment

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#850]
- [ ] watchdog to detect that the jacdac bus is dead and reboot the device
- [ ] limit streaming interval to > 1s
- [ ] (nice to have: upload soil moisture to 1s interval)

**Comment by mmoskal** [comment]
What watchdog interval do want?

Right now I have it set to 30s and feed it whenever we manage to send a message to the cloud.

This will reset for (at least) the following failure modes:
* can't connect to WiFi
* can't connect to IoT Hub
* no sensors connected (we don't send empty messages)
* any other crash

The 30s is somewhat problematic when initially configuring the thing (and it resets under you).

**Comment by mmoskal** [comment]
The time limit is now 120s. We also feed the watchdog when connected to the dashboard in the website.

Deployed in uploader 0.8.0
