### ISSUE TITLE
Device twin de-sync when connected during "disconnect"

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#866]
**Describe the bug**

When temporarily disconnecting a device for as long as it takes for the "device lost" message to appear on the dashboard, after plugging it back in, it takes a few more seconds for the device twin to begin mirroring state again.

See this example gif:
![button-sim-desync](https://user-images.githubusercontent.com/4742697/144837211-b58295a3-581c-434c-90f8-4cfb11860727.gif)

After plugging the device back in, the disconnected message disappears, and I am continuously pressing the button. Note that it takes a few seconds for the device twin to begin to update again.

**Comment by pelikhan** [comment]
Could you attach the trace? I can't quite repro this one.

**Comment by jamesadevine** [comment]
here ya go!

[trace.jd.txt](https://github.com/microsoft/jacdac/files/7668118/trace.jd.txt)

**Comment by jamesadevine** [comment]
This is happening on windows FYI. I haven't checked mac

**Comment by jamesadevine** [comment]
@pelikhan Any updates on this?

**Comment by pelikhan** [comment]
the react layer is not updating after a restart is detected somehow

**Comment by pelikhan** [comment]
make sure to completely let it "die" in your demo for now
