### ISSUE TITLE
Intermittent micro:bit connection

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#868]
**Describe the bug**
A user is reporting that the micro:bit repeatedly connects/disconnects from website with latest OOB experience.

Here is the trace:
[trace.jd (1).txt](https://github.com/microsoft/jacdac/files/7703641/trace.jd.1.txt)

CC @mmoskal

**Comment by pelikhan** [comment]
I see the device restarted but unclear how to repro this. We don't have enough info about the makecode program to determine what's going on.
