### ISSUE TITLE
MicrobitV2 can't connect in dashboard

### ISSUE THREAD

**Issue by smfox10** [microsoft/jacdac#875]
1、I have downloaded the hex of jacdac with V2
2、I ues Chrome latest version 96.0.4664.110（64 位）
3、but MicrobitV2 can't connect in dashboard
![jacdac connect](https://user-images.githubusercontent.com/3880290/146636114-2d417e1a-4b9c-42b8-a6a2-e80812b6d9f1.gif)

I use zadig to replace the driver，But I ran into a problem again.
MicrobitV2 can connect in dashboard，I can't find the Microbit USB flash drive in the file manager.It is difficult to use both makecode and dashboard at the same time.This is too difficult for general users to use.

![image](https://user-images.githubusercontent.com/3880290/146636155-8a8b1399-72ab-424a-9fe5-1a1e142cac70.png)

![jacdac zadig](https://user-images.githubusercontent.com/3880290/146636118-fd872610-9e9f-4588-b932-a0d9cce3c96c.gif)

**Comment by pelikhan** [comment]
Right MakeCode or the dashboard don't know about each locking the device yet. This is something we need to fix.

I'm confused about having to use Zadig. The micro:bit v2 should just have worked in the dashboard.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: CCFIVE ***@***.***>
Sent: Saturday, December 18, 2021 1:21 AM
To: microsoft/jacdac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/jacdac] MicrobitV2 can't connect in dashboard (Issue #875)


1、I have downloaded the hex of jacdac with V2
2、I ues Chrome latest version 96.0.4664.110（64 位）
3、but MicrobitV2 can't connect in dashboard
[jacdac connect]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3880290%2F146636114-2d417e1a-4b9c-42b8-a6a2-e80812b6d9f1.gif&data=04%7C01%7Cjhalleux%40microsoft.com%7C9927e38848a84ab742b208d9c207c2fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637754160863987331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9k8tYJN3o2M2blx3qOndRoAgQXYnhq%2BuDYDh1fMcbec%3D&reserved=0>

I use zadig to replace the driver，But I ran into a problem again.
MicrobitV2 can connect in dashboard，I can't find the Microbit USB flash drive in the file manager.It is difficult to use both makecode and dashboard at the same time.This is too difficult for general users to use.

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3880290%2F146636155-8a8b1399-72ab-424a-9fe5-1a1e142cac70.png&data=04%7C01%7Cjhalleux%40microsoft.com%7C9927e38848a84ab742b208d9c207c2fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637754160863987331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dity4dWAqer7LOyLH7hh1y1F%2B6sPlSpPGGyND9OSz08%3D&reserved=0>

[jacdac zadig]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3880290%2F146636118-fd872610-9e9f-4588-b932-a0d9cce3c96c.gif&data=04%7C01%7Cjhalleux%40microsoft.com%7C9927e38848a84ab742b208d9c207c2fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637754160863987331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I7DSK6vWb4SFha2po06J%2BJsKg4S%2FNOvzU8IRdMdm7Oo%3D&reserved=0>

**Comment by tballmsft** [comment]
@pelikhan  - is this fixed now?

**Comment by pelikhan** [comment]
This is fixed as much as possible.
