### ISSUE TITLE
filter should be enabled by default when spinning simulators

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#877]
I just noticed there is a "search" (filter) feature when spinning simulators. It's very helpful because there is a million of them. Maybe we can enable it by default and focus the keyboard on it?

**Comment by mmoskal** [comment]
also, when filtered down to a few position the whole modal shrinks which is jarring

**Comment by pelikhan** [comment]
@mmoskal try again, should be better now.

**Comment by mmoskal** [comment]
better! can you focus the filter when the modal pops up?

**Comment by pelikhan** [comment]
I think this frowned upon for accessibility. The focus needs to go on the title so that the screen readers read it and provide a context to non-vision users. need to check.
________________________________

**Comment by mmoskal** [comment]
That definitely doesn't sound right - when you have a login page, the focus always (should) go to the login entry text box not to the title. Also if someone has trouble seeing I would rather have them use the filter than the screen reader start reading that enormous list.

**Comment by mmoskal** [comment]
you could also focus it when a key is pressed

**Comment by pelikhan** [comment]
Added autofocus + aria-label
