### ISSUE TITLE
devtools disconnect from dashboard upon laptop sleep

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#878]
repro:
* run `jacdac devtools  --packets`
* spin a button in dashboard
* sleep the laptop
* wake the laptop
* pressing buttons no longer generates packets in the console (dashboard simply disconnected from the node server, which keeps running)

This is a bit of a problem if you have a testing setup with simulators - reloading the page kills them all.

Additional problem: if you stop the devtools there is no indication the connection was broken in the dashboard

**Comment by pelikhan** [comment]
The devtools page tries to reconnect to the websocket every 5s in v1.2.1
