### ISSUE TITLE
update hardware design info

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#881]
Fill up "hardwareDesign" field for released modules.
- [ ] fill info
- [ ] run ``yarn buildspecs` from jacdac-docs
- [ ] push jacdac-spec, jacdac-ts, jacdac-docs

**Comment by pelikhan** [comment]
https://microsoft.github.io/jacdac-docs/devices/ has now a filter for those entries

**Comment by tballmsft** [comment]
@jamesadevine  - I am making a pass. Some notes

- Firmware for following is at 40-0.2 (what gives?): https://github.com/microsoft/jacdac-ddk/tree/main/electronics/altium/reference-designs/JacdacG0Button%2040-0.3

**Comment by tballmsft** [comment]
See https://github.com/microsoft/jacdac/pull/882

**Comment by jamesadevine** [comment]
The designs had a version bump with minor changes before uploading I believe.

James
________________________________

**Comment by tballmsft** [comment]
no worries.

**Comment by jamesadevine** [comment]
I dunno, perhaps we should create the firmware for these new versions — it’s a bit inconsistent

James
________________________________
