### ISSUE TITLE
react-jacdac

### ISSUE THREAD

**Issue by ruyi-tsai** [microsoft/jacdac#884]
**Describe the bug**
react-jacdac exective yarn watch not success

**To Reproduce**
```
uyi@ruyi-VirtualBox:~/react-jacdac$ yarn watch
yarn run v1.22.17
$ microbundle --jsx React.createElement watch
Watching source, compiling to dist:
Wrote 1534 B: react-jacdac.modern.js.gz
       1334 B: react-jacdac.modern.js.br
Wrote 1541 B: react-jacdac.cjs.gz
       1343 B: react-jacdac.cjs.br
Wrote 1565 B: react-jacdac.module.js.gz
       1371 B: react-jacdac.module.js.br
Wrote 1626 B: react-jacdac.umd.js.gz
       1431 B: react-jacdac.umd.js.br
```
 always keep this line ?
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61086995/148892895-7ebc6279-ad55-4dae-89b8-d4a96ab8f16d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pelikhan** [comment]
This looks about right, what is the issue?

**Comment by pelikhan** [comment]
Please reopen with more details.
