### ISSUE TITLE
devtools doesn't pass ?passive=1

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#886]
devtools (npm jacdac-cli package) doesn't pass query arguments to inner dashboard frame, eg http://localhost:8081/?passive=1 will load https://microsoft.github.io/jacdac-docs/dashboard/#0.3615932725927158 and not https://microsoft.github.io/jacdac-docs/dashboard/?passive=1#0.3615932725927158

**Comment by pelikhan** [comment]
fixed in https://github.com/microsoft/jacdac/issues/886

**Comment by pelikhan** [comment]
and https://github.com/microsoft/jacdac-docs/commit/4f3cfafc5448e575a4939f5b9aa1ca7912d4fbc5
