### ISSUE TITLE
Streaming stops when simulator goes out of view

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#894]
**Describe the bug**
In MakeCode, it appears that when the micro:bit simulator goes out of view, the browser stops acting as a brain. See:

![makecode-streaming-stop](https://user-images.githubusercontent.com/4742697/151960858-fce2a556-24bf-4a08-823a-e7190bfbc206.gif)

This could be confusing for users.

**Comment by pelikhan** [comment]
It's a performance feature :)

**Comment by jamesadevine** [comment]
Yeah, I get that! Will users understand that? :smile:

**Comment by pelikhan** [comment]
I need to set the bus to streaming while the console view is visible... i don't know when the console view is visible. 

If the users start enough simulators, then we run into perf issues...
