### ISSUE TITLE
Should we  be smarter when writing to LEDs

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#895]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4742697/151961629-0016e858-38bb-475a-ab67-da8dbb5aadb8.png)

The program above hammers the bus when the `pause 500 ms` block is removed.

MakeCode share URL, here:
https://makecode.microbit.org/_TR4Ji2Vukg0E

I get the sense that we should be smarter when writing to sensors, just as we are when reading sensors. This might be a challenge as duplicating state is often a bad idea. Especially so with the LED module, where writing to individual pixels is not well supported as updates can be lost.

We have previously made similar decisions to protect users such as with the `forever` loop. The `forever` loop has a built in pause of 10 ms to yield control of the fiber and allow concurrent operation. Do we need to have a similar protection model here (i.e. a caching layer)?

Thoughts @pelikhan @mmoskal @tballmsft ?

**Comment by jamesadevine** [comment]
Yes, maybe it is a bad example. To what degree do we protect the user from this though?

**Comment by mmoskal** [comment]
I think we don't. 

Otherwise we'll need some thresholds when to decide not to write to a register, and that can easily lead to problems
(eg  `forever{ lamp.setBrightness(slider.value) }` - the nice thing is the slider jitters a little ).

**Comment by mmoskal** [comment]
Which makes me think the minimum period in VM's `every(...)` function should probably be 100ms or so, not the current 20ms.

**Comment by mmoskal** [comment]
We could also print out some warning to the user in MakeCode, telling them they are sending too many packets? Or in general have some sort of bus utilization gauge.

**Comment by jamesadevine** [comment]
> We could also print out some warning to the user in MakeCode, telling them they are sending too many packets? Or in general have some sort of bus utilization gauge.

Nice, that would be neat. However, the impact of the code without pause is that the browser sim also can't handle the data rate. This might make it hard to do a bus utilization gauge?

**Comment by mmoskal** [comment]
Well, then maybe the sim should start dropping packets and flashing red :)

**Comment by jamesadevine** [comment]
Ha, that sounds neat...

**Comment by pelikhan** [comment]
IMO just like the forever loop, we need to make our runtime resilient to this. Unclear that people will understand warnings.

The setting 1 led at a time is a particularly doomed example. It leads to missed leds, and would be better if we sent a full buffer each time.

**Comment by pelikhan** [comment]
> Well, then maybe the sim should start dropping packets and flashing red :)

They'll surely think that Jacdac is broken.

**Comment by tballmsft** [comment]
@pelikhan says we are double buffering - needs to be tested

**Comment by tballmsft** [comment]
Nice and fast now, no discernable delay anywhere...

**Comment by tballmsft** [comment]
@pelikhan - here is updated program, can you also test with KB hardware: https://makecode.microbit.org/_gvd8Y94vkRkt
