### ISSUE TITLE
super noisy slider (bad hardware)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#898]
- I have slider module connected to microbit via jacdaptor
- microbit is programmed with jacdac extension (via makecode)
- micro:bit successfully connected to dashboard
- slider twin shows slider around 24%, when physical slider set to 0
![image](https://user-images.githubusercontent.com/10767146/152232796-a0d934d0-f9cf-4426-a5e3-f7ed07855273.png)
- a quick move of slider to either end will result in brief change to twin, but then returns to around 24%

**Comment by mmoskal** [comment]
Throw it away?

**Comment by jamesadevine** [comment]
This is the one that was returned by Harish?

I'd check the solder joints... What is the board revision? Probably, as michal says, it's not worth the time to debug. Easier to just throw it away!

**Comment by pelikhan** [comment]
Keep it and send it to me. Our software stack should be able to diagnose issues and flag issues
________________________________
