### ISSUE TITLE
Device says initialising

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#899]
I haven't seen this before. Today, devices on the dashboard and in MakeCode have started saying initialising:

![image](https://user-images.githubusercontent.com/4742697/152335471-2e4ad9b0-b794-48a5-8063-faab5a4dda7d.png)

This initialising toast does not go away.

**Comment by pelikhan** [comment]
The UI reflects the state of the status_code register, which in the case of the slider stays at 0x1

![image](https://user-images.githubusercontent.com/4175913/152365795-6d3f82cf-35bd-4150-bf36-85ebd363bfa8.png)

**Comment by pelikhan** [comment]
This is a new feature where I actually sniff the status code and surface potential error modes.

**Comment by jamesadevine** [comment]
Can you turn it off for now? We are about to conduct a user study.

**Comment by jamesadevine** [comment]
I've already shipped the hardware so I cannot update the module firmware.

**Comment by pelikhan** [comment]
I will. Keep this bug open, the firmware needs to be fixed and deployed so that we can upgrade devices.

**Comment by jamesadevine** [comment]
Agreed! Cheers peli
