### ISSUE TITLE
Fix polling strategy

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#9]
Too much polling or too little

**Comment by pelikhan** [comment]
Min polling interval would be enough. Thermometer (10s) vs accelerometer (20ms). max could be considered the cut-off frequency which also also to create a low-pass filter. Do the device filter data by default?

**Comment by pelikhan** [comment]
See also https://github.com/microsoft/jacdac/issues/18

**Comment by tballmsft** [comment]
This discussion relates to the service specification. Do we want a const or a register for the polling value?

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac/pull/92
