### ISSUE TITLE
button simulator responds 15 times to status report query

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#901]
repro:
* run devtools
* spin button simulator
* look at packet console - see 15 repetitions of get status_code

not blocking

**Comment by pelikhan** [comment]
cli devtools?

**Comment by mmoskal** [comment]
yeah, the ones from npm

**Comment by pelikhan** [comment]
There is definitely this bug that could have affected you, it created the repeated packets. Might be more.
https://github.com/microsoft/jacdac-docs/commit/6d8580a868e49b952c88ebcff65ca574b291b29a

**Comment by pelikhan** [comment]
SHould be fixed now.
