### ISSUE TITLE
QR code scale factor is wrong in produced file

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#915]

**Comment by jamesadevine** [comment]
e.g. the page shows expected QR code dimensions to be 3.5 mm x 3.5 mm, however actual dimensions are 5 mm x 5 mm.

**Comment by pelikhan** [comment]
what URL do you use? how do i repro this?

**Comment by jamesadevine** [comment]
Yes, I filed this issue poorly.

1) Enter any url. I used a longer url, but the issue applies to short urls too. `https://microsoft.com/abc123/abc123/abc123/abc123`.

2) "original size" reported is 9 mm x 9 mm:
![image](https://user-images.githubusercontent.com/4742697/156765825-5406c084-6646-48c7-8f57-29481255e50e.png)

3) import into CAD editor, and the dimensions are bigger than reported:

![image](https://user-images.githubusercontent.com/4742697/156765982-a93a901f-9b7d-4b53-8072-926368c17051.png)

**Comment by pelikhan** [comment]
which file format and which CAD editor?

**Comment by jamesadevine** [comment]
Any format, any editor

**Comment by pelikhan** [comment]
Removed margins in https://github.com/microsoft/jacdac-docs/commit/9a9b1c6b4803fe2fb983f6d34ce4f4437a50af8e which seemed to fix the issue.
This page needs more documentation on how to use these files.

**Comment by pelikhan** [comment]
Reopen if still an issue.

**Comment by jamesadevine** [comment]
Cheers Peli!

CC @xmeow

**Comment by pelikhan** [comment]
Wait for this build https://github.com/microsoft/jacdac-docs/runs/5425509661?check_suite_focus=true
