### ISSUE TITLE
Pixel ordering on RGB LED devices

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#918]
Pixel order in hardware might be different from that on simulator (e.g. RGB ring). How do we unify hardware pixel ordering and simulator pixel ordering? A service const? Or specify pixel order relative to some feature on the board?

**Comment by pelikhan** [comment]
We can have a const "offset" register and a "orientation" (cw or ccw), or we can keep adding more variations to the variant (ringCCW).

For short strips, we could have a const that returns a sequence of (x,y) positions on a 0-255mm grid? This would cover arbitrary layout but we would probably have to build a tool to build those.
________________________________

**Comment by mmoskal** [comment]
IMHO we should mandate clockwise; are the existing rings CCW? both of my rings (the ones I designed) are clockwise

**Comment by jamesadevine** [comment]
We need to discuss and resolve this in today's meeting if possible.

**Comment by pelikhan** [comment]
Let's go with the second image, it matches the rotary encoder. CW, first LED (0) on the left.

**Comment by pelikhan** [comment]
UI now ordering clock-wize starting from left https://github.com/microsoft/jacdac-docs/commit/b4f9f30266e5c7c8a8a0e6f1107ed2e44fdcbf3d
