### ISSUE TITLE
Fix font/color on labels on home screen

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#933]
![image](https://user-images.githubusercontent.com/4175913/157731466-dd11104a-a5f1-4b65-8a6f-fd5b30cf81d5.png)

labels on the image don't match color/font of the page.

**Comment by tballmsft** [comment]
What is the font I should use?

**Comment by tballmsft** [comment]
Here's the image with same font, in black. 
![image](https://user-images.githubusercontent.com/10767146/157733780-749ce32e-5014-4660-9e5e-8e7e55fddecf.png)

**Comment by pelikhan** [comment]
SFMono-Regular

**Comment by tballmsft** [comment]
Hmm... what's the corresponding font in PowerPoint?

**Comment by pelikhan** [comment]
unknown. this image could also be done as a grid in HTML to leverage the font in the browser.

**Comment by tballmsft** [comment]
OK. I send it back to you.
