### ISSUE TITLE
Add "+ New service" button to service catalog

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#937]
Would it be possible to add a button to the service catalog page to make it easier to find out how to create a new service?

![image](https://user-images.githubusercontent.com/4742697/158403419-68842828-9c52-427d-b128-ecf294d46fe9.png)

e.g. in the top right of this page?

**Comment by pelikhan** [comment]
Where does it point to?
________________________________

**Comment by jamesadevine** [comment]
The service editor/creator! Or does that no longer exist?

James
________________________________

**Comment by pelikhan** [comment]
There is a note at the very bottom, do we want to make it "top level"?

**Comment by jamesadevine** [comment]
It depends if we want it to be easily discoverable or not... I always struggle to find the service editor, so i'm a bit biased.

**Comment by pelikhan** [comment]
When the search yields nothing, it gets visible. We could add a button there.
![image](https://user-images.githubusercontent.com/4175913/158419319-2fd410c1-54dc-4d8e-aa95-a7d9f28084a8.png)

**Comment by jamesadevine** [comment]
In that case, I think the "see also" covers it. Perhaps the button is not required.
