### ISSUE TITLE
Simulator: power supply

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#939]
Can we get a simulator for the dashboard for the power supply service?

The dashboard already shows an enabled toggle, but it would be good to have a slider between voltage_min and voltage_max if possible. There should probably be some default UI for all services that use the `min_value` `max_value` registers?

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/jacdac-docs/commit/ce90341465457808ac1fcb1f0c8254538aba236d
