### ISSUE TITLE
Template repo for firmware

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#968]
Having users clone MSR-modules leads to generated firmware with all existing MSR modules, since users are unlikely to delete any of them.

**Comment by mmoskal** [comment]
repo created: https://github.com/microsoft/jacdac-module-template
ready for a test ride!

**Comment by pelikhan** [comment]
Maybe have the example be a button? Seems easier to start than a powered device like a servo

**Comment by mmoskal** [comment]
changed example to button
