### ISSUE TITLE
OOB interaction with module tester

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#986]
1. flash micro:bit with new OOB (microbit-machine
2. add our rotary encoder
3. see that the micro:bit responds both to button press and turning
4. connect to module tester
5. wait for test to start
6. see that micro:bit still responds to button press but not to turning (while digital twin does respond to turning)

**Comment by pelikhan** [comment]
hugh.... module tester needs to put the microbit in proxy mode

**Comment by pelikhan** [comment]
forcing proxy mode
